### PR TITLE
Fixes #3450 AMP Markup Incompatibilities with preload links and delay JS features

### LINKED ISSUE #3450: Official AMP plugin compatibility: issues upon activation with certain options
**Describe the bug**

We've received a few reports ([like this one](https://wordpress.org/support/topic/cache-amp-plugin-which-one-is-the-best-to-work-together/)) of some potential issues when using [the AMP plugin](https://wordpress.org/plugins/amp/) with WP Rocket. In testing, the AMP plugin detects 5 instances of invalid markup being placed on AMP content upon activation and persistently with a few options enabled:

Screen Shot 2020-12-18 at 6 30 52 PM

Screen Shot 2020-12-23 at 2 50 21 PM

Since the AMP plugin automatically detects and removes the invalid markup, the AMP content remains valid. However, to [maintain compatibility](https://docs.wp-rocket.me/article/1326-amp-compatibility) and a good user experience, it would be best to prevent this from occurring. 

**To Reproduce**
1. Install and activate WP Rocket on a site using the AMP plugin
2. Go to _AMP > Validated URLs_ to see invalid markup detected and removed
3. [Recheck URLs](https://jmp.sh/DJmIfV5) to see the invalid markup for **Optimize CSS Delivery** and **Delay JS execution** resolve. 
4. Notice that invalid markup for **Preload links** remains.

**Expected behavior**

No invalid markup on AMP content and validation errors flagged by the AMP plugin.

**Screenshots**

**Options that cause invalid markup with links to screenshots**

[Preload links](https://jmp.sh/3aON5tl) (occurs upon activation and persists)

[Optimize CSS delivery](https://jmp.sh/nREtsG8) (occurs upon activation, but resolves after rechecking the URLS)

[Delay JavaScript execution](https://jmp.sh/aK3MWZr) (occurs upon activation, but resolves after rechecking the URLs)

**Additional context**

Some of these may appear in certain site setups and not others. Details of my test below: 

<details>
<summary>Site Health Info</summary>

```

### wp-core ###

version: 5.6
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/fastcms1/example.com
wordpress_size: 61.09 MB (64055503 bytes)
uploads_path: /home/fastcms1/example.com/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /home/fastcms1/example.com/wp-content/themes
themes_size: 8.27 MB (8673288 bytes)
plugins_path: /home/fastcms1/example.com/wp-content/plugins
plugins_size: 22.70 MB (23799327 bytes)
database_size: 3.53 MB (3706713 bytes)
total_size: 95.59 MB (100234831 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Twenty Twenty-One (twentytwentyone)
version: 1.1
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, title-tag, post-formats, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, custom-background, editor-color-palette, editor-gradient-presets, responsive-embeds, custom-line-height, experimental-link-color, custom-spacing, custom-units, amp, widgets
theme_path: /home/fastcms1/example.com/wp-content/themes/twentytwentyone
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.9, author: the WordPress team, Auto-updates disabled
Twenty Seventeen: version: 2.5, author: the WordPress team, Auto-updates disabled
Twenty Twenty: version: 1.6, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (2) ###

AMP: version: 2.0.9, author: AMP Project Contributors, Auto-updates disabled
WP Rocket: version: 3.8.1, author: WP Media, Auto-updates disabled

### wp-plugins-inactive (4) ###

Akismet Anti-Spam: version: 4.1.7, author: Automattic, Auto-updates disabled
All-in-One WP Migration: version: 7.32, author: ServMask, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled
Site Kit by Google: version: 1.23.0, author: Google, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
gd_version: 2.2.5
ghostscript_version: 8.70

### wp-server ###

server_architecture: Linux 2.6.32-954.3.5.lve1.4.71.el6.x86_64 x86_64
httpd_software: Apache/2.4.46 (cPanel) OpenSSL/1.1.1h mod_bwlimited/1.4 Phusion_Passenger/5.3.7
php_version: 7.4.13 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: -1
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.71.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.32-log
client_version: mysqlnd 7.4.13

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/fastcms1/example.com/wp-content
WP_PLUGIN_DIR: /home/fastcms1/example.com/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### amp_wp ###

amp_mode_enabled: transitional
amp_reader_theme: legacy
amp_templates_enabled: post, page, is_singular, is_home, is_archive, is_author, is_date, is_search, is_404, is_category, is_tag
amp_serve_all_templates: true
amp_css_transient_caching_disabled: false
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: 34
amp_css_transient_caching_time_series: 
	20201219: 0
	20201223: 14
	20201224: 34
amp_libxml_version: 2.9.4

```

</details>

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by iCaspar**
Closes #3450.

Add a `do_rocket_preload_links` filter to allow/disallow disable preload links feature.
Add a `do_rocket_delay_js` filter to allow/disallow delay JS feature.

Hook `return_false()` to new filters in AMP subscriber to prevent incompatible HTML.

### CODE REVIEW

**Review by crystinutzaa — APPROVED** [review]

**Comment by iCaspar** [comment]
@wp-media/qa This is ready for QA. Please see #3450 for criteria that should be fixed, it is very well laid out there.

File: inc/Engine/Optimization/DelayJS/HTML.php [hunk 1]
```diff
@@ -69,6 +69,17 @@ public function is_allowed() {
...
 		}
 
+		/**
+		 * Filter whether to allow rocket to enable delay JS.
+		 *
+		 * @since 3.8.4
+		 *
+		 * @param bool $do_delay_js Whether to enable preload links. Default is true.
+		 */
+		if ( ! (bool) apply_filters( 'do_rocket_delay_js', true ) ) { // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound
```
Comment (remyperona) [inline inc/Engine/Optimization/DelayJS/HTML.php]:
```suggestion
		if ( ! (bool) apply_filters( 'rocket_do_delay_js', true ) ) {
```

File: inc/Engine/Preload/Links/Subscriber.php [hunk 2]
```diff
@@ -61,10 +61,22 @@ public function add_preload_script() {
...
 		}
 
+		/**
+		 * Filter whether to allow rocket to enable preload links.
+		 *
+		 * @since 3.8.4
+		 *
+		 * @param bool $do_preload_links Whether to enable preload links. Default is true.
+		 */
+		if ( ! (bool) apply_filters( 'do_rocket_preload_links', true ) ) { //phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound
```
Comment (remyperona) [inline inc/Engine/Preload/Links/Subscriber.php]:
```suggestion
		if ( ! (bool) apply_filters( 'rocket_do_preload_links', true ) ) {
```

File: inc/ThirdParty/Plugins/Optimization/AMP.php [hunk 3]
```diff
@@ -113,6 +113,8 @@ public function disable_options_on_amp() {
 		remove_filter( 'wp_resource_hints', 'rocket_dns_prefetch', 10, 2 );
 		add_filter( 'do_rocket_lazyload', '__return_false' );
 		add_filter( 'do_rocket_lazyload_iframes', '__return_false' );
+		add_filter( 'do_rocket_delay_js', '__return_false' );
+		add_filter( 'do_rocket_preload_links', '__return_false' );
```
Comment (remyperona) [inline inc/ThirdParty/Plugins/Optimization/AMP.php]:
```suggestion
		add_filter( 'rocket_do_delay_js', '__return_false' );
		add_filter( 'rocket_do_preload_links', '__return_false' );
```

File: tests/Integration/inc/Engine/Optimization/DelayJS/Subscriber/delayJs.php [hunk 4]
```diff
@@ -20,6 +20,7 @@ public function tearDown() {
 		unset( $GLOBALS['wp'] );
 		remove_filter( 'pre_get_rocket_option_delay_js', [ $this, 'set_delay_js_option' ] );
 		remove_filter( 'pre_get_rocket_option_delay_js_scripts', [ $this, 'set_delay_js_scripts_option' ] );
+		remove_filter( 'do_rocket_delay_js', '__return_false' );
```
Comment (remyperona) [inline tests/Integration/inc/Engine/Optimization/DelayJS/Subscriber/delayJs.php]:
```suggestion
		remove_filter( 'rocket_do_delay_js', '__return_false' );
```

File: tests/Integration/inc/Engine/Optimization/DelayJS/Subscriber/delayJs.php [hunk 5]
```diff
@@ -61,4 +67,10 @@ public function set_delay_js_option() {
 	public function set_delay_js_scripts_option() {
 		return isset( $this->options_data[ 'delay_js_scripts' ] ) ? $this->options_data[ 'delay_js_scripts' ] : [];
 	}
+
+	public function set_do_rocket_delay_js_filter( bool $do_delay = true ): void {
+		if ( ! $do_delay ) {
+			add_filter( 'do_rocket_delay_js', 'return_false' );
```
Comment (remyperona) [inline tests/Integration/inc/Engine/Optimization/DelayJS/Subscriber/delayJs.php]:
```suggestion
			add_filter( 'rocket_do_delay_js', 'return_false' );
```

File: tests/Integration/inc/Engine/Preload/Links/Subscriber/addPreloadScript.php [hunk 6]
```diff
@@ -17,6 +17,7 @@ public function tearDown() {
 
 		unset( $GLOBALS['wp'] );
 		remove_filter( 'pre_get_rocket_option_preload_links', [ $this, 'set_preload_links' ] );
+		remove_filter( 'do_rocket_preload_links', '__return_false' );
```
Comment (remyperona) [inline tests/Integration/inc/Engine/Preload/Links/Subscriber/addPreloadScript.php]:
```suggestion
		remove_filter( 'rocket_do_preload_links', '__return_false' );
```

File: tests/Integration/inc/Engine/Preload/Links/Subscriber/addPreloadScript.php [hunk 7]
```diff
@@ -38,6 +39,10 @@ public function testShouldDoExpected( $config, $expected ) {
 			$GLOBALS['wp']->query_vars['nowprocket'] = 1;
 		}
 
+		if ( isset( $config['preload_filter'] ) && false === $config['preload_filter'] ) {
+			add_filter( 'do_rocket_preload_links' , '__return_false' );
```
Comment (remyperona) [inline tests/Integration/inc/Engine/Preload/Links/Subscriber/addPreloadScript.php]:
```suggestion
			add_filter( 'rocket_do_preload_links' , '__return_false' );
```

File: tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php [hunk 8]
```diff
@@ -36,6 +36,9 @@ public function testShouldDoExpected( $config, $expected ) {
 			$this->assertNotFalse( has_filter( 'wp_resource_hints', 'rocket_dns_prefetch' ) );
 			$this->assertFalse( has_filter( 'do_rocket_lazyload', '__return_false' ) );
 			$this->assertFalse( has_filter( 'do_rocket_lazyload_iframes', '__return_false' ) );
+			$this->assertFalse( has_filter( 'do_rocket_delay_js', '__return_false' ) );
+			$this->assertFalse( has_filter( 'do_rocket_preload_links', '__return_false' ) );
```
Comment (remyperona) [inline tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php]:
```suggestion
			$this->assertFalse( has_filter( 'rocket_do_delay_js', '__return_false' ) );
			$this->assertFalse( has_filter( 'rocket_do_preload_links', '__return_false' ) );
```

File: tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php [hunk 9]
```diff
@@ -55,6 +58,8 @@ public function testShouldDoExpected( $config, $expected ) {
 			$this->assertFalse( has_filter( 'wp_resource_hints', 'rocket_dns_prefetch' ) );
 			$this->assertNotFalse( has_filter( 'do_rocket_lazyload', '__return_false' ) );
 			$this->assertNotFalse( has_filter( 'do_rocket_lazyload_iframes', '__return_false' ) );
+			$this->assertNotFalse( has_filter( 'do_rocket_delay_js', '__return_false' ) );
+			$this->assertNotFalse( has_filter( 'do_rocket_preload_links', '__return_false' ) );
```
Comment (remyperona) [inline tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php]:
```suggestion
			$this->assertNotFalse( has_filter( 'rocket_do_delay_js', '__return_false' ) );
			$this->assertNotFalse( has_filter( 'rocket_do_preload_links', '__return_false' ) );
```

File: tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php [hunk 10]
```diff
@@ -52,6 +52,10 @@ public function testShouldDoExpected( $config, $expected ) {
 			);
 			$this->assertFalse( has_filter( 'do_rocket_lazyload', '__return_false' ) );
 			$this->assertFalse( has_filter( 'do_rocket_lazyload_iframes', '__return_false' ) );
+			$this->assertFalse( has_filter( 'do_rocket_lazyload_iframes', '__return_false' ) );
+			$this->assertFalse( has_filter( 'do_rocket_delay_js', '__return_false' ) );
+			$this->assertFalse( has_filter( 'do_rocket_preload_links', '__return_false' ) );
```
Comment (remyperona) [inline tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php]:
```suggestion
			$this->assertFalse( has_filter( 'rocket_do_delay_js', '__return_false' ) );
			$this->assertFalse( has_filter( 'rocket_do_preload_links', '__return_false' ) );
```

**Review by remyperona — CHANGES_REQUESTED** [review]
the `do_rocket_` is the naming we used early one, before having any kind of coding standards.

Moving forward, let's always prefix our filters corectly with `rocket_`, for consistency.

**Review by remyperona — APPROVED** [review]

**Comment by remyperona** [comment]
@wp-media/qa ready for QA

**Review by piotrbak — APPROVED** [review]
Worked as expected:
[testrail-report-112.pdf](https://github.com/wp-media/wp-rocket/files/5867059/testrail-report-112.pdf)
