### PR TITLE
Fix Divi Logo image distortion from setting image dimensions

### LINKED ISSUE #3429: 3.8 - Divi/Extra: logo is distorted when adding missing image dimensions
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When using:
1. The Divi theme.
2. The **Add missing image dimensions** feature is enabled.

the logo is distorted:

Normally, it should be like this:

Divi stores the logo's height in a custom attribute: `data-height-percentage` and uses the following function to calculate the logo's dimensions:
```JAVASCRIPT
function E(e) {
            var n, r = t("body"), i = t("#logo"), o = parseInt(i.attr("data-actual-width")), a = parseInt(i.attr("data-actual-height")), s = parseInt(i.attr("data-height-percentage")), c = t("#et-top-navigation"), u = parseInt(c.attr("data-height")), l = parseInt(c.attr("data-fixed-height")), d = t("#main-header"), f = r.hasClass("et_header_style_split"), p = d.hasClass("et-fixed-header"), _ = r.hasClass("et_hide_primary_logo"), h = r.hasClass("et_hide_fixed_logo"), v = p ? u : l;
            e = void 0 !== e && e,
            f && !window.et_is_vertical_nav && (e && (v = u),
            n = o * ((v * (s / 100) + 22) / a),
            _ && (p || e) && (n = 0),
            !h || p || e || (n = 0),
            t(".et_header_style_split .centered-inline-logo-wrap").css({
                width: n
            }))
        }
```
**File:** `Divi/js/custom.unified.js`

Setting a fixed width/height causes the logo to be distorted.

**To Reproduce**
1. Go to MEGA/Divi.
2. Enable the **Add missing image dimensions** feature.
3. Visit the front-end and scroll to see the distorted logo.

**Expected behavior**

The logo should not be distorted.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1370025086/223865/

**Slack Convo:** https://wp-media.slack.com/archives/C43T1AYMQ/p1608486013007400?thread_ts=1608459676.004200&cid=C43T1AYMQ

Maybe we can add a filter in the following method, so we can exclude custom attributes like `data-height-percentage`:
https://github.com/wp-media/wp-rocket/blob/0c6c60c8246907979bb2075e37c412f5efaeea21/inc/Engine/Media/ImageDimensions/ImageDimensions.php#L315-L329

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by iCaspar**
Closes #3429 

- [x] Add filter to Divi compatibility file to disable setting image dimensions on `data-height-percentage`
- [x] Add unit test and fixtures

### CODE REVIEW

File: inc/ThirdParty/Themes/Divi.php [hunk 1]
```diff
@@ -108,6 +113,29 @@ public function add_divi_to_description( $disable_youtube_lazyload ) {
...
+	 * Disables setting explicit dimensions on images where Divi calculates height as percentage.
+	 *
+	 * @since 3.8.2
+	 *
+	 * @param array $images The array of images selected for adding image dimensions.
+	 *
+	 * @return array The array without images using data-height-percentage.
+	 */
+	public function disable_image_dimensions_height_percentage( array $images ) {
+		if ( ! self::is_divi() ) {
```
Comment (engahmeds3ed) [inline inc/ThirdParty/Themes/Divi.php:126]: why this checking here?
I can see that this callback won't be called from `get_subscribed_events` method if it's not Divi, I think no need to use it here.

File: inc/ThirdParty/Themes/Divi.php [hunk 2]
```diff
@@ -108,6 +113,29 @@ public function add_divi_to_description( $disable_youtube_lazyload ) {
...
+			return $images;
+		}
+
+		foreach ( $images as $key => $image ) {
```
Comment (engahmeds3ed) [inline inc/ThirdParty/Themes/Divi.php:130]: I think this check is case insensitive, can we check the following proposed solution if it's faster or not
```
return array_filter($images, function($img) {
	return ! preg_match('#data-height-percentage#i', $img);
});
```

File: inc/ThirdParty/Themes/Divi.php [hunk 3]
```diff
@@ -108,6 +113,29 @@ public function add_divi_to_description( $disable_youtube_lazyload ) {
...
+			if ( false !== strpos( $image, 'data-height-percentage' ) ) {
+				unset( $images[ $key ] );
+			}
+		}
+
+		return array_values( $images );
```
Comment (engahmeds3ed) [inline inc/ThirdParty/Themes/Divi.php:136]: we don't care about returning array values only on the main filter usage as we won't use keys.
So u can adjust the test code only to use this `array_values` or not based on the fixture.

File: tests/Fixtures/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php [hunk 4]
```diff
@@ -0,0 +1,46 @@
+<?php
```
Comment (engahmeds3ed) [inline tests/Fixtures/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php:1]: Add fixture for `DATA-HEIGHT-PERCENTAGE` with uppercase.

File: tests/Unit/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+ * @covers \WP_Rocket\ThirdParty\Themes\Divi::disable_image_dimensions_height_percentage
+ * @uses   ::is_divi
+ *
+ * @group  ThirdParty
+ */
+class Test_DisableImageDimensionsHeightPercentage extends TestCase {
+	/**
+	 * @dataProvider providerTestData
+	 */
+	public function testAddDiviToDescription( $config, $expected ) {
```
Comment (engahmeds3ed) [inline tests/Unit/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php:21]: where is integration test, I think we need it and keep in mind that we need to save the current theme at setup and then revert it back at tearDown

**Review by engahmeds3ed — CHANGES_REQUESTED** [review]

File: inc/ThirdParty/Themes/Divi.php (hunk 1 above)
Comment (iCaspar) [reply inc/ThirdParty/Themes/Divi.php:126]: This is called from `get_subscribed_events()` on L:51, above.
If not guarded here, the testcase for leaving things alone for other themes will fail -- see this testcase:
https://github.com/wp-media/wp-rocket/blob/76838b53857ced21499de0869953b6f459e70aa0/tests/Fixtures/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php#L32

File: inc/ThirdParty/Themes/Divi.php (hunk 2 above)
Comment (iCaspar) [reply inc/ThirdParty/Themes/Divi.php:130]: Divi specifically defines this, so while it's pretty certain that it will always come to us lowercase, I agree that making case insensitive is safer.

Current solution adding `strtolower()` runs on average half the time as the regex in my tests.

File: tests/Unit/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php (hunk 5 above)
Comment (iCaspar) [reply tests/Unit/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php:21]: Done... The WPThemeTestcase we're extending takes care of setting theme at setup and teardown. :)

File: inc/ThirdParty/Themes/Divi.php (hunk 2 above)
Comment (engahmeds3ed) [reply inc/ThirdParty/Themes/Divi.php:130]: Great

File: tests/Unit/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php [hunk 6]
```diff
@@ -0,0 +1,41 @@
+<?php
+
+namespace WP_Rocket\Tests\Unit\inc\ThirdParty\Themes\Divi;
+
+use Mockery;
+use WP_Rocket\Tests\Unit\TestCase;
+use Brain\Monkey\Functions;
+use WP_Rocket\ThirdParty\Themes\Divi;
+use WP_Theme;
```
Comment (Tabrisrp) [inline tests/Unit/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php:9]:
```suggestion
use Brain\Monkey\Functions;
use Mockery;
use WP_Rocket\Tests\Unit\TestCase;
use WP_Rocket\ThirdParty\Themes\Divi;
use WP_Theme;
```

File: tests/Unit/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+ *
+ * @group  ThirdParty
+ */
+class Test_DisableImageDimensionsHeightPercentage extends TestCase {
+	/**
+	 * @dataProvider providerTestData
+	 */
+	public function testAddDiviToDescription( $config, $expected ) {
+		$options_api = Mockery::mock( 'WP_Rocket\Admin\Options' );
+		$options     = Mockery::mock( 'WP_Rocket\Admin\Options_Data' );
```
Comment (Tabrisrp) [inline tests/Unit/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php:23]:
```suggestion
		$options_api = Mockery::mock( Options::class );
		$options        = Mockery::mock( Options_Data::class );
```

File: tests/Integration/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php [hunk 8]
```diff
@@ -0,0 +1,68 @@
+<?php
+namespace WP_Rocket\Tests\Integration\inc\ThirdParty\Themes\Divi;
+
+use WP_Rocket\Tests\Integration\WPThemeTestcase;
+use WP_Rocket\ThirdParty\Themes\Divi;
```
Comment (Tabrisrp) [inline tests/Integration/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php:5]:
```suggestion
```

File: tests/Integration/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php [hunk 9]
```diff
@@ -0,0 +1,68 @@
...
+
+	public function setUp() {
+		parent::setUp();
+
+		self::$container->get( 'event_manager' )->add_subscriber( self::$container->get( 'divi' ) );
+	}
+
+	public function tearDown() {
+		if ( isset( $this->config_data['image_dimensions'] ) ){
+			remove_filter( 'pre_get_rocket_option_image_dimensions', [$this, 'set_image_dimensions'] );
```
Comment (Tabrisrp) [inline tests/Integration/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php:37]: the `set_image_dimensions()` method doesn't exist in this file

File: tests/Integration/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php [hunk 10]
```diff
@@ -0,0 +1,68 @@
...
+
+		if ( ! $config['is-child'] ) {
+			$this->set_theme( $config['stylesheet'], $config['theme-name'] );
+		} else {
+			$this->set_theme( $config['is-child'], $config['parent-name'] )
+				->set_child_theme( $config['stylesheet'], $config['theme-name'], $config['is-child'] );
+		}
+
+		switch_theme( $config['stylesheet'] );
+		add_filter( 'rocket_specify_image_dimensions', '__return_true' );
```
Comment (Tabrisrp) [inline tests/Integration/inc/ThirdParty/Themes/Divi/disableImageDimensionsHeightPercentage.php:61]: This is set, but not removed on tearDown

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Comment by Tabrisrp** [comment]
@wp-media/qa ready for QA

**Review by piotrbak — APPROVED** [review]
Worked as expected, the requested changes are related to the tests:
[testrail-report-97.pdf](https://github.com/wp-media/wp-rocket/files/5765847/testrail-report-97.pdf)
