### PR TITLE
Closes #7732: Duplicated id for global score widget during polling

### LINKED ISSUE #7732: Duplicated id for global score widget during polling
**Describe the bug**
The global score widget has a duplicated id `wpr_global_score_widget`

**To Reproduce**
1. Fresh install & activate
2. Go to dashboard while homepage result is being generated
3. Wait for the polling to kick in
4. Inspect element of the global score widget
5. See `wpr_global_score_widget` duplicated

**Expected behavior**
There should be duplicated id of `wpr_global_score_widget`

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by jeawhanlee**
# Description

Fixes #7732 
This PR fixes the issue with having duplicated ids when polling new data for the global score widget.

## Type of change

- [x] New feature (non-breaking change which adds functionality).
- [x] Bug fix (non-breaking change which fixes an issue).

### What was tested

Tested that during polling when url reports are still being generated, the global score widget element does not have the id - `wpr_global_score_widget` duplicated

### How to test

Same as how to reproduce in the [issue](https://github.com/wp-media/wp-rocket/issues/7732)

### Documentation

Created a new part for the global score widget to be shared with the payload data during polling.

### New dependencies

N/A

### Risks

N/A

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [ ] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [ ] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification

Not applicable to the changes in this PR

# Additional Checks
- [ ] In the case of complex code, I wrote comments to explain it.
- [ ] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [ ] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

File: inc/Engine/Admin/PerformanceMonitoring/Render.php [hunk 1]
```diff
@@ -119,14 +119,40 @@ public function render_global_score_widget( array $data ) {
...
+	 * @return array The data for the global score widget.
+	 */
+	private function get_global_score_widget_data() {
+		$data = [
+			'has_credit'  => $this->plan->has_credit(),
+			'can_add_url' => $this->pma_context->is_adding_page_allowed(),
+			'status_text' => $this->get_monitoring_status_text(),
+		];
+
+		$data['reach_max_url'] = ! $data['can_add_url'];
```
Comment (wordpressfan) [inline inc/Engine/Admin/PerformanceMonitoring/Render.php]: Move this line to the array, and u can return the array directly without assigning it to a variable..

File: views/settings/partials/performance-monitoring/global-score-widget-content.php [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+			$this->render_performance_score( $data );
+			?>
+		<?php else : ?>
+			<div class="wpr-score-no-urls"></div>
+		<?php endif; ?>
+	</div>
+	<p class="wpr-page-num-txt">
+	<?php
+	// translators: %1$s is the number of pages tracked/monitored.
+	printf( esc_html( $data['status_text'] . ': %s' ), intval( $data['pages_num'] ) );
```
Comment (wordpressfan) [inline views/settings/partials/performance-monitoring/global-score-widget-content.php]: I know that it's not coming from this PR and it was like this before but can u plz adjust this line to have `$data['status_text']` as a placeholder and pass it as argument?

**Review by wordpressfan — CHANGES_REQUESTED** [review]

**Review by wordpressfan — APPROVED** [review]

**Comment by Mai-Saad** [comment]
- [x] No duplicated id while GS loading , completed
- [x] No duplicated id while GS failed
- [x] No duplicated id while GS blurred
