### PR TITLE
Fix Fatal error "Path cannot be empty" when combining not readable or not found file

### LINKED ISSUE #3422: PHP 8 - Fatal error "Path cannot be empty" - file_get_contents('') at /inc/Engine/Optimization/AbstractOptimization.php
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅ 
- Used the search feature to ensure that the bug hasn’t been reported before ✅ 

**Describe the bug**
In PHP 8, trying to get the content of a path that doesn’t exist throws a fatal error. 
It is happening when we pass an empty path here for example:
https://github.com/wp-media/wp-rocket/blob/master/inc/Engine/Optimization/AbstractOptimization.php#L199

```PHP Fatal error: Uncaught ValueError: Path cannot be empty in /opt/httpd/htdocs/wp-admin/includes/class-wp-filesystem-direct.php:39\nStack trace:
#0 /opt/httpd/htdocs/wp-admin/includes/class-wp-filesystem-direct.php(39): file_get_contents('')
#1 /opt/httpd/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/AbstractOptimization.php(199): WP_Filesystem_Direct->get_contents(false)
#2 /opt/httpd/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Minify/CSS/Combine.php(296): WP_Rocket\\Engine\\Optimization\\AbstractOptimization->get_file_content(false)
#3 /opt/httpd/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Minify/CSS/Combine.php(217): WP_Rocket\\Engine\\Optimization\\Minify\\CSS\\Combine->get_content('/opt/httpd/htdo...')
#4 /opt/httpd/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Minify/CSS/Combine.php(73): WP_Rocket\\Engine\\Optimization\\Minify\\CSS\\Combine->combine()
#5 /opt/httpd/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Minify/CSS/Subscriber.php(53): WP_Rocket\\Engine\\Optimization\\Minify\\CSS\\Combine->optimize('<!DOCTYPE HTML>...')
#6 /opt/httpd/htdocs/wp-includes/class-wp-hook.php(287): WP_Rocket\\Engine\\Optimization\\Minify\\CSS\\Subscriber->process('<!DOCTYPE HTML>...')
#7 /opt/httpd/htdocs/wp-includes/plugin.php(212): WP_Hook->apply_filters('<!DOCTYPE HTML>...', Array)\n
#8 /opt/httpd/htdocs/wp-content/plugins/wp-rocket/inc/classes/Buffer/class-optimization.php(104): apply_filters('rocket_buffer', '<!DOCTYPE HTML>...')
#9 [internal function]: WP_Rocket\\Buffer\\Optimization->maybe_process_buffer('<!DOCTYPE HTML>...', 9)\n
#10 /opt/httpd/htdocs/wp-includes/functions.php(4755): ob_end_flush()
#11 /opt/httpd/htdocs/wp-includes/class-wp-hook.php(287): wp_ob_end_flush_all('')
#12 /opt/httpd/htdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#13 /opt/httpd/htdocs/wp-includes/plugin.php(484):!WP_Hook->do_action(Array)
#14 /opt/httpd/htdocs/wp-includes/load.php(1052): do_action('shutdown')
#15 [internal function]: shutdown_action_hook()
#16 {main}
thrown in /opt/httpd/htdocs/wp-admin/includes/class-wp-filesystem-direct.php on line 39
 ```

**To Reproduce**
1. On a server running **PHP 8** and WP Rocket 
2. Pass a path that doesn't exist [here](https://github.com/wp-media/wp-rocket/blob/master/inc/Engine/Optimization/AbstractOptimization.php#L198): 
3. It will fail on line 199 with this error: https://snippi.com/s/ql270c6

**Expected behavior**
Per Remy's comment [here](https://wp-media.slack.com/archives/C43T1AYMQ/p1608152406033500), 
> We can guard against it by adding an additional check, to prevent trying to get the content of a path that doesn’t exist 

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1365043281/222562?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
Fixes https://github.com/wp-media/wp-rocket/issues/3422

### CODE REVIEW

File: inc/Engine/Optimization/Minify/CSS/Combine.php [hunk 1]
```diff
@@ -293,6 +293,12 @@ private function get_content( $combined_file ) {
 		foreach ( $this->styles as $key => $style ) {
 			if ( 'internal' === $style['type'] ) {
 				$filepath     = $this->get_file_path( $style['url'] );
```
Comment (iCaspar) [inline inc/Engine/Optimization/Minify/CSS/Combine.php:295]: Remove extra spacing before `=` here to pass phpcs

**Review by iCaspar — CHANGES_REQUESTED** [review]

**Review by iCaspar — APPROVED** [review]

**Comment by engahmeds3ed** [comment]
@wp-media/qa ready for QA.

**Review by piotrbak — APPROVED** [review]
Worked as expected:
[testrail-report-94.pdf](https://github.com/wp-media/wp-rocket/files/5754807/testrail-report-94.pdf)
