### PR TITLE
Apply missing image dimensions for images with a relative path

### LINKED ISSUE #3438: Apply missing image dimensions for images with a relative path
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - yes
- Used the search feature to ensure that the bug hasn’t been reported before - yes

**Describe the bug**
Images added with a relative path don't have image dimensions applied.

**To Reproduce**
1. Activate _Add Missing Image Dimensions_ option in the Media tab
2. Add image with a markup like this: ``
3. The dimensions are not applied:
image
Full-screen image: https://jmp.sh/RNI1CNa

**Expected behavior**
Image dimensions have to be applied for images with a relative path.

**Additional context**
Debug log: https://jmp.sh/XfT839x
Specify Image Dimensions failed because the internal image is not found.

Slack discussion: https://wp-media.slack.com/archives/C43T1AYMQ/p1608732263037200

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
Closes https://github.com/wp-media/wp-rocket/issues/3438

### CODE REVIEW

File: inc/Engine/Media/ImageDimensions/ImageDimensions.php [hunk 1]
```diff
@@ -227,7 +226,15 @@ private function get_local_path( $url ) {
...
 
-		return str_replace( content_url(), rocket_get_constant( 'WP_CONTENT_DIR' ), $url );
+		if ( false === strpos( $url, content_url() ) ) {
+			$url = site_url( '/' ) . ltrim( $url, '/' );
+		}
+
+		return str_replace(
+			'/',
+			rocket_get_constant( 'DIRECTORY_SEPARATOR' ),
+			str_replace( site_url(), rocket_get_constant( 'ABSPATH' ), $url )
```
Comment (remyperona) [inline inc/Engine/Media/ImageDimensions/ImageDimensions.php]: I'm thinking that this might not be working on some WP setups, notably when WP is installed in a sub-directory like so:
- home URL is http://example.org
- site URL is http://example.org/wp

Can you test it?

Comment (engahmeds3ed) [reply inc/Engine/Media/ImageDimensions/ImageDimensions.php]: I adjusted the tests to accept changing `site_url` and `home_url` and tests passed.

You can check this fixture
https://github.com/wp-media/wp-rocket/blob/4035cff4b1ef03f07055022202a162f923e06ef8/tests/Fixtures/inc/Engine/Media/ImageDimensions/ImageDimensions/specifyImageDimensions.php#L213-L224

**Review by remyperona — APPROVED** [review]

**Comment by remyperona** [comment]
@wp-media/qa ready for QA

If you can validate the change on different setups:
- home URL = site URL
- home URL = site URL on a website in a subdirectory installation
- home URL ≠ site URL, with the index.php at the root and the other inside a subdirectory (See https://wordpress.org/support/article/giving-wordpress-its-own-directory/)

**Comment by piotrbak** [comment]
@engahmeds3ed Please find my comments here:
- Works on a regular WordPress site 👍 
- Works with custom `wp-content` 👍 
- Doesn't work with the subdirectory WordPress 👎 
- Doesn't work with the environment where `home_url =! site_url` 👎 

The last two seem to be related to the multisite issue:
https://github.com/wp-media/wp-rocket/issues/3453

**Review by remyperona — APPROVED** [review]

**Comment by piotrbak** [comment]
@engahmeds3ed Two things found during the QA:
- When the site is in the subdirectory `example.com/qa/` and we're loading the images from the parent site `example.com/path/to/image.jpg`, then it's not possible to specify image dimensions even when filters are set. Possible that it's related to the https://github.com/wp-media/wp-rocket/issues/3453
- When the query string is added to the image, the process fails completely `example.com/path/to/image.jpg?hey`

**Comment by engahmeds3ed** [comment]
@piotrbak adjusted the code now to solve those two issues but FYI, now we are dealing with image with query string as external image so you need to enable `allow_url_fopen` from php.ini and also use this filter to return true `rocket_specify_image_dimensions_for_distant` to make it works.

`I knot that you already know that, but for future reference.`

Ready for QA again.

**Comment by piotrbak** [comment]
@engahmeds3ed @Tabrisrp Last one, probably an edge case... Relative URL + query string.

We're failing to add the missing attributes there.

**Comment by engahmeds3ed** [comment]
Adjusted this edge case also, @piotrbak plz check now.

**Review by piotrbak — APPROVED** [review]
Working as expected:
[testrail-report-117.pdf](https://github.com/wp-media/wp-rocket/files/5914223/testrail-report-117.pdf)
