### PR TITLE
Closes #2566 Hide RocketCDN when white label is enabled

### LINKED ISSUE #2566: Hide RocketCDN information when WP_ROCKET_WHITE_LABEL_ACCOUNT is true
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version 👍 
- Used the search feature to ensure that the bug hasn’t been reported before 👍 

**Describe the issue**
Whitelabel option is not hiding RocketCDN information in the WP Rocket dashboard.

**To Reproduce**
1. Add `define ('WP_ROCKET_WHITE_LABEL_ACCOUNT', true);` to `wp-config.php` ([refer](https://docs.wp-rocket.me/article/7-enabling-white-label))
2. Visit WP Rocket > Dashboard tab. 
3. Account details will be hidden. But RocketCDN subscription details will be displayed. 

**Expected behavior**
Our users would use white label on customer websites and wouldn't want their customers to see RocketCDN related things. When `WP_ROCKET_WHITE_LABEL_ACCOUNT` is true, nothing related to RocketCDN should be displayed. 

When `WP_ROCKET_WHITE_LABEL_ACCOUNT` is `true`:
- Hide `RocketCDN` section in `Dashboard` tab.
- Remove the `Manage Subscription` link in `CDN` tab.
- Do not show the notices that prompts users to sign-up for RocetCDN. 

**Additional context**
Related discussion: https://wp-media.slack.com/archives/CR8RSB1T8/p1586526612068300

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by Tabrisrp**
Closes #2566

- [x] Update `AdminPageSubscriber` methods
- [x] Update `NoticesSubscriber` methods
- [x] Add new constants to `StubTrait`
- [x] Update unit tests
- [x] Update integration tests
- [x] QA

### CODE REVIEW

**Comment by vmanthos** [comment]
Starting QA.

File: inc/Engine/CDN/RocketCDN/AdminPageSubscriber.php [hunk 1]
```diff
@@ -110,6 +114,10 @@ public function display_rocketcdn_status() {
 	 * @return array
 	 */
 	public function rocketcdn_field( $fields ) {
+		if ( rocket_get_constant( 'WP_ROCKET_WHITE_LABEL_ACCOUNT' ) ) {
```
Comment (hellofromtonya) [inline inc/Engine/CDN/RocketCDN/AdminPageSubscriber.php:117]: @Tabrisrp Let's move this code into a private method to encapsulate the guard clause.

```php
if ( $this->is_while_label_account() ) {
```

and 

```php
private function is_while_label_account() {
	return (bool) rocket_get_constant( 'WP_ROCKET_WHITE_LABEL_ACCOUNT', false );
}
```

and then update all of the uses in this class.

Why?

- Readability
- Encapsulate the knowledge
- If ever we need to change it, we can do so in one method.

File: inc/Engine/CDN/RocketCDN/NoticesSubscriber.php [hunk 2]
```diff
@@ -53,6 +53,10 @@ public static function get_subscribed_events() {
 	 * @return void
 	 */
 	public function promote_rocketcdn_notice() {
+		if ( rocket_get_constant( 'WP_ROCKET_WHITE_LABEL_ACCOUNT' ) ) {
```
Comment (hellofromtonya) [inline inc/Engine/CDN/RocketCDN/NoticesSubscriber.php:56]: Same in this class too, i.e. `if ( $this->is_while_label_account() ) {`
