### PR TITLE
Fixes #2278 Compatibility with CDN URL containing a path

### LINKED ISSUE #2278: Subdirectory CDN incompatibility
For example, GoDaddy is using the following CDN URL markup:
_https://secureservercdn.net/110.150.138.55/lpq.31c.myftpupload.com_

Having CDN URL with subdirectories doesn't seem to work with WP Rocket now. Get_file_path function returns empty string, for example here:
https://github.com/wp-media/wp-rocket/blob/4b8b155c0a3c5543f70867a4b26725e1dbd8457e/inc/classes/optimization/JS/class-combine.php#L207

The combined file gets created and added to the source, while original scripts are not removed though.

**Steps to reproduce:** 
- Please add CDN URL like `example.com/cdn` 
- Enable JavaScript combination
- The combined JS file will be rewritten correctly with `example.com/cdn`
- However, all the JS files will still remain - https://jmp.sh/cS4Y6av

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### LINKED ISSUE #2466: Notice: Trying to access array offset on value of type null (PHP 7.4, WP Rocket 3.5.1)
I've just updated my Staging Site to PHP 7.4 on WPEngine.
I've updated WP Rocket to version 3.5.1

I'm getting the following Notice:
Notice: Trying to access array offset on value of type null in /nas/content/live/xxx/wp-content/plugins/wp-rocket/inc/classes/optimization/class-abstract-optimization.php on line 66

I see there was a similar notice happening in another class and it was solved and closed:
https://github.com/wp-media/wp-rocket/issues/2185

### PR DESCRIPTION
**Pull request by remyperona**
Closes #2278.

This issue has multiple factors going into play:
- This line is removing the `path` part of the CDN URL(s) added in the settings: https://github.com/wp-media/wp-rocket/blob/8cf329ca6f1e7ad9145c80499cfd4be98e702e3b/inc/classes/subscriber/CDN/CDNSubscriber.php#L145
- Fixing the above makes this conditional fail. It is checking the asset file `host` vs the known `hosts` values which include the CDN URL(s). So right now it won't correctly match: https://github.com/wp-media/wp-rocket/blob/8cf329ca6f1e7ad9145c80499cfd4be98e702e3b/inc/classes/optimization/class-abstract-optimization.php#L61
- The function `rocket_url_to_path()` needs to be updated too to keep things working: https://github.com/wp-media/wp-rocket/blob/8cf329ca6f1e7ad9145c80499cfd4be98e702e3b/inc/functions/formatting.php#L467

This means it impacts:
- Cache dynamic resources
- Remove Query Strings
- Minify/Combine CSS
- Minify/Combine JS

**Solution** ✅ 
Solving the issue means fixing the 3 points above, and also making sure there is no side-effects.

- Fixing first point: don't use the `host` only, but both `host` and `path`
- Fixing second point: instead of using the file `host` only, check if the there is a match between the hosts list and the full URL of the file
- Fixing third point: same approach as second point

### Progress
**Write tests to validate current state**
- [x] Unit/Integration Tests `WP_Rocket\Subscriber\CDN\CDNSubscriber::get_cdn_hosts`
- [x] Unit Test `WP_Rocket\Optimization\Cache_Dynamic_Resource::is_excluded_file`
- [x] Integration Test `WP_Rocket\Subscriber\Optimization\Cache_Dynamic_Resource_Subscriber::cache_dynamic_resource`
- [x] Unit Test `WP_Rocket\Optimization\Remove_Query_String::remove_query_strings_css`
- [x] Unit Test `WP_Rocket\Optimization\Remove_Query_String::remove_query_strings_js`
- [x] Integration Test `WP_Rocket\Subscriber\Optimization\Remove_Query_String_Subscriber::process`
- [x]  `Cristina`  Unit Test `WP_Rocket\Optimization\CSS\Minify::optimize`
- [x]  `Cristina`  Unit Test `WP_Rocket\Optimization\CSS\Combine::optimize`
- [x]  `Cristina`  Integration Test `WP_Rocket\Subscriber\Optimization\Minify_CSS_Subscriber::process`
- [x] `Cristina` Unit Test `WP_Rocket\Optimization\JS\Minify::optimize`
- [x] `Cristina` Unit Test `WP_Rocket\Optimization\JS\Combine::optimize`
- [x]  `Cristina` Integration Test `WP_Rocket\Subscriber\Optimization\Minify_JS_Subscriber::process`

**Update code to be compatible with CDN URL containing path**
- [x] Update `WP_Rocket\Subscriber\CDN\CDNSubscriber::get_cdn_hosts`
- [x] Update `WP_Rocket\Optimization::get_file_path` with code based on `rocket_url_path()`
- [x] Deprecate `rocket_url_path()`
- [x] Update `WP_Rocket\Optimization\Abstract_Optimization::is_external_file`
- [x] Add new method in `WP_Rocket\Subscriber\CDN\CDNSubscriber::maybe_replace_url`

**Add new tests for CDN URL containing path**
- [x] Unit/Integration Tests `WP_Rocket\Subscriber\CDN\CDNSubscriber::get_cdn_hosts`
- [x] Unit Test `WP_Rocket\Optimization\Cache_Dynamic_Resource::is_excluded_file`
- [x] Integration Test `WP_Rocket\Subscriber\Optimization\Cache_Dynamic_Resource_Subscriber::cache_dynamic_resource`
- [x] Unit Test `WP_Rocket\Optimization\Remove_Query_String::remove_query_strings_css`
- [x] Unit Test `WP_Rocket\Optimization\Remove_Query_String::remove_query_strings_js`
- [x] Integration Test `WP_Rocket\Subscriber\Optimization\Remove_Query_String_Subscriber::process`
- [x] `Cristina` Unit Test `WP_Rocket\Optimization\CSS\Minify::optimize`
- [x] `Cristina` Unit Test `WP_Rocket\Optimization\CSS\Combine::optimize`
- [x] `Cristina` Integration Test `WP_Rocket\Subscriber\Optimization\Minify_CSS_Subscriber::process`
- [x] `Cristina`  Unit Test `WP_Rocket\Optimization\JS\Minify::optimize`
- [x] `Cristina` Unit Test `WP_Rocket\Optimization\JS\Combine::optimize`
- [x] `Cristina`  Integration Test `WP_Rocket\Subscriber\Optimization\Minify_JS_Subscriber::process`
- [x] Unit/Integration Test `WP_Rocket\Subscriber\CDN\CDNSubscriber::maybe_replace_url`

### CODE REVIEW

**Comment by hellofromtonya** [comment]
Team -- We should consider refactoring these files to bundle them into `inc/Engine/Optimization`.

**Comment by Tabrisrp** [comment]
Yes I was thinking about it, but I considered doing that once this is done, in a new PR

File: inc/classes/optimization/CSS/class-abstract-css-optimization.php [hunk 1]
```diff
@@ -1,8 +1,8 @@
 <?php
```
Comment (hellofromtonya) [inline inc/classes/optimization/CSS/class-abstract-css-optimization.php:1]: As we are touching this file, let's move and rename per our new standards/architecture.

File: inc/classes/optimization/CSS/class-abstract-css-optimization.php [hunk 2]
```diff
@@ -119,7 +119,7 @@ protected function is_minify_excluded_file( $tag ) {
 			return true;
 		}
 
-		$file_path = rocket_extract_url_component( $tag[2], PHP_URL_PATH );
+		$file_path = wp_parse_url( $tag[2], PHP_URL_PATH );
```
Comment (hellofromtonya) [inline inc/classes/optimization/CSS/class-abstract-css-optimization.php:122]: 1. Type hint the `array $tag` in the function params list.
2. What if `$tag` is empty? There wouldn't be a `0` and `2` index, which would cause a notice/warning. We need to protect this method.

File: inc/classes/optimization/CSS/class-combine.php [hunk 3]
```diff
@@ -1,11 +1,9 @@
 <?php
```
Comment (hellofromtonya) [inline inc/classes/optimization/CSS/class-combine.php:1]: Let's move and rename this file for our new standards and architecture.

File: inc/classes/optimization/JS/class-abstract-js-optimization.php [hunk 4]
```diff
@@ -1,8 +1,8 @@
 <?php
```
Comment (hellofromtonya) [inline inc/classes/optimization/JS/class-abstract-js-optimization.php:1]: Let's move and rename this one too.

File: inc/classes/optimization/CSS/class-minify.php [hunk 5]
```diff
@@ -119,8 +119,11 @@ private function replace_url( $url ) {
 			return false;
 		}
 
+		// This filter is documented in /inc/classes/optimization/class-abstract-optimization.php.
```
Comment (hellofromtonya) [inline inc/classes/optimization/CSS/class-minify.php:122]: Let's move and rename this file for our new standards and architecture.

File: inc/classes/optimization/CSS/class-minify.php [hunk 6]
```diff
@@ -119,8 +119,11 @@ private function replace_url( $url ) {
...
+		$url = apply_filters( 'rocket_asset_url', $url, $this->get_zones() );
```
Comment (hellofromtonya) [inline inc/classes/optimization/CSS/class-minify.php:123]: Why are we adding this filter? Is it a feature request? _curious_

File: inc/classes/optimization/JS/class-abstract-js-optimization.php [hunk 7]
```diff
@@ -93,7 +93,7 @@ protected function is_minify_excluded_file( $tag ) {
 			return true;
 		}
 
-		$file_path = rocket_extract_url_component( $tag[2], PHP_URL_PATH );
```
Comment (hellofromtonya) [inline inc/classes/optimization/JS/class-abstract-js-optimization.php:96]: Same comments here about type hinting and guarding in case `$tag` doesn't have 3 elements.

File: inc/classes/optimization/class-abstract-optimization.php [hunk 8]
```diff
@@ -38,32 +38,58 @@ protected function find( $pattern, $html ) {
...
+		 * Filters the allowed hosts for optimization
+		 *
+		 * @since  3.4
+		 * @author Remy Perona
+		 *
+		 * @param array $hosts Allowed hosts.
+		 * @param array $zones Zones to check available hosts.
+		 */
+		$hosts      = apply_filters( 'rocket_cdn_hosts', [], $this->get_zones() );
+		$wp_content = get_rocket_parse_url( content_url() );
```
Comment (hellofromtonya) [inline inc/classes/optimization/class-abstract-optimization.php:57]: What if `get_rocket_parse_url()` doesn't return an array that's has the right keys/structure?

File: inc/classes/optimization/class-abstract-optimization.php [hunk 9]
```diff
@@ -38,32 +38,58 @@ protected function find( $pattern, $html ) {
 	 * @return bool True if external, false otherwise
 	 */
 	protected function is_external_file( $url ) {
```
Comment (hellofromtonya) [inline inc/classes/optimization/class-abstract-optimization.php:40]: Let's move and rename this class file too.

File: inc/classes/optimization/class-cache-dynamic-resource.php [hunk 10]
```diff
@@ -2,6 +2,7 @@
 namespace WP_Rocket\Optimization;
```
Comment (hellofromtonya) [inline inc/classes/optimization/class-cache-dynamic-resource.php:2]: Let's move and rename this class file too.

File: inc/classes/optimization/class-remove-query-string.php [hunk 11]
```diff
@@ -1,8 +1,9 @@
 <?php
```
Comment (hellofromtonya) [inline inc/classes/optimization/class-remove-query-string.php:1]: Let's move and rename this class file too.

File: inc/classes/subscriber/Optimization/class-abstract-minify-subscriber.php [hunk 12]
```diff
@@ -1,11 +1,11 @@
 <?php
 namespace WP_Rocket\Subscriber\Optimization;
```
Comment (hellofromtonya) [inline inc/classes/subscriber/Optimization/class-abstract-minify-subscriber.php:2]: Let's move and rename this class file too.

File: inc/classes/subscriber/Optimization/class-minify-css-subscriber.php [hunk 13]
```diff
@@ -1,9 +1,9 @@
 <?php
 namespace WP_Rocket\Subscriber\Optimization;
```
Comment (hellofromtonya) [inline inc/classes/subscriber/Optimization/class-minify-css-subscriber.php:2]: Let's move and rename this class file too.

File: inc/classes/subscriber/Optimization/class-minify-js-subscriber.php [hunk 14]
```diff
@@ -1,10 +1,10 @@
 <?php
```
Comment (hellofromtonya) [inline inc/classes/subscriber/Optimization/class-minify-js-subscriber.php:1]: Let's move and rename this class file too.

File: inc/functions/formatting.php [hunk 15]
```diff
@@ -433,6 +391,13 @@ function rocket_get_cache_busting_paths( $filename, $extension ) {
  * @return string Resolved file path
  */
 function rocket_realpath( $file ) {
+	$wrapper = null;
+
+	// Strip the protocol.
+	if ( wp_is_stream( $file ) ) {
```
Comment (hellofromtonya) [inline inc/functions/formatting.php:397]: Use `rocket_is_stream` instead. It's available in `develop` branch.

**Review by hellofromtonya — CHANGES_REQUESTED** [review]
Round 1.

File: inc/classes/optimization/CSS/class-minify.php (hunk 6 above)
Comment (Tabrisrp) [reply inc/classes/optimization/CSS/class-minify.php:123]: I'm using it for 2 things:
- Reduce coupling we had before with the CDN part of the plugin
- When CDN is enabled, I convert the CDN URL back to the origin URL, to make sure the file has the correct path when we save it in the `min` folder. Else we could get unexpected paths when the CND URL itself has a path.

File: inc/functions/formatting.php (hunk 15 above)
Comment (Tabrisrp) [reply inc/functions/formatting.php]: Done https://github.com/wp-media/wp-rocket/commit/4f2bfb5985ec5d3363c3e1707b57a40ae1603a4e

File: inc/classes/optimization/class-abstract-optimization.php (hunk 8 above)
Comment (Tabrisrp) [reply inc/classes/optimization/class-abstract-optimization.php]: Done in https://github.com/wp-media/wp-rocket/commit/164c6c444a5d38449782299c9a91a7541313db94

File: inc/classes/optimization/JS/class-abstract-js-optimization.php (hunk 7 above)
Comment (Tabrisrp) [reply inc/classes/optimization/JS/class-abstract-js-optimization.php:96]: Done in https://github.com/wp-media/wp-rocket/commit/4093a46af1c2cb5a62512f4e6f5f29965c363365

File: inc/classes/optimization/CSS/class-abstract-css-optimization.php (hunk 2 above)
Comment (Tabrisrp) [reply inc/classes/optimization/CSS/class-abstract-css-optimization.php]: Done in https://github.com/wp-media/wp-rocket/commit/dc6eb9dbc5ad6671d69ac3cbe71d796dc5da58f7

File: inc/classes/optimization/class-remove-query-string.php (hunk 11 above)
Comment (Tabrisrp) [reply inc/classes/optimization/class-remove-query-string.php:1]: Moving this one will create conflicts with the changes we are making in 3.6, since it's deprecated in one of the opened PR. Shouldn't we leave it alone since the file is going to be deprecated anyway?

Comment (hellofromtonya) [reply inc/classes/optimization/class-remove-query-string.php:1]: But it won't be deprecated for at least 6 weeks. Until then, we can relocate it to bundle with the rest of the optimization files. Then we can merge `develop` into the 3.6 branch and update the PR that deprecates it.

File: inc/classes/subscriber/Optimization/class-minify-js-subscriber.php (hunk 14 above)
Comment (hellofromtonya) [reply inc/classes/subscriber/Optimization/class-minify-js-subscriber.php:1]: @Tabrisrp This file still needs to be moved and renamed.

File: inc/classes/optimization/class-remove-query-string.php (hunk 11 above)
Comment (hellofromtonya) [reply inc/classes/optimization/class-remove-query-string.php:1]: A good guideline is this: future releases need to stay up-to-date with the current work.; but not the other way around.

File: inc/classes/optimization/CSS/class-minify.php (hunk 5 above)
Comment (Tabrisrp) [reply inc/classes/optimization/CSS/class-minify.php:123]: Not sure why it's not showing, but it has been done

File: inc/classes/subscriber/Optimization/class-minify-js-subscriber.php (hunk 14 above)
Comment (Tabrisrp) [reply inc/classes/subscriber/Optimization/class-minify-js-subscriber.php:1]: Same here, in the files tab, it's correctly showing as updated

File: inc/classes/optimization/class-remove-query-string.php (hunk 11 above)
Comment (Tabrisrp) [reply inc/classes/optimization/class-remove-query-string.php:1]: Done in https://github.com/wp-media/wp-rocket/pull/2392/commits/23447dce7701dde57ad7f04d1803ef9774a46c49

File: tests/Unit/inc/Engine/Optimization/RemoveQueryString/removeQueryStringsCSS.php [hunk 16]
```diff
@@ -0,0 +1,41 @@
...
+            ->zeroOrMoreTimes()
+            ->andReturnUsing( function( $url, $original_url ) use ( $cdn_url ) {
+                return str_replace( 'http://example.org', $cdn_url, $url );
+            } );
+
+        $this->assertSame(
+            $expected,
+            $this->rqs->remove_query_strings_css( $original )
+        );
+    }
```
Comment (Screenfeed) [inline tests/Unit/inc/Engine/Optimization/RemoveQueryString/removeQueryStringsCSS.php:40]:
```suggestion
		Filters\expectApplied( 'rocket_cdn_hosts' )
			->zeroOrMoreTimes()
			->with( [], [ 'all', 'css_and_js', 'css', 'js' ] )
			->andReturn( $cdn_host );

		Filters\expectApplied( 'rocket_asset_url' )
			->zeroOrMoreTimes()
			->andReturnUsing( function( $url ) use ( $cdn_url, $site_url ) {
				return str_replace( $cdn_url, $site_url, $url );
			} );

		Filters\expectApplied( 'rocket_css_url' )
			->zeroOrMoreTimes()
			->andReturnUsing( function( $url, $original_url ) use ( $cdn_url ) {
				return str_replace( 'http://example.org', $cdn_url, $url );
			} );

		$this->assertSame(
			$expected,
			$this->rqs->remove_query_strings_css( $original )
		);
	}
```

File: tests/Unit/inc/Engine/Optimization/RemoveQueryString/removeQueryStringsJS.php [hunk 17]
```diff
@@ -0,0 +1,41 @@
...
+            ->zeroOrMoreTimes()
+            ->andReturnUsing( function( $url, $original_url ) use ( $cdn_url ) {
+                return str_replace( 'http://example.org', $cdn_url, $url );
+            } );
+
+        $this->assertSame(
+            $expected,
+            $this->rqs->remove_query_strings_js( $original )
+        );
+    }
```
Comment (Screenfeed) [inline tests/Unit/inc/Engine/Optimization/RemoveQueryString/removeQueryStringsJS.php:40]:
```suggestion
		Filters\expectApplied( 'rocket_cdn_hosts' )
			->zeroOrMoreTimes()
			->with( [], [ 'all', 'css_and_js', 'css', 'js' ] )
			>andReturn( $cdn_host );

		Filters\expectApplied( 'rocket_asset_url' )
			->zeroOrMoreTimes()
			->andReturnUsing( function( $url ) use ( $cdn_url, $site_url ) {
				return str_replace( $cdn_url, $site_url, $url );
			} );

		Filters\expectApplied( 'rocket_js_url' )
			->zeroOrMoreTimes()
			>andReturnUsing( function( $url, $original_url ) use ( $cdn_url ) {
				return str_replace( 'http://example.org', $cdn_url, $url );
			} );

		$this->assertSame(
			$expected,
			$this->rqs->remove_query_strings_js( $original )
		);
	}
```

File: tests/Unit/inc/classes/subscriber/CDN/CDNSubscriber/getCdnHosts.php [hunk 18]
```diff
@@ -0,0 +1,76 @@
...
+				return 'http:' . $url;
+			}
+
+			return 'http://' . $url;
+		} );
+	}
+
+	public function addDataProvider() {
+        return $this->getTestData( __DIR__, 'get-cdn-hosts' );
+    }
```
Comment (Screenfeed) [inline tests/Unit/inc/classes/subscriber/CDN/CDNSubscriber/getCdnHosts.php:61]:
```suggestion
	public function addDataProvider() {
		return $this->getTestData( __DIR__, 'get-cdn-hosts' );
	}
```

File: tests/Unit/inc/classes/subscriber/CDN/CDNSubscriber/maybeReplaceUrl.php [hunk 19]
```diff
@@ -0,0 +1,106 @@
...
+
+		$this->assertSame(
+			'https://123456.rocketcdn.me/wordpress/wp-content/plugins/hello-dolly/style.css',
+			$this->subscriber->maybe_replace_url( 'https://123456.rocketcdn.me/wordpress/wp-content/plugins/hello-dolly/style.css', [ 'all' ] )
+		);
+	}
+
+	public function addDataProvider() {
+        return $this->getTestData( __DIR__, 'maybe-replace-url' );
+	}
```
Comment (Screenfeed) [inline tests/Unit/inc/classes/subscriber/CDN/CDNSubscriber/maybeReplaceUrl.php:86]:
```suggestion
	public function addDataProvider() {
		return $this->getTestData( __DIR__, 'maybe-replace-url' );
	}
```

**Review by Screenfeed — CHANGES_REQUESTED** [review]
Lots of alignment issues :/

**Review by Screenfeed — APPROVED** [review]

File: inc/functions/formatting.php [hunk 20]
```diff
@@ -102,48 +102,6 @@ function rocket_validate_js( $file ) {
...
- * Check if the passed value is an internal URL (default domain or CDN/Multilingual).
- *
- * @since  3.3.7
- * @author Remy Perona
- * @author Grégory Viguier
- *
- * @param  string $file string to test.
- * @return bool
- */
-function rocket_is_internal_file( $file ) {
```
Comment (crystinutzaa) [inline inc/functions/formatting.php:115]: You deprecated rocket_is_internal_file() function, however this function is used in:
`rocket_validate_js()` which is hooked in `rocket_sanitize_textarea_field`
```
'exclude_js'           => [ 'rocket_validate_js', 'rocket_clean_wildcards' ], // Pattern.
```

Comment (Tabrisrp) [reply inc/functions/formatting.php:115]: Thank you for catching that, when I searched for it VSCode didn't return anything strangely. I undeprecated the function and updated it 👍

**Review by crystinutzaa — APPROVED** [review]

**Review by Screenfeed — APPROVED** [review]

**Review by hellofromtonya — APPROVED** [review]

**Comment by hellofromtonya** [comment]
@Tabrisrp I made a few improvements. See the commit history above. Please review my changes.

**Comment by hellofromtonya** [comment]
@arunbasillal This PR is ready for QA. It's a blocker for other PRs. Please move it to the top of your QA list. Thanks.

**Comment by arunbasillal** [comment]
Starting QA

**Review by arunbasillal — COMMENTED** [review]
- Followed the steps to recreated here: https://github.com/wp-media/wp-rocket/issues/2278#issue-553796106
- Recreated the issue on `master` branch 👍 
- Issue still persisted on the `fix` branch. Please see - https://youtu.be/w5l8Qe6r-8M

@Tabrisrp Please note.

**Review by arunbasillal — APPROVED** [review]
Review based on AC: https://github.com/wp-media/wp-rocket/issues/2278#issuecomment-596754754

- CDN CNAME `domain.com/path`
- Combined JS file uses the CDN CNAME with the full CNAME. No other JS files should be present. 👍 
- Disable JS combination and have only JS minification. Check if the result is as expected. 👍 
- Repeat the same for Minify CSS, Combine CSS, Remove Query Strings 👍 
- Test with a CDN CNAME that has a trailing slash (domain.com/path/) and double trailing slash. The resulting URL shouldn't have double slashes. Removed in satitization 👍
- Tested with CDN CNAME as `https://domain.com/path` (with https). Works 👍 
- Tested with `https://domain.com` and `domain.com`. Works 👍 

Everything looks good 🚀
