### PR TITLE
Fixed the warning when the plugin param is not defined

### LINKED ISSUE #5645: Missing column on wp_wpr_rocket_cache during updates
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.3.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

During plugins updates, and if navigating away from the plugins page, the website might go down and show the following error: 

```
WordPress database error Unknown column 'is_locked' in 'field list' for query INSERT INTO `wp_wpr_rocket_cache` (`url`, `status`, `modified`, `last_accessed`, `is_locked`) VALUES ('some-url', 'completed', '2022-12-20T22:23:24Z', '2022-12-20 22:23:24', '0') made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ob_end_flush_all, ob_end_flush, WP_Rocket\\Engine\\Optimization\\Buffer\\Optimization->maybe_process_buffer, do_action('rocket_after_process_buffer'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\\Engine\\Preload\\Subscriber->update_cache_row, WP_Rocket\\Engine\\Preload\\Database\\Queries\\Cache->create_or_update, WP_Rocket\\Dependencies\\Database\\Query->add_item
```

We should safeguard this:

https://github.com/wp-media/wp-rocket/blob/537d497e7d2e12ae5a5b2b0f69a6d47edd073a39/inc/Engine/Preload/Database/Queries/Cache.php#L124-L179

from doing any database update while a plugin update is ongoing. 

**To Reproduce**
Couldn't be reproduced at will. But it happened on 3 different websites.

**Expected behavior**
No issues should happen related to the Preload module while updates are ongoing, even if the user navigates away from the plugins page. 

**Screenshots**

**Additional context**
Related: 

https://secure.helpscout.net/conversation/2070564947/382216/
https://secure.helpscout.net/conversation/2070582927/382224/
https://secure.helpscout.net/conversation/2103762680/390369/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Fix an issue with a warning when the plugin parameter is not defined in the update

Fixes #5645

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- [ ] Test locally

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Mai-Saad** [comment]
For test:
This PR is fixing this error when updating plugin/theme while WPR (dev) is active
```
[14-Feb-2023 14:47:00 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WP_Rocket\Engine\Plugin\UpdaterSubscriber::upgrade_pre_install_option(), 1 passed in /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php on line 310 and exactly 2 expected in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Plugin/UpdaterSubscriber.php:523
Stack trace:
#0 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(310): WP_Rocket\Engine\Plugin\UpdaterSubscriber->upgrade_pre_install_option()
#1 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /var/www/new.rocketlabsqa.ovh/htdocs/wp-admin/includes/class-wp-upgrader.php(491): apply_filters()
#3 /var/www/new.rocketlabsqa.ovh/htdocs/wp-admin/includes/class-wp-upgrader.php(799): WP_Upgrader->install_package()
#4 /var/www/new.rocketlabsqa.ovh/htdocs/wp-admin/includes/class-plugin-upgrader.php(345): WP_Upgrader->run()
#5 /var/www/new.rocketlabsqa.ovh/htdocs/wp-admin/includes/ajax-actions.php(4577): Plugin_Upgrader->bulk_upgrade()
#6 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(308): wp_ajax_update_plugin()
#7 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#8 /var/www/new.rocketlabsqa.ovh/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#9 /var/www/new.rocketlabsqa.ovh/htdocs/wp-admin/admin-ajax.php(188): do_action()
#10 {main}
  thrown in /var/www/new.rocketlabsqa.ovh/htdocs/wp-content/plugins/wp-rocket/inc/Engine/Plugin/UpdaterSubscriber.php on line 523
```
We need to check Plugin, theme, WP, WPR update there + Rollback on different env (Apache, Nginx, multisite)

**Comment by engahmeds3ed** [comment]
@CrochetFeve0251 
this used filter:
https://developer.wordpress.org/reference/hooks/upgrader_pre_install/

has one argument beside the filter return value so we need to change the way we add the callback here:
https://github.com/wp-media/wp-rocket/blob/1a0d2f987188781065fa4871f22e567a0f367a53/inc/Engine/Plugin/UpdaterSubscriber.php#L117-L118

to be like
```
'upgrader_pre_install'                  => [ 'upgrade_pre_install_option', 10, 2 ],
'upgrader_post_install'                 => [ 'upgrade_post_install_option', 10, 2 ],
```

And I believe this `$hook_extra` argument is an array that contains the key `plugin` that we may use.

You can check this code in Core as a reference:
https://github.com/WordPress/wordpress-develop/blob/5a49274a927b21ce18165bcba004c20421fcc088/src/wp-admin/includes/class-plugin-upgrader.php#L211

and here:

https://github.com/WordPress/wordpress-develop/blob/5a49274a927b21ce18165bcba004c20421fcc088/src/wp-admin/includes/class-plugin-upgrader.php#L523

What do u think?

File: inc/Engine/Plugin/UpdaterSubscriber.php [hunk 1]
```diff
@@ -520,9 +520,9 @@ public function rollback_add_return_link( $update_actions ) {
 	 *
 	 * @return mixed|WP_Error
 	 */
-	public function upgrade_pre_install_option( $return, $plugin ) {
+	public function upgrade_pre_install_option( $return, $plugin = null ) {
```
Comment (remyperona) [inline inc/Engine/Plugin/UpdaterSubscriber.php]: since the type of the second argument should be an array, the default value for the parameter should be an empty array instead of a null value

File: inc/Engine/Plugin/UpdaterSubscriber.php [hunk 2]
```diff
@@ -545,8 +545,8 @@ public function upgrade_pre_install_option( $return, $plugin ) {
 	 *
 	 * @return mixed|string|WP_Error
 	 */
-	public function upgrade_post_install_option( $return, $plugin ) {
-		if ( is_wp_error( $return ) ) {
+	public function upgrade_post_install_option( $return, $plugin = null ) {
```
Comment (remyperona) [inline inc/Engine/Plugin/UpdaterSubscriber.php]: same here

**Review by remyperona — APPROVED** [review]

**Comment by CrochetFeve0251** [comment]
> @CrochetFeve0251 this used filter: https://developer.wordpress.org/reference/hooks/upgrader_pre_install/
> 
> has one argument beside the filter return value so we need to change the way we add the callback here:
> 
> https://github.com/wp-media/wp-rocket/blob/1a0d2f987188781065fa4871f22e567a0f367a53/inc/Engine/Plugin/UpdaterSubscriber.php#L117-L118
> 
> to be like
> 
> ```
> 'upgrader_pre_install'                  => [ 'upgrade_pre_install_option', 10, 2 ],
> 'upgrader_post_install'                 => [ 'upgrade_post_install_option', 10, 2 ],
> ```
> 
> And I believe this `$hook_extra` argument is an array that contains the key `plugin` that we may use.
> 
> You can check this code in Core as a reference: https://github.com/WordPress/wordpress-develop/blob/5a49274a927b21ce18165bcba004c20421fcc088/src/wp-admin/includes/class-plugin-upgrader.php#L211
> 
> and here:
> 
> https://github.com/WordPress/wordpress-develop/blob/5a49274a927b21ce18165bcba004c20421fcc088/src/wp-admin/includes/class-plugin-upgrader.php#L523
> 
> What do u think?

You are right I fixed that.

**Comment by Mai-Saad** [comment]
Working fine now for WPR update, plugin , theme, WP update on different env.
However while exploring on branch, rarely found other error https://wp-media.slack.com/archives/GUT7FLHF1/p1676467216060249.
I think we can merge this one and gather feedback. @piotrbak what do you think?

**Comment by piotrbak** [comment]
@Mai-Saad Agreed

**Review by Mai-Saad — APPROVED** [review]

**Comment by DragMeToProgrammingParadise** [comment]
WordPress database error Unknown column 'is_locked' in 'field list' for query INSERT INTO `wp_wpr_rocket_cache` (`url`, `status`, `modified`, `last_accessed`, `is_locked`) VALUES ('https://www.mymakbuddy.in/product/meatzza-snackers-chicken-nuggets-500g', 'completed', '2023-04-08T17:58:40Z', '2023-04-08 17:58:40', '0') made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ob_end_flush_all, ob_end_flush, WP_Rocket\Engine\Optimization\Buffer\Optimization->maybe_process_buffer, do_action('rocket_after_process_buffer'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\Engine\Preload\Subscriber->update_cache_row, WP_Rocket\Engine\Preload\Database\Queries\Cache->create_or_update, WP_Rocket\Dependencies\Database\Query->add_item
