### PR TITLE
Fix #7706: PMA: The SAAS failing gives a 0 score

### LINKED ISSUE #7706: PMA: The SAAS failing gives a 0 score
**Describe the bug**
When the saas is failing due to an internal error from GT Metrix, the saas is returning an error 500 but the plugin is displaying a 0 score.

**Expected behavior**
We'd need to display failed state when receiving the following message from the SaaS:
```
{
    "status": "failed",
    "error": {
        "code": 500,
        "type": "ProcessingError",
        "message": "The test failed for an unknown reason.",
        "details": {}
    },
    "data": {}
}
```

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
https://group-onecom.slack.com/archives/C091CSKLB1Q/p1758700549369739

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #7706 
One line change ensures that when SaaS returns "status": "failed", the system properly handles it as a failure instead of treating it as a successful test with no score.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

### What was tested

Refer to issue

### How to test

Refer to issue

### Documentation

This pull request updates the logic for returning HTTP status codes based on the job status in the `get_queue_job_status` method. Now, if the job status is `'failed'`, the method will return a `500` status code instead of always returning `200` for non-pending statuses.

Error handling improvement:

* Updated the status code logic in `get_queue_job_status` (`APIClient.php`) to return `500` when the job status is `'failed'`, ensuring failed jobs are properly indicated to the caller.
### New dependencies

N/a
### Risks

N/a
# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

### CODE REVIEW

File: inc/Engine/Admin/PerformanceMonitoring/APIHandler/APIClient.php [hunk 1]
```diff
@@ -152,7 +152,7 @@ public function get_queue_job_status( string $test_id, $queue_name, $is_home = f
 		);
 
 		return [
-			'code'   => 'pending' === $response_data['status'] ? 425 : 200,
+			'code'   => 'pending' === $response_data['status'] ? 425 : ( 'failed' === $response_data['status'] ? 500 : 200 ),
```
[the remark this answers is not in the document]
Comment (CrochetFeve0251) [reply inc/Engine/Admin/PerformanceMonitoring/APIHandler/APIClient.php]: @Miraeld it is true it is a bit hard to read.

Bailing out would make it more readable

**Review by CrochetFeve0251 — CHANGES_REQUESTED** [review]

File: inc/Engine/Admin/PerformanceMonitoring/APIHandler/APIClient.php [hunk 2]
```diff
@@ -151,8 +151,15 @@ public function get_queue_job_status( string $test_id, $queue_name, $is_home = f
 			]
 		);
 
+		$code = 200;
+		if ( 'pending' === $response_data['status'] ) {
+			$code = 425;
+		} elseif ( 'failed' === $response_data['status'] ) {
+			$code = 500;
+		}
+
```
Comment (jeawhanlee) [inline inc/Engine/Admin/PerformanceMonitoring/APIHandler/APIClient.php]: What do you think about using switch here instead?

File: inc/Engine/Admin/PerformanceMonitoring/Jobs/Manager.php [hunk 3]
```diff
@@ -159,6 +159,35 @@ public function process( array $job_details, $row_details, string $optimization_
 			return;
 		}
 
+		// Validate job data before marking as completed.
+		$validation_error = $this->validate_job_data( $job_details, $row_details );
```
Comment (jeawhanlee) [inline inc/Engine/Admin/PerformanceMonitoring/Jobs/Manager.php]: I'm not sure but why do we need these type of validations here, we already do expected validation in the `validate_and_fail` method. Am I missing something?

File: inc/Engine/Admin/PerformanceMonitoring/Jobs/Manager.php [hunk 4]
```diff
@@ -201,6 +230,46 @@ public function get_optimization_type_from_row( $row ): string {
...
 	}
 
+	/**
+	 * Validate job data to ensure it has required fields with valid values.
+	 *
+	 * @param array  $job_details Details related to the job.
+	 * @param object $row_details Details related to the row.
+	 * @return string Empty string if valid, error message if invalid.
+	 */
+	private function validate_job_data( array $job_details, $row_details ): string {
```
Comment (jeawhanlee) [inline inc/Engine/Admin/PerformanceMonitoring/Jobs/Manager.php]: Same thing with this as well. If `status` is `failed`, we don't need further checks.

**Review by jeawhanlee — CHANGES_REQUESTED** [review]

File: inc/Engine/Admin/PerformanceMonitoring/Jobs/Manager.php (hunk 3 above)
Comment (Miraeld) [reply inc/Engine/Admin/PerformanceMonitoring/Jobs/Manager.php]: Hello, 

`validate_and_fail()` => Early in the process when the API response indicates a job has failed (`status === 'failed'`), it only checks if the job status is 'failed' and handles the failure appropriately

`validate_job_data()` => It's called later in the `process()` method **before** marking a job as completed. 
It validates:
- Job ID exists in database row
- Proper data structure exists (data.data)
- Performance score is valid (not zero/missing)
- Report URL exists and is properly formatted

The `validate_and_fail()` method handles explicitly failed jobs from the API, while `validate_job_data()` catches implicitly failed jobs ~ those that the API claims are successful but contain invalid/incomplete data (cf. the slack thread mentioned in the issue).

File: inc/Engine/Admin/PerformanceMonitoring/Jobs/Manager.php (hunk 4 above)
Comment (Miraeld) [reply inc/Engine/Admin/PerformanceMonitoring/Jobs/Manager.php]: Hello, 

`validate_and_fail()` => Early in the process when the API response indicates a job has failed (`status === 'failed'`), it only checks if the job status is 'failed' and handles the failure appropriately

`validate_job_data()` => It's called later in the `process()` method **before** marking a job as completed. 
It validates:
- Job ID exists in database row
- Proper data structure exists (data.data)
- Performance score is valid (not zero/missing)
- Report URL exists and is properly formatted

The `validate_and_fail()` method handles explicitly failed jobs from the API, while `validate_job_data()` catches implicitly failed jobs ~ those that the API claims are successful but contain invalid/incomplete data (cf. the slack thread mentioned in the issue).

**Comment by Miraeld** [comment]
Last changes are okay with me
