### PR TITLE
Fixes #2849 Ignore inline scripts content when applying the CDN rewrite

### LINKED ISSUE #2849: CDN RegEx picks up relative URLs when query strings have a specially-formatted value
When the source code includes:
1. relative URLs, e.g. `action='/fr/?_ga=2.213437008.512656707.1593765841-1928543133.1539673047'>`
2. containing a query string with a value formatted like this: `string_1.string2`

the [RegEx](https://github.com/wp-media/wp-rocket/blob/0455940481777146a4677dbf59ed928223351639/inc/Engine/CDN/CDN.php#L63) matches that.

Here is an example from a customer's website: https://regex101.com/r/VgMfih/1

When that's being used alongside WPML or Polylang, it can result in rewriting of the URL and, if it's used in, e.g. a form, its functionality can break.

**To Reproduce**

1. Use WPML or Polylang and set the language as a subfolder, e.g. `https://example.com/fr/`
2. Add the following code on the website: `action='/fr/?_ga=2.213437008.512656707.1593765841-1928543133.1539673047'>`
3. Enable the CDN.
4. Check the source code. The previous URL will be rewritten to:
`https://cdn.example.com/fr/?_ga=2.213437008.512656707.1593765841-1928543133.1539673047`

**Expected behavior**

That kind or URL shouldn't be rewritten.

**Additional context**

This is certainly an edge case. Excluding URLs like `/fr/(.*)` from CDN delivery, resolved the issue.

**Related ticket:** https://secure.helpscout.net/conversation/1212168255/177075/

@crystinutzaa said:
* The RegEx picks this up because it starts with a `/` and is inside quotes.
* The RegEx cannot be modified to exclude this scenario.
* A possible solution would be to exclude all forms.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
## Description

With this PR, by default we now remove inline scripts from the content to parse, to avoid unexpected rewritting of cases reported by the support.

This behaviour can be reverted by using the new filter `rocket_cdn_exclude_inline_scripts`.

We also introduce another filter `rocket_cdn_relative_paths`, which can prevent complete rewrite of relative paths.

Fixes #2849 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Added snippets to the automated tests to check for reported use case and verify they are correctly passing now

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: inc/Engine/CDN/CDN.php [hunk 1]
```diff
@@ -41,14 +43,44 @@ public function __construct( Options_Data $options ) {
...
+		 * @since 3.10.5
+		 *
+		 * @param bool $enable True to exclude, false otherwise.
+		 */
+		if ( apply_filters( 'rocket_cdn_exclude_inline_scripts', true ) ) {
+			$buffer = $this->remove_inline_scripts( $html );
+		}
+
+		/**
+		 * Filters the CDN rewritting of relative paths
```
Comment (iCaspar) [inline inc/Engine/CDN/CDN.php]:
```suggestion
		 * Filters the CDN rewriting of relative paths
```

**Review by iCaspar — APPROVED** [review]
Trivial typo in filter comment.

**Review by Mai-Saad — COMMENTED** [review]
@Tabrisrp Almost all tests passed but have the following notes:
1- While the filter rocket_cdn_relative_pathsset to false, we still rewrite relative URL inside srcset => can we fix this?
2- We still didn't fix https://github.com/wp-media/wp-rocket/issues/3718 nor https://github.com/wp-media/wp-rocket/issues/2849 by default, but we need to set rocket_cdn_relative_paths to false to avoid rewriting relative URLs inside HTML or inside script containing HTML
3- We still didn't fix https://github.com/wp-media/wp-rocket/issues/3138 by default, set rocket_cdn_relative_paths to false will fix the problem for relative path but not for absolute path in code content

**Comment by remyperona** [comment]
The filter can't be applied for srcset because the RegEx is in a different format, but relative paths are ok in srcset, it's not going to break things there

**Review by Mai-Saad — APPROVED** [review]
Working as expected then.
[testrail-report-323.pdf](https://github.com/wp-media/wp-rocket/files/7658690/testrail-report-323.pdf)
