### PR TITLE
Closes #6204: Refine RUCSS error reporting

### LINKED ISSUE #6204: Refine RUCSS error reporting with meaningful messages and timestamps
**Context**
We use "bad json" and code "400" as defaults for returns from the SaaS RUCSS feature. This prevents us and the support team to efficiently identify what went wrong, or which step failed. Also, we lack timing information to understand the lifecycle of the jobs from the plugin side.

**Expected behavior**
- Add a `submitted_at` field in the RUCSS table. This field is set to null by default, and filled with the current timestamp when a job is sent (or re-sent) to the SaaS (`used_css_query->reset_job`, `used_css_query->create_new_job`).
- Store in the row of the job, in the "message" column: the response & message from Saas & timestamp when getting job status that is not a 200. And concatenate those. For instance, if the first try return a 400 bad json at 2:15PM, store: `YY-MM-DD-14:12:30 400: Bad Json` Then, 10 minutes later, another 400 bad json, store: `YY-MM-DD-14:12:30 400: Bad Json;YY-MM-DD-14:22:45 400: Bad Json`. If the final try is also a failure, continue to concatenate.
Be careful with max size of the string: truncate if needed?
- Replace "Bad Json" in get_queue_job_status by: "No message. Defaulted in get_queue_job_status"
- Replace "Bad Json" in add_to_queue by: "No message. Defaulted in add_to_queue"

### PR DESCRIPTION
**Pull request by Miraeld**
## Description

The goal here is to give more info about the error message from the RUCSS process, and also, add a new column in the DB called `submitted_at`. Also, we do update the `error_message` column in order to get more details when the request fails.

Fixes #6204

## Type of change

- Enhancement (non-breaking change which improves an existing functionality).

## Is the solution different from the one proposed during the grooming?

No

# Checklists

## Generic development checklist

- [x] My code follows the style guidelines of this project, with adapted comments and without new warnings.
- [x] I have added unit and integration tests that prove my fix is effective or that my feature works.
- [x] The CI passes locally with my changes (including unit tests, integration tests, linter).
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] If applicable, I have made corresponding changes to the documentation. *Provide a link to the documentation.*

## Test summary

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I validated all Acceptance Criteria of the related issues. (If applicable, provide proof).
- [ ] I validated all test plan the QA Review asked me to.

### CODE REVIEW

File: tests/Integration/inc/Engine/Optimization/RUCSS/Cron/Subscriber/checkJobStatus.php [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+
+		if($url === $this->config['create']['url'] && $args['method'] === $this->config['create']['method'] ) {
+			return $this->config['create']['response'];
+		}
+
+		return $response;
+	}
+	public function rucss_hash() {
+		return $this->config['hash'];
+	}
```
Comment (CrochetFeve0251) [inline tests/Integration/inc/Engine/Optimization/RUCSS/Cron/Subscriber/checkJobStatus.php]: @Miraeld there is an issue with indentation here

**Review by CrochetFeve0251 — CHANGES_REQUESTED** [review]

File: tests/Integration/inc/Engine/Optimization/RUCSS/Cron/Subscriber/checkJobStatus.php (hunk 1 above)
Comment (Miraeld) [reply tests/Integration/inc/Engine/Optimization/RUCSS/Cron/Subscriber/checkJobStatus.php]: It's been fixed :)

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
Working as expected.
- Submitted at added to the table
- detailed error + timestamp in message (some char then truncate)
- bad json msg is replaced
- submitted_at = modified due to https://github.com/wp-media/wp-rocket/issues/6229
