### PR TITLE
Fix #3209 avada lazyload is detected as always active

### LINKED ISSUE #3209: Avada Lazyload is detected as always active
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Avada has added WordPress Lazyload option: https://jmp.sh/3SpVHLf

In our [compatibility file](https://github.com/wp-media/wp-rocket/blob/6c811c18c1739349a51753b07816b7260b1e2c07/inc/3rd-party/themes/avada.php#L22), we are checking Avada’s lazyload setting to be **empty**, and in that case, our Lazyload is available.

But now, the value is never empty, it’d be one of:
- none
- Wordpress
- avada

**To Reproduce**
1. Go to MEGA Avada
2. Deactivate Lazyload in Avada's settings, set it to "None": https://jmp.sh/3SpVHLf
3. Visit WP Rocket settings page
4. WPR Lazyload option is disabled: https://jmp.sh/7tNbWYk

**Expected behavior**
We should detect Avada's Lazyload **none** setting is deactivated, and enable WPR Lazyload option.

**Screenshots**
Avada's new option: https://jmp.sh/3SpVHLf

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by alfonso100**
Proposing a fix for [#3209](https://github.com/wp-media/wp-rocket/issues/3209)
(thank you @engahmeds3ed for the help!)

starting from Avada 7.2 version the `lazy_load` value is never empty, it’d be one of:
- none
- wordpress
- avada

Added verifications for the "none" value to deactivate and disable our LazyLoad option, while keeping the "empty" value verification for backward compatibility

### CODE REVIEW

**Comment by Tabrisrp** [comment]
I'm not sure this is the best approach. When selecting `none` in Avada, it means "neither the WordPress lazyload, nor the Avada one", but it doesn't extend to WP Rocket itself.

How about deactivating WP Rocket lazyload only when the `Avada` value is selected?

This is the one value that _can_ conflict with our own lazyload, the other won't cause any issue.

File: inc/3rd-party/themes/avada.php [hunk 1]
```diff
@@ -38,11 +38,11 @@ function rocket_avada_maybe_disable_lazyload() {
...
 	$current_theme = wp_get_theme();
 
-	if ( 'Avada' === $current_theme->get( 'Name' ) && ! empty( $avada_options['lazy_load'] ) ) {
-		return true;
+	if  ( ( 'Avada' === $current_theme->get( 'Name' ) ) && ( empty( $avada_options['lazy_load'] ) || 'avada' !== $avada_options['lazy_load']  ) ) {
+		return false;
 	}
 
-	return false;
+	return true;
```
Comment (Tabrisrp) [inline inc/3rd-party/themes/avada.php:45]:
```
if  ( ( 'Avada' !== $current_theme->get( 'Name' ) ) {
    return false;
}

if ( empty( $avada_options['lazy_load'] ) ) {
        return false;
}

if (  ! empty( $avada_options['lazy_load'] && 'avada' !== $avada_options['lazy_load']  ) ) {
	return false;
}

return true;
```

File: inc/3rd-party/themes/avada.php [hunk 2]
```diff
@@ -54,4 +54,4 @@ function rocket_avada_maybe_disable_lazyload() {
 function rocket_avada_clear_cache_fusion_patcher() {
 	rocket_clean_domain();
 }
-add_action( 'fusion_cache_reset_after', 'rocket_avada_clear_cache_fusion_patcher' );
+add_action( 'fusion_cache_reset_after', 'rocket_avada_clear_cache_fusion_patcher' );
```
Comment (Tabrisrp) [inline inc/3rd-party/themes/avada.php:57]:
```suggestion
add_action( 'fusion_cache_reset_after', 'rocket_avada_clear_cache_fusion_patcher' );

```

**Review by Tabrisrp — CHANGES_REQUESTED** [review]

**Review by Tabrisrp — APPROVED** [review]

**Comment by alfonso100** [comment]
Tested this on MEGA/Avada, confirmed to be working as expected with Avada 7.2
