### PR TITLE
Fix completed and failed mixpanel requests

### LINKED ISSUE #7678: 3.20 - User events tracking
More details [here](https://group-one.atlassian.net/wiki/x/EwDi6wc).

### PR DESCRIPTION
**Pull request by wordpressfan**
# Description

Fixes #7678 

Here we are fixing a few issues related to sending mixpanel requests for rocket insights feature.

## Type of change

- [ ] New feature (non-breaking change which adds functionality).
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).
- [ ] Sub-task of #(issue number)
- [ ] Chore
- [ ] Release

### What was tested

- Visiting the settings page sends the request `Page Viewed`
- Add a new url to rocket insights feature sends the request `Rocket Insights Page Added`
- Finalize processing the url in rocket insights feature sends the request `Rocket Insights Performance Test` and there we have status, score, is_retest, duration, and plan_type that we can filter with in mixpanel.
- When clicking `See report` button, it sends the request `rocket insights see report`

### How to test

Mentioned above.

### Documentation

Before firing completed and failed hooks, we get the row details from the database to have it with real final data.

### New dependencies

N/A

### Risks

N/A

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification

*If some mandatory items are not relevant, explain why in this section.*

# Additional Checks
- [ ] In the case of complex code, I wrote comments to explain it.
- [ ] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [ ] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

**Review by jeawhanlee — APPROVED** [review]

File: inc/Engine/Tracking/Subscriber.php [hunk 1]
```diff
@@ -122,7 +122,7 @@ public function track_optin_change( $status ): void {
 	 * @since 3.20
 	 *
 	 * @param string $url        The URL that was added for monitoring.
-	 * @param Plan   $plan       Plan instance.
+	 * @param string $plan       Plan name.
```
Comment (remyperona) [inline inc/Engine/Tracking/Subscriber.php:125]: It's not the plan name, it's actually the plan object instance  that is passed

File: inc/Engine/Tracking/Subscriber.php [hunk 2]
```diff
@@ -138,7 +138,7 @@ public function track_rocket_insights_url_added( $url, $plan, $urls_count ): voi
 	 *
 	 * @param object $row_details Details related to the database row.
 	 * @param array  $job_details Details related to the job.
-	 * @param Plan   $plan Plan instance.
+	 * @param string $plan Plan name.
```
Comment (remyperona) [inline inc/Engine/Tracking/Subscriber.php:141]: Same here

**Review by remyperona — CHANGES_REQUESTED** [review]

File: inc/Engine/Tracking/Subscriber.php (hunk 1 above)
Comment (wordpressfan) [reply inc/Engine/Tracking/Subscriber.php:125]: Here we changed the approach a bit to only send the plan name because there was a mis-consistency about using this plan which led to fatal error which was fixed here:
https://github.com/wp-media/wp-rocket/commit/dcb6ec6a402025dac6fb68d6370403426be71d8c

Slack convo: https://group-onecom.slack.com/archives/C08EFCYRQ2X/p1759165601712989?thread_ts=1759159199.739659&cid=C08EFCYRQ2X
