### PR TITLE
FIX: Add upgrade callback to reset credit on version update

### LINKED ISSUE #7782: 3.20 - Credit limit reached notice is displayed when updating to 3.20
**Describe the bug**
When updating WP Rocket to 3.20 the credit limit reached notice is displayed when it shouldn't.

After refreshing, it usually to disappear.

**To Reproduce**
1. Have 3.19.4 installed (3.20 options like the ones related to credits should not be in the database)
2. Update to 3.20
3. Go to Rocket Insights
4. See notice

**Expected behavior**
Credit limit reached notice shouldn't be displayed when fresh updating from previous to 3.20

**Screenshots**
How it is:
Image

How should be:
Image

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #NaN
Adds a callback on upgrade to force credit reset when previous version is < 3.20
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

### What was tested

Upgrading WP Rocket from < 3.20
### How to test

Upgrade WP Rocket from < 3.20
### Documentation

This pull request adds a new feature to the performance monitoring subscriber to automatically reset credit when the WP Rocket plugin is upgraded to version 3.20.0 or higher. The main changes include registering a new event listener and implementing a callback method to handle the credit reset logic.

**Performance Monitoring Upgrade Handling:**

* Registered the `wp_rocket_upgrade` event to trigger the new `on_update_reset_credit` callback in the `get_subscribed_events` method of `Subscriber.php`.
* Added the `on_update_reset_credit` method to reset credit when upgrading from a version lower than 3.20.0, using `version_compare` and the `plan->reset_credit()` call.

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification

No tests

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

File: inc/Engine/Admin/PerformanceMonitoring/Subscriber.php [hunk 1]
```diff
@@ -509,4 +510,17 @@ public function retest_all_pages() {
...
+	/**
+	 * Callback for the wp_rocket_upgrade action to reset credit on version update.
+	 *
+	 * @param string $new_version New plugin version.
+	 * @param string $old_version Previous plugin version.
+	 * @return void
+	 */
+	public function on_update_reset_credit( $new_version, $old_version ) {
+		if ( version_compare( $old_version, '3.20.0', '<' ) ) {
+			$this->plan->reset_credit();
```
Comment (wordpressfan) [inline inc/Engine/Admin/PerformanceMonitoring/Subscriber.php]:
```suggestion
			$this->reset_credit_monthly();
```

**Review by wordpressfan — CHANGES_REQUESTED** [review]
