### PR TITLE
Closes #5010 Remove WPR metabox from elementor template

### LINKED ISSUE #5010: Remove WP Rocket's options from Elementor templates
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version (3.11.1)
- Used the search feature to ensure that the bug hasn’t been reported before ✔️

**Describe the bug**
Elementor has an option to create/use templates, but we are not creating any cache file/folder for them since this content is not publicly visible and thus, displaying the WP Rocket options on the _Edit_ screen and the _Clear this cache_ button doesn't apply.

**To Reproduce**
-

**Expected behavior**
The _Clear this cache_ button and the WP Rocket options from the _Edit_ screen of Elementor templates should **not** be displayed.

**Screenshots**
Clear this cache button: https://share.getcloudapp.com/YEur9X9D
WP Rocket options: https://share.getcloudapp.com/rRu1ekZ5

**Additional context**
Having these options available creates confusion to our customers.
Related ticket: https://secure.helpscout.net/conversation/1870181424/340939

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

Removes WPR options from Elementor template.

Fixes #5010 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Enhancement (non-breaking change which improves an existing functionality)

## How Has This Been Tested?

Locally with Elementor

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by remyperona — CHANGES_REQUESTED** [review]
I propose a different approach to test: in `rocket_cache_options_meta_boxes()`, add to the arguments passed to `get_post_types()` the following `publicly_queryable => true`

**Comment by jeawhanlee** [comment]
@Tabrisrp I added this: `publicly_queryable => true` to the argument but I don't see any changes, perhaps, there's something i'm doing wrong.

File: inc/ThirdParty/Plugins/PageBuilder/Elementor.php [hunk 1]
```diff
@@ -166,4 +168,33 @@ public function exclude_js( $excluded_files ): array {
...
+	 *
+	 * @param array $cpts Custom post type.
+	 * @return array
+	 */
+	public function remove_rocket_metabox_option( array $cpts ): array {
+		if ( isset( $cpts['elementor_library'] ) ) {
+			unset( $cpts['elementor_library'] );
+
+			return $cpts;
+		}
```
Comment (remyperona) [inline inc/ThirdParty/Plugins/PageBuilder/Elementor.php]:
```suggestion
		if ( isset( $cpts['elementor_library'] ) ) {
			unset( $cpts['elementor_library'] );
                }

		return $cpts;
```

We want to always return something

File: inc/ThirdParty/Plugins/PageBuilder/Elementor.php [hunk 2]
```diff
@@ -166,4 +168,33 @@ public function exclude_js( $excluded_files ): array {
...
+	/**
+	 * Remove rocket option from row actions.
+	 *
+	 * @param boolean $default Filter default value.
+	 * @param mixed   $post Post object.
+	 * @return boolean
+	 */
+	public function remove_rocket_row_action( bool $default, $post ): bool {
+		if ( 'elementor_library' === $post->post_type ) {
+			$default = true;
```
Comment (remyperona) [inline inc/ThirdParty/Plugins/PageBuilder/Elementor.php]:
```suggestion
			return true;
```

File: inc/admin/admin.php [hunk 3]
```diff
@@ -70,7 +70,9 @@ function rocket_post_row_actions( $actions, $post ) {
 	$url                     = wp_nonce_url( admin_url( 'admin-post.php?action=purge_cache&type=post-' . $post->ID ), 'purge_cache_post-' . $post->ID );
 	$actions['rocket_purge'] = sprintf( '<a href="%s">%s</a>', $url, __( 'Clear this cache', 'rocket' ) );
 
-	return $actions;
+	if ( ! apply_filters( 'rocket_skip_post_row_actions', false, $post ) ) {
+		return $actions;
+	}
```
Comment (remyperona) [inline inc/admin/admin.php]: This should be located earlier in the method, after the first conditional, to avoid unnecessary processing if we are skipping.

We should also preserve the final return, as we always want this function to return the `$actions` variable.

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@jeawhanlee @piotrbak I think we need to remove `Purge this URL` or `clear this post` from the admin bar as well for Elementor templates. what do you think?
Screenshot from 2022-05-31 15-59-36
Screenshot from 2022-05-31 16-00-17

**Comment by jeawhanlee** [comment]
> @jeawhanlee @piotrbak I think we need to remove `Purge this URL` or `clear this post` from the admin bar as well for Elementor templates. what do you think? 

@Mai-Saad True!

**Comment by piotrbak** [comment]
Yes

File: inc/ThirdParty/Plugins/PageBuilder/Elementor.php [hunk 4]
```diff
@@ -166,4 +169,48 @@ public function exclude_js( $excluded_files ): array {
...
+			return true;
+		}
+
+		return $default;
+	}
+
+	/**
+	 * Remove cache or purge option from elementor template post.
+	 *
+	 * @param boolean $should_add_option Should add rocket option to admin bar.
```
Comment (remyperona) [inline inc/ThirdParty/Plugins/PageBuilder/Elementor.php]:
```suggestion
	 * @param boolean $should_skip Should skip rocket option to admin bar.
```

File: inc/ThirdParty/Plugins/PageBuilder/Elementor.php [hunk 5]
```diff
@@ -166,4 +169,48 @@ public function exclude_js( $excluded_files ): array {
...
+	 * @param mixed   $post Post object.
+	 * @return boolean
+	 */
+	public function skip_admin_bar_cache_purge_option( bool $should_add_option, $post ): bool {
```
Comment (remyperona) [inline inc/ThirdParty/Plugins/PageBuilder/Elementor.php]:
```suggestion
	public function skip_admin_bar_cache_purge_option( bool $should_skip, $post ): bool {
```

File: inc/ThirdParty/Plugins/PageBuilder/Elementor.php [hunk 6]
```diff
@@ -166,4 +169,48 @@ public function exclude_js( $excluded_files ): array {
...
+		if ( 'elementor_library' === $post->post_type ) {
+			return true;
+		}
+
+		return $should_add_option;
```
Comment (remyperona) [inline inc/ThirdParty/Plugins/PageBuilder/Elementor.php]:
```suggestion
		return $should_skip;
```

File: inc/common/admin-bar.php [hunk 7]
```diff
@@ -139,33 +139,43 @@ function rocket_admin_bar( $wp_admin_bar ) {
...
-				/**
-				 * Purge a post.
-				 */
-				if ( $post && 'post.php' === $pagenow && isset( $_GET['action'], $_GET['post'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
+			/**
+			 * Filters Rocket Admin Bar options.
+			 *
+			 * @since 3.11.4
+			 *
+			 * @param bool  $should_add_option Should add rocket option to admin bar.
```
Comment (remyperona) [inline inc/common/admin-bar.php]:
```suggestion
			 * @param bool  $should_skip Should skip adding clear post to admin bar.
```

File: inc/common/admin-bar.php [hunk 8]
```diff
@@ -139,33 +139,43 @@ function rocket_admin_bar( $wp_admin_bar ) {
 				);
 			}
 
-			if ( is_admin() ) {
-				/**
-				 * Purge a post.
-				 */
-				if ( $post && 'post.php' === $pagenow && isset( $_GET['action'], $_GET['post'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
+			/**
+			 * Filters Rocket Admin Bar options.
```
Comment (remyperona) [inline inc/common/admin-bar.php]:
```suggestion
			 * Filters the rocket clear post admin bar menu
```

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Comment by piotrbak** [comment]
@jeawhanlee I'm getting the following warning:
```
PHP Warning:  Attempt to read property "post_type" on null in /var/www/domain.com/htdocs/wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/PageBuilder/Elementor.php on line 210
```

To reproduce:
1. Switch to the PR branch
2. Visit the `wp-admin/edit.php?post_type=page` screen
3. Check the error.log

**Review by CrochetFeve0251 — APPROVED** [review]

**Review by piotrbak — APPROVED** [review]
Working as expected [testrail-report-395.pdf](https://github.com/wp-media/wp-rocket/files/8916860/testrail-report-395.pdf)
