### PR TITLE
Fix #934: Cloudflare validation API when saving - needs proper error messages

### LINKED ISSUE #934: Cloudflare  - No validation of API info when saving
When inputting the Cloudflare email/API key, there is no validation or other messaging when you save. So you can save incorrect information and you won't know. 
Only if you try and clear the Cloudflare cache will some kind of error be displayed.

### PR DESCRIPTION
**Pull request by crystinutzaa**
Added Cloudflare validation API when saving API key, email & zone.

Needs proper error messages. Error messages coming from Cloudflare are "generic" and can lead to confusion.

Based on:
3.4.1 WP Rocket Minor Version doc

### CODE REVIEW

File: inc/functions/cloudflare.php [hunk 1]
```diff
@@ -1,6 +1,50 @@
 <?php
 defined( 'ABSPATH' ) || die( 'Cheatin&#8217; uh?' );
 
+function is_api_keys_valid_cloudflare( $cf_email, $cf_api_key, $cf_zone_id ) {
```
Comment (Tabrisrp) [inline inc/functions/cloudflare.php]:
```suggestion
function rocket_is_api_keys_valid_cloudflare( $cf_email, $cf_api_key, $cf_zone_id ) {
```

File: inc/classes/admin/settings/class-settings.php [hunk 2]
```diff
@@ -367,6 +367,12 @@ public function sanitize_callback( $input ) {
 			$input['cloudflare_api_key'] = WP_ROCKET_CF_API_KEY;
 		}
 
+		$is_api_keys_valid_cloudflare = is_api_keys_valid_cloudflare( $input['cloudflare_email'], $input['cloudflare_api_key'], $input['cloudflare_zone_id']);
```
Comment (Tabrisrp) [inline inc/classes/admin/settings/class-settings.php]:
```suggestion
		$is_api_keys_valid_cloudflare = rocket_is_api_keys_valid_cloudflare( $input['cloudflare_email'], $input['cloudflare_api_key'], $input['cloudflare_zone_id'] );
```

File: inc/classes/admin/settings/class-settings.php [hunk 3]
```diff
@@ -367,6 +367,13 @@ public function sanitize_callback( $input ) {
 			$input['cloudflare_api_key'] = WP_ROCKET_CF_API_KEY;
 		}
 
+		// Check Cloudflare input data and display error message
```
Comment (Tabrisrp) [inline inc/classes/admin/settings/class-settings.php]: You should check if the main CF option `do_cloudflare` is enabled before testing and sending back any error, else it will show an error for something the user is not using.

Comment (crystinutzaa) [reply inc/classes/admin/settings/class-settings.php]: Done. I had Cloudflare enabled and forgot to test it without do_cloudflare. Thank you for spotting this issue!
