### PR TITLE
Fix #1070 Prevent DOMDocument bug with closing HTML tags in inline scripts

### LINKED ISSUE #1070: 3.1 Alpha-2: Console errors for Ninja form
Options in file optimization tab throwing multiple console errors. Can be seen in our-mega-site/genesis/ninja-form/

Combining Google fonts or Remove Query strings or Minify CSS or Minify JS: Error: An "el" .nf-form-layout must exist in DOM

Combining JS: SyntaxError: expected expression, got '<'

### PR DESCRIPTION
**Pull request by Tabrisrp**
DOMDocument doesn't like closing HTML tags in inline scripts (because it's not valid in HTML 4, which it still relies on).

To work around that, we escape early any closing tag found in inline scripts, and unescape them either:
- before they're combined into the combined JS file
- before returning the buffer content at the end when all optimizations have been done

### CODE REVIEW

File: inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+class Scripts_Escaping_Subscriber implements Subscriber_Interface {
+	/**
+	 * @inheritDoc
+	 */
+	public static function get_subscribed_events() {
+		/** This action is documented in inc/classes/subscriber/class-google-tracking-cache-busting-subscriber.php */
+		if ( apply_filters( 'rocket_buffer_enable', true ) ) {
+			return [
+				'rocket_buffer' => [
+					[ 'escape_html_in_scripts', 1 ],
```
Comment (Screenfeed) [inline inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php]: I guess the number is a hook priority.
In case you're not aware of it, and absolutely need to be before everybody, we can use negative values.

File: inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+	 * Escapes HTML closing tags contained in inline scripts to prevent them from being removed by DOMDocument
+	 *
+	 * @since 3.1
+	 * @author Remy Perona
+	 *
+	 * @param string $html HTML content.
+	 * @return string
+	 */
+	public function escape_html_in_scripts( $html ) {
+		preg_match_all( '/<script[^>]*?>(.*)<\/script>/msU', $html, $matches );
```
Comment (Screenfeed) [inline inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php]:
```php
if ( empty( $matches[1] ) ) {
	return $html;
}
```

Comment (Screenfeed) [inline inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php]: Not using `<script[^>]*?>(.*?)<\/script>` in the end?

File: inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+	 * Unescapes HTML closing tags contained in inline scripts once we're done with DOMDocument
+	 *
+	 * @since 3.1
+	 * @author Remy Perona
+	 *
+	 * @param string $html HTML content.
+	 * @return string
+	 */
+	public function unescape_html_in_scripts( $html ) {
+		preg_match_all( '/<script[^>]*?>(.*)<\/script>/msU', $html, $matches );
```
Comment (Screenfeed) [inline inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php]: Like previous one.

File: inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php (hunk 2 above)
Comment (Tabrisrp) [reply inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php]: it was not working with the lazy, don't know why

Comment (Screenfeed) [reply inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php]: Do you know what is the markup then?

File: inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php (hunk 1 above)
Comment (Tabrisrp) [reply inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php]: yes it's the hook priority currently the lowest priority used elsewhere is 10 so 1 is fine

File: inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php (hunk 2 above)
Comment (Screenfeed) [reply inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php]: Oh, forget it, I didn't see you were using the `U` flag.
