### PR TITLE
Closes #4020 Delete metadata from the postmeta table during uninstall

### LINKED ISSUE #4020: Uninstallation - clear metadata from the postmeta table
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

During WP Rocket's uninstallation, the metadata that is saved in the `wp_postmeta` table isn't removed, the same way we do for other database entries/tables and folders:
https://github.com/wp-media/wp-rocket/blob/59045e5ace9948b5ad844c6f4d5c46122089af7b/inc/Engine/WPRocketUninstall.php#L126-L131

**To Reproduce**

1. Disable some of WP Rocket's features in a post using the metabox.
2. Unistall WP Rocket.
3. Search the `wp_postmeta` table for entries containing `_rocket_exclude_`.

**Expected behavior**

We should also clear the `metadata` table during uninstallation.

**Additional context**

This came after @DahmaniAdame asked a question in Slack:
https://wp-media.slack.com/archives/C08N8J6VC/p1623145035349500

We can either delete the data running a query like:
```Mysql
DELETE FROM `wp_postmeta` WHERE meta_key LIKE '%_rocket_exclude_%
```

or using `delete_metadata()`:

```PHP
$rocket_metadata = array( '_rocket_exclude_minify_css',
                          '_rocket_exclude_minify_js',
                          '_rocket_exclude_cdn',
                          '_rocket_exclude_lazyload',
                          '_rocket_exclude_lazyload_iframes',
                          '_rocket_exclude_async_css',
                          '_rocket_exclude_defer_all_js',
                          '_rocket_exclude_delay_js',
                          '_rocket_exclude_remove_unused_css',
			);
foreach( $rocket_metadata as $metadata){
	delete_metadata( 'post', '', $metadata, '', true);//delete metadata
}
```
**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

Created array with possible list of post meta entries with a loop to delete post meta when WPR is uninstalled.

Fixes #4020 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

Solution is in no way different from the proposed one.

## How Has This Been Tested?

Check a few WPR options in the meta of a post, then uninstall to see that WPR related post meta does not exist in the wp_postmeta table.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

File: inc/Engine/WPRocketUninstall.php [hunk 1]
```diff
@@ -87,6 +87,23 @@ class WPRocketUninstall {
...
+		'_rocket_exclude_minify_css',
+		'_rocket_exclude_minify_js',
+		'_rocket_exclude_cdn',
+		'_rocket_exclude_lazyload',
+		'_rocket_exclude_lazyload_iframes',
+		'_rocket_exclude_async_css',
+		'_rocket_exclude_defer_all_js',
+		'_rocket_exclude_delay_js',
+		'_rocket_exclude_remove_unused_css',
+	];
```
Comment (remyperona) [inline inc/Engine/WPRocketUninstall.php]:
```suggestion
	/**
	 * WP Rocket Post meta data entries
	 *
	 * @var array
	 */
	private $post_meta = [
		'minify_css',
		'minify_js',
		'cdn',
		'lazyload',
		'lazyload_iframes',
		'async_css',
		'defer_all_js',
		'delay_js',
		'remove_unused_css',
	];
```

We can use the prefix in the delete function directly, it makes the array easier to read. We also don't need to prefix the private variable.

File: inc/Engine/WPRocketUninstall.php [hunk 2]
```diff
@@ -180,6 +197,11 @@ private function delete_plugin_data() {
 		// Delete all user meta related to WP Rocket.
 		delete_metadata( 'user', '', 'rocket_boxes', '', true );
 
+		// Delete all post meta related to WP Rocket.
+		foreach ( $this->wpr_post_meta as $pm ) {
+			delete_metadata( 'post', '', $pm, '', true );
+		}
```
Comment (remyperona) [inline inc/Engine/WPRocketUninstall.php]:
```suggestion
		foreach ( $this->post_meta as $post_meta ) {
			delete_post_meta_by_key( "_rocket_exclude_{$post_meta}" );
		}
```

We should avoid too short or unexplicity names for variables, so I suggest using `$post_meta` instead of `$pm` for readability.

`delete_post_meta_by_key()` is a wrapper function that achieves the same result, but it's easier to read

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Review by Mai-Saad — APPROVED** [review]
Working as expected for post/page/product while having single/multiple/no data in post meta

**Comment by remyperona** [comment]
@jeawhanlee You can merge this PR, using the squash and merge option
