### PR TITLE
Closes 2441: Fixed warning when temporary file can't be created

### LINKED ISSUE #2441: PHP Warnings after update and on 1st preload
**Describe the bug**
The customer's debug log file is filled with PHP Warnings for `_temp` file extensions not found after updating to 3.5.0.3 and only on the 1st preload. Here's the log they shared:

```
[13-Mar-2020 08:29:55 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/0-credit-card-abroad/index-https.html_gzip_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:09 UTC] PHP Warning:  chmod(): No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 168
[13-Mar-2020 08:30:09 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/credit-card-minimum-payment/index-mobile-https.html_gzip_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:10 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/0-credit-card-abroad/index-mobile-https.html_gzip_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:21 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/about/index-mobile-https.html_gzip_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:38 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/press/index-mobile-https.html_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:41 UTC] PHP Warning:  chmod(): No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 168
[13-Mar-2020 08:30:41 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/privacy-policy/index-mobile-https.html_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
[13-Mar-2020 08:30:43 UTC] PHP Warning:  chmod(): No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 168
[13-Mar-2020 08:30:43 UTC] PHP Warning:  copy(/home/****/wp-content/cache/wp-rocket/www.0creditcardexpert.co.uk/resources/index-mobile-https.html_temp): failed to open stream: No such file or directory in /home/****/wp-admin/includes/class-wp-filesystem-direct.php on line 281
```

- The errors did not reoccur.
- When launching a new preload, no warnings or errors were generated.
- When updating to 3.5.0.4, no warnings or errors were generated.

**To Reproduce**
1. Install 3.4.4.
2. Generate the preload.
3. Clear the debug log <- just to be sure.
4. Update to 3.5.0.3.
5. Check the debug log.

**Expected behavior**
Update and generate preload without PHP warnings.

**Additional context**
- WordPress: v5.3.2
- Rocket: 3.5.0.3
- [HS Ticket](https://secure.helpscout.net/conversation/1108808884/151489?folderId=273768)

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description
Fixed a problem due to a warning happening when we are moving the temporary file to its final position.
For that we added a check to verify if the file was created before moving it.

Fixes #2441

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Manual Test

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: inc/classes/Buffer/class-cache.php [hunk 1]
```diff
@@ -332,7 +332,10 @@ private function write_cache_file( $cache_filepath, $content ) {
 		}
 
 		// Save the cache file.
-		rocket_put_content( $temp_filepath, $content );
+		if ( rocket_put_content( $temp_filepath, $content ) ) {
```
Comment (remyperona) [inline inc/classes/Buffer/class-cache.php]:
```suggestion
		if ( ! rocket_put_content( $temp_filepath, $content ) ) {
```

File: inc/classes/Buffer/class-cache.php [hunk 2]
```diff
@@ -343,7 +346,10 @@ private function write_cache_file( $cache_filepath, $content ) {
 			 */
 			$compression_level = apply_filters( 'rocket_gzencode_level_compression', 6 );
 
-			rocket_put_content( $temp_gzip_filepath, gzencode( $content, $compression_level ) );
+			if ( rocket_put_content( $temp_gzip_filepath, gzencode( $content, $compression_level ) ) ) {
```
Comment (remyperona) [inline inc/classes/Buffer/class-cache.php]:
```suggestion
			if ( ! rocket_put_content( $temp_gzip_filepath, gzencode( $content, $compression_level ) ) ) {
```

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Review by Mai-Saad — COMMENTED** [review]
Can't reproduce the problem here on the test site. However, smoke test for installation, update (from 3.11.5, 3.12.0.5, 3.12.1.1, and 3.12.1), and rollback using the terminal is working fine.
If it's working fine on any of the client's sites then we can merge this PR.
