### PR TITLE
Fixes #1062 #1128 #1132 Combine JS exclusions improvements

### LINKED ISSUE #1062: 3rd Party Scripts cannot be excluded from the administration
We cannot exclude 3rd party JS files in the option" Excluded JavaScript files". Since we combine them, we should be able to exclude them from the admin. 

For example for: 

https://cdnjs.cloudflare.com/ajax/libs/Base64/0.3.0/base64.min.js

We should exclude the full script URL. 

Currently this is the exclusion which is incorrect: 

/ajax/libs/Base64/0.3.0/base64.min.js

### PR DESCRIPTION
**Pull request by Tabrisrp**
- Stop combining inline JS by default, add an option to activate it instead
- Add a field to exclude inline JS patterns from the settings
- Allow third party exclusions in the exclude JS field

### CODE REVIEW

**Comment by Tabrisrp** [comment]
Hold off on review of this since some parts are still in discussion

File: inc/classes/admin/settings/class-page.php [hunk 1]
```diff
@@ -921,11 +923,32 @@ private function assets_section() {
...
+					],
+				],
 				'exclude_js'             => [
 					'type'              => 'textarea',
 					'label'             => __( 'Excluded JavaScript Files', 'rocket' ),
-					'description'       => __( 'Specify URLs of JavaScript files to be excluded from minification and concatenation.', 'rocket' ),
-					'helper'            => __( 'The domain part of the URL will be stripped automatically.<br>Use (.*).js wildcards to exclude all JS files located at a specific path.', 'rocket' ),
+					// translators: %1$s = opening <a> tag, %2$s = closing </a> tag.
+					'description'       => sprintf( __( 'Specify URLs of JavaScript files to be excluded from minification and concatenation (one per line). %1$sMore info%2$s', 'rocket' ), '<a href="' . esc_url( $exclude_js_beacon['url'] ) . '" data-beacon-article="' . esc_attr( $exclude_js_beacon['id'] ) . '" rel="noopener noreferrer" target="_blank">', '</a>' ),
+					'helper'            => __( '<strong>Internal:</strong> The domain part of the URL will be stripped automatically. Use(.*).js wildcards to exclude all JS files located at a specific path.<br>
```
Comment (Screenfeed) [inline inc/classes/admin/settings/class-page.php]: A space character is missing: `Use (.*).js`.

File: inc/classes/admin/settings/class-page.php [hunk 2]
```diff
@@ -921,11 +923,32 @@ private function assets_section() {
...
+					<strong>3rd Party:</strong> Use URL full path, including domain name, to exclude external JS.', 'rocket' ),
```
Comment (Screenfeed) [inline inc/classes/admin/settings/class-page.php]: Multi-line translation? I guess it will be fun when the indentation changes :s

File: inc/classes/admin/settings/class-page.php [hunk 3]
```diff
@@ -921,11 +923,32 @@ private function assets_section() {
 						'button_label' => __( 'Activate combine JavaScript', 'rocket' ),
 					],
 				],
+				'exclude_inline_js'  => [
+					'type'              => 'textarea',
+					'label'             => __( 'Excluded Inline JavaScript', 'rocket' ),
+					// translators: %1$s = opening <a> tag, %2$s = closing </a> tag.
+					'description'       => sprintf( __( 'Specify patterns of inline JavaScript to be excluded from concatenation (one per line). %1$sMore info%2$s', 'rocket' ), '<a href="' . esc_url( $inline_js_beacon['url'] ) . '" data-beacon-article="' . esc_attr( $inline_js_beacon['id'] ) . '" rel="noopener noreferrer" target="_blank">', '</a>' ),
```
Comment (Screenfeed) [inline inc/classes/admin/settings/class-page.php]: Maybe a final dot? `%1$sMore info%2$s.`

File: inc/classes/admin/settings/class-page.php [hunk 4]
```diff
@@ -921,11 +923,32 @@ private function assets_section() {
...
+						'disabled' => get_rocket_option( 'minify_concatenate_js' ) ? 0 : 1,
+					],
+				],
 				'exclude_js'             => [
 					'type'              => 'textarea',
 					'label'             => __( 'Excluded JavaScript Files', 'rocket' ),
-					'description'       => __( 'Specify URLs of JavaScript files to be excluded from minification and concatenation.', 'rocket' ),
-					'helper'            => __( 'The domain part of the URL will be stripped automatically.<br>Use (.*).js wildcards to exclude all JS files located at a specific path.', 'rocket' ),
+					// translators: %1$s = opening <a> tag, %2$s = closing </a> tag.
+					'description'       => sprintf( __( 'Specify URLs of JavaScript files to be excluded from minification and concatenation (one per line). %1$sMore info%2$s', 'rocket' ), '<a href="' . esc_url( $exclude_js_beacon['url'] ) . '" data-beacon-article="' . esc_attr( $exclude_js_beacon['id'] ) . '" rel="noopener noreferrer" target="_blank">', '</a>' ),
```
Comment (Screenfeed) [inline inc/classes/admin/settings/class-page.php]: Maybe a final dot? `%1$sMore info%2$s.`

File: inc/classes/admin/settings/class-settings.php [hunk 5]
```diff
@@ -503,4 +527,41 @@ public function sanitize_callback( $input ) {
...
+	 */
+	private function is_internal_file( $file ) {
+		$file_host = wp_parse_url( $file, PHP_URL_HOST );
+
+		if ( ! $file_host ) {
+			return false;
+		}
+
+		$hosts   = get_rocket_cnames_host( [ 'all', 'css_and_js', 'css', 'js' ] );
+		$hosts[] = wp_parse_url( 'WP_CONTENT_URL', PHP_URL_HOST );
```
Comment (Screenfeed) [inline inc/classes/admin/settings/class-settings.php]: No `'` around `WP_CONTENT_URL`.

```php
$hosts[] = wp_parse_url( WP_CONTENT_URL, PHP_URL_HOST );
```

File: inc/classes/admin/settings/class-settings.php [hunk 6]
```diff
@@ -503,4 +527,41 @@ public function sanitize_callback( $input ) {
...
+		if ( $langs ) {
+			foreach ( $langs as $lang ) {
+				$hosts[] = wp_parse_url( $lang, PHP_URL_HOST );
+			}
+		}
+
+		$hosts_index = array_flip( array_unique( $hosts ) );
+
+		// URL has domain and domain is not part of the internal domains.
+		if ( ! isset( $hosts_index[ $file_host ] ) ) {
```
Comment (Screenfeed) [inline inc/classes/admin/settings/class-settings.php]: Shorter: 😜

```php
return isset( $hosts_index[ $file_host ] );
```

File: inc/classes/optimization/JS/class-combine.php [hunk 7]
```diff
@@ -172,6 +172,12 @@ protected function parse( $scripts ) {
 					return;
 				}
 
+				$matches_inline[2] = str_replace( array( "\r", "\n" ), '', $matches_inline[2] );
+
+				if ( in_array( $matches_inline[2], $this->get_localized_scripts() ) ) {
```
Comment (Screenfeed) [inline inc/classes/optimization/JS/class-combine.php]: You're not strict enough 😛
```php
in_array( $matches_inline[2], $this->get_localized_scripts(), true )
```

File: inc/classes/admin/settings/class-page.php (hunk 2 above)
Comment (Tabrisrp) [reply inc/classes/admin/settings/class-page.php]: better to concatenate the lines separately?

File: inc/classes/admin/settings/class-page.php (hunk 3 above)
Comment (Tabrisrp) [reply inc/classes/admin/settings/class-page.php]: We use the same notation in other places in the settings without the dot, so it will be either dot everywhere or dot nowhere

Comment (Screenfeed) [reply inc/classes/admin/settings/class-page.php]: OK, as long as it's the same everywhere, it's fine 👍

File: inc/classes/admin/settings/class-page.php (hunk 2 above)
Comment (Screenfeed) [reply inc/classes/admin/settings/class-page.php]: IMHO, anything else is better. Personally I'd do `__() . '<br/>' . __()`.
