### PR TITLE
Fixes #1196 Exclude common external jQuery from defer JS safe mode

### LINKED ISSUE #1196: Jquery Safe Mode - exclude common externally hosted jquery
Safe mode for Deferred JS doesn't work if the site is using an externally hosted version of jquery instead of the default WordPress file. 

Could we also automatically exclude the most common versions of externally hosted jquery so that we don't have to use a helper plugin? 

e.g. https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js?ver=1.12.4

### PR DESCRIPTION
**Pull request by Tabrisrp**
Exclude jQuery loaded from `wp.com` CDN and from `ajax.googleapis.com`

### CODE REVIEW

File: inc/functions/options.php [hunk 1]
```diff
@@ -468,9 +468,13 @@ function get_rocket_exclude_defer_js() {
 	];
 
 	if ( get_rocket_option( 'defer_all_js', 0 ) && get_rocket_option( 'defer_all_js_safe', 0 ) ) {
-		$jquery = site_url( $wp_scripts->registered['jquery-core']->src );
+		$jquery            = site_url( $wp_scripts->registered['jquery-core']->src );
```
Comment (Screenfeed) [inline inc/functions/options.php]: I remember some people messing with `jquery-core` and `jquery-migrate`, and registering their custom jQuery under `jquery`. Do you think it's still a thing today?

Comment (Tabrisrp) [reply inc/functions/options.php]: not often enough to warrant that I think, and often they replaced with the googleapis one so it should be covered by that

Comment (Screenfeed) [reply inc/functions/options.php]: OK. Let's say that the risk of `$wp_scripts->registered['jquery-core']->src` not being set or being empty can be neglected then.
