### PR TITLE
Fixes 2633: RegexIterator regex to use Windows dir separator when IIS/Windows

### LINKED ISSUE #2633: Domain cache is not clearing on IIS
**Describe the bug**
`rocket_clean_files()` and `rocket_clean_domain()` do not work on IIS/Windows-based servers. This problem was introduced in 3.5.4 and is happening when using the absolute path as part of the regex.

**To Reproduce**

1. Run Rocket on a Windows/IIS server.
2. Go to Settings > Rocket in the admin backend.
3. Click on "Delete cache" button.
4. Notice that the domain cache is not cleaned.

**Expected behavior**
`rocket_clean_files()` and `rocket_clean_domain()` both should clean on IIS/Windows too.

**Additional context**

https://secure.helpscout.net/conversation/1156832865/163201/
https://secure.helpscout.net/conversation/1155771576/162912/
https://secure.helpscout.net/conversation/1159867977/163952/

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by hellofromtonya**
This PR fixes #2633 by:

1. Checking if it's a Windows-based machine, i.e. via the constant `DIRECTORY_SEPARATOR`.
2. If yes:
    - Changes `/` into `\` for the `FilesystemIterator`
    - Prepares the directory separator for regex.

Note: Skips this switching code when using the virtual filesystem. 

## TODO 

- [x] Add unit tests.
- [x] Test in Parallels (VM for Windows on Mac). ✅ Works
- [x] Test on Windows laptop/desktop. ✅ Works
- [x] Test on customer's IIS servers, i.e. customers who have reported this problem. @vmanthos @piotrbak 
- [x] QA

### CODE REVIEW

**Comment by hellofromtonya** [comment]
@crystinutzaa can you check that this code works on your Windows machine? To check:

1. Go to Settings > Rocket
2. Click on the "Clear domain" button.
3. Does it clean/delete the cache?
4. Any errors?

**Comment by crystinutzaa** [comment]
@hellofromtonya & @piotrbak I tested on my Windows local machina and it worked just fine.

File: inc/functions/files.php [hunk 1]
```diff
@@ -1458,6 +1459,12 @@ function _rocket_get_cache_dirs( $url_host, $cache_path = '', $hard_reset = fals
 		$cache_path = rocket_get_constant( 'WP_ROCKET_CACHE_PATH' );
 	}
 
+	// When Windows-based.
+	$is_windows = ( DIRECTORY_SEPARATOR === '\\' && ( substr( $cache_path, 0, 7 ) !== 'vfs://' ) );
```
Comment (Tabrisrp) [inline inc/functions/files.php:1463]: 7 is the length, but we compare with a string that is 6 characters, am I missing something?

Comment (hellofromtonya) [reply inc/functions/files.php]: Nope. Mistake. Fixed in https://github.com/wp-media/wp-rocket/pull/2632/commits/e4335ecf48ce9c2be744b4557b4c32558a492612.

**Comment by hellofromtonya** [comment]
@piotrbak and @vmanthos Let's test this one our IIS customers sites, i.e. those who reported the problem. In order to test it, you're going to need the updates from PR #2629 for `rocket_clean_domain()` and this PR too. How?

1. Copy and paste this [`inc/functions/files.php` file](https://github.com/wp-media/wp-rocket/blob/fix/apply-redesign-clean-domains/inc/functions/files.php) on their server.
2. Then replace the `_rocket_get_cache_dirs()` code with the [code from this PR, which is here](https://github.com/wp-media/wp-rocket/blob/fix/iis-for-spl-regex/inc/functions/files.php#L1445-L1505).

Please record your findings here as a comment(s).

**Comment by vmanthos** [comment]
I tested this on 2 customers' websites and it's working fine. 👍 

The cache was properly cleared both when using the admin bar menu item and when updating posts/pages.

**Tickets:**
* https://secure.helpscout.net/conversation/1156832865/163201/
* https://secure.helpscout.net/conversation/1159379315/163802/
