### PR TITLE
Fixes #5330 Remove the type casting method on pre and type cast the secret key

### LINKED ISSUE #5330: Fatal error on 3.12.0.1
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
There's another error, here's the log:
https://snippi.com/s/0nvclnq
https://snippi.com/s/dffb0ka

**To Reproduce**
I wasn't able to reproduce the error till now.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

- [x] Remove the options' values casting before saving them.
- [x] Cast string values where we need to have strings

### CODE REVIEW

File: inc/functions/options.php [hunk 1]
```diff
@@ -459,12 +459,12 @@ function get_rocket_cache_query_string() { // phpcs:ignore WordPress.NamingConve
  * @return bool true if everything is ok, false otherwise
  */
 function rocket_valid_key() {
-	$rocket_secret_key = get_rocket_option( 'secret_key' );
+	$rocket_secret_key = (string) get_rocket_option( 'secret_key' );
```
Comment (remyperona) [inline inc/functions/options.php]:
```suggestion
	$rocket_secret_key = (string) get_rocket_option( 'secret_key', '' );
```

File: inc/functions/options.php [hunk 2]
```diff
@@ -459,12 +459,12 @@ function get_rocket_cache_query_string() { // phpcs:ignore WordPress.NamingConve
...
 	if ( ! $rocket_secret_key ) {
 		return false;
 	}
 
-	$valid_details = 8 === strlen( get_rocket_option( 'consumer_key' ) ) && hash_equals( $rocket_secret_key, hash( 'crc32', get_rocket_option( 'consumer_email' ) ) );
+	$valid_details = 8 === strlen( (string) get_rocket_option( 'consumer_key' ) ) && hash_equals( $rocket_secret_key, hash( 'crc32', get_rocket_option( 'consumer_email' ) ) );
```
Comment (remyperona) [inline inc/functions/options.php]:
```suggestion
	$valid_details = 8 === strlen( (string) get_rocket_option( 'consumer_key', '' ) ) && hash_equals( $rocket_secret_key, hash( 'crc32', get_rocket_option( 'consumer_email', '' ) ) );
```

**Review by remyperona — CHANGES_REQUESTED** [review]
Additional change to make sure the default value is a string if the option is not found

**Review by remyperona — APPROVED** [review]
