### PR TITLE
Closes #5599 The /feed/ url is cached and optimized by default on 3.12.3.2

### LINKED ISSUE #5599: The /feed/ url is cached and optimized by default
**Before submitting an issue please check that you’ve completed the following steps:**
yes- Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
On WP Rocket 3.12.3.2 `/feed/` is cached and optimized by default. rolling back to 3.11.5 fixes the issue.
this might be affecting `/wp-json/` too and probably other paths. (untested)

**To Reproduce**
1. Install 3.12.3.2
2. Visit the /feeds URL and see caching and optimization applied
3. Rollback to 3.11.5 and clear the cache
4. Visit the /feeds URL again,  caching and optimization are NOT applied

**Expected behavior**
Feeds should not be cached unless the user opts for this. And optimizations shouldn't be applied in any case.

**Screenshots**
IM3zjAV

https://i.imgur.com/IM3zjAV.jpg

**Additional context**
ticket where /feed/ is cached https://secure.helpscout.net/conversation/2079965213/385018/
probably related, about /wp-json/: https://secure.helpscout.net/conversation/2082507658/385784?folderId=273761

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description
Fixes the issue where trailing slash is appended to non user defined patterns for cache_reject_uri.

Fixes #5599 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?
Automated and Manual Tests.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by remyperona — CHANGES_REQUESTED** [review]
The value in the option should be updated before saving it to the DB, not when serving it from the DB.

We want the change to be reflected in the UI for this field

File: inc/Engine/Cache/Config/ConfigSubscriber.php [hunk 1]
```diff
@@ -47,6 +47,29 @@ function ( $uri ) {
 	 * @return void
 	 */
 	public function regenerate_config_file() {
+		$cache_reject_uri = $this->match_pattern_with_permalink_structure( get_rocket_option( 'cache_reject_uri', [] ) );
+		update_rocket_option( 'cache_reject_uri', $cache_reject_uri );
```
Comment (remyperona) [inline inc/Engine/Cache/Config/ConfigSubscriber.php]: We could use our Options and Options_Data classes instead of the helper functions

File: inc/Engine/Cache/Config/ConfigSubscriber.php [hunk 2]
```diff
@@ -47,6 +47,29 @@ function ( $uri ) {
...
+
 		rocket_generate_config_file();
 	}
+
+	/**
+	 * Modify cache_reject_uri values.
+	 *
+	 * @param array|mixed $value New values.
+	 * @param array|mixed $old_value Old values.
```
Comment (remyperona) [inline inc/Engine/Cache/Config/ConfigSubscriber.php]:
```suggestion
	 * @param mixed $value The new, unserialized option value.
	 * @param mixed $old_value The old option value.
```

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@jeawhanlee I run tests and found that when:
1. the permalinks don't have a `/` and
2. in the **Never Cache URLs** text area `/` was added to prevent caching of the homepage

the `/` is removed so caching of the homepage takes place. This isn't happening with `trunk` or when the permalinks include a trailing `/`.

Can you please look into this?

**Note**

This is to have a reference of the [the index.php issue](https://github.com/wp-media/wp-rocket/issues/678) reported [here](https://github.com/wp-media/wp-rocket/issues/5599#issuecomment-1335678072).

When permalinks:
1. have a trailing `/`and 
2. the `/cache/wp-rocket/example.com/index.php/` folder  is created manually, the non-cached pages are redirected to the homepage.

**Slack discussion:** https://wp-media.slack.com/archives/GUT7FLHF1/p1670251431739879

**Review by mostafa-hisham — APPROVED** [review]

File: inc/Engine/Cache/Config/ConfigSubscriber.php [hunk 3]
```diff
@@ -2,29 +2,107 @@
...
 		];
 	}
 
+	/**
+	 * Returns a matching user added patterns with permalink structure
+	 *
+	 * @param array $patterns user pattern.
+	 * @return array
+	 */
+	public function match_pattern_with_permalink_structure( array $patterns ): array {
```
Comment (engahmeds3ed) [inline inc/Engine/Cache/Config/ConfigSubscriber.php]:
```suggestion
	private function match_pattern_with_permalink_structure( array $patterns ): array {
```

File: inc/Engine/Cache/Config/ConfigSubscriber.php [hunk 4]
```diff
@@ -2,29 +2,107 @@
...
 	/**
 	 * Return an array of events that this subscriber wants to listen to.
 	 *
 	 * @return array
 	 */
 	public static function get_subscribed_events() {
 		return [
-			'permalink_structure_changed' => 'regenerate_config_file',
+			'permalink_structure_changed'         => 'regenerate_config_file',
+			'pre_update_option_' . WP_ROCKET_SLUG => [ 'change_cache_reject_uri_with_permalink', 10, 2 ],
```
Comment (engahmeds3ed) [inline inc/Engine/Cache/Config/ConfigSubscriber.php]:
```suggestion
			'pre_update_option_' . rocket_get_constant( 'WP_ROCKET_SLUG', 'wp_rocket_settings' ) => [ 'change_cache_reject_uri_with_permalink', 10, 2 ],
```
what do u think

File: tests/Fixtures/inc/Engine/Cache/Config/ConfigSubscriber/changeCacheRejectUriWithPermalink.php [hunk 5]
```diff
@@ -0,0 +1,101 @@
+<?php
```
Comment (engahmeds3ed) [inline tests/Fixtures/inc/Engine/Cache/Config/ConfigSubscriber/changeCacheRejectUriWithPermalink.php:1]: (That's a dev matter so it won't affect the PR itself and not a blocker)
I know that you need to write less code and not to duplicate ourselves but this fixture isn't readable for me, I believe you need to make it simpler by writing the pattern manually for each case below, so it'd be easier for anyone to add cases whenever u want

**Review by engahmeds3ed — CHANGES_REQUESTED** [review]

**Review by vmanthos — APPROVED** [review]
This is working as expected now.

**Note**
[The exclusion](https://github.com/wp-media/wp-rocket/issues/5599#issuecomment-1335678072) of `index.php` will not work in [some cases](https://github.com/wp-media/wp-rocket/pull/5604#issuecomment-1338964373).

After internal discussion, we decided that that's fine since we recommend excluding `/index.php` in our docs.
