### PR TITLE
Fixes #3852 Correctly show updated options values after plugin update

### LINKED ISSUE #3852: 3.9 alpha4: Default exclusion list isn't added when it should
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version (3.9-alpha4)
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
After updating to 3.9-alpha4 on a website that already has Delay JS turned on, the default exclusion isn't here by default. We need to refresh the option page to have the default exclusion added.

**To Reproduce**
1. Be sure the current configuration has Delay JS on.
2. Update to 3.9-alpha4
3. See error, the default exclusion isn't added.
4. Refresh the page a,d the default list will be added

**Expected behavior**
The default exclusion list on Delay JS should be added right after the update.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
## Description

As described in the issue, we are in a race condition when loading the settings page as the first page after updating the plugin, which results in incorrect display of the options values sometimes.

Forcing a reload of the page once `wp_rocket_upgrade` is finished will prevent this.

Fixes #3852 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Tested manually by switching between versions of the plugin, and verifying the redirect was correctly triggered

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally with my changes

### CODE REVIEW

File: inc/admin/upgrader.php [hunk 1]
```diff
@@ -40,6 +40,15 @@ function rocket_upgrader() {
 
 	$page = filter_input( INPUT_GET, 'page', FILTER_SANITIZE_STRING );
 
+	if (
+		did_action( 'wp_rocket_upgrade' )
+		&&
+		'wprocket' === $page
```
Comment (engahmeds3ed) [inline inc/admin/upgrader.php]: very minor change request,
I think reversing the order of the conditions will be better as this method is called with `admin_init` so in most cases the `$page` will not equal `wprocket` so we don't need to do the second check `did_action`

```suggestion
		'wprocket' === $page
		&&
		did_action( 'wp_rocket_upgrade' )
```

also, I was thinking that here:
https://github.com/wp-media/wp-rocket/blob/7eb62835e5ffa2b3c79c7625fc7921fbe57739d3/inc/admin/upgrader.php#L21
we do this action so why not defining variable here instead of using `did_action`, I think this will work also.

This is very minor so I will approve it.

**Review by engahmeds3ed — APPROVED** [review]

**Comment by Mai-Saad** [comment]
The issue is only reproducible when updating from the plugins page so in order to retest this fix we need to merge the branch to the alpha zip file .. @Tabrisrp @engahmeds3ed  what do you think?

**Review by Mai-Saad — APPROVED** [review]
(tested on Alpha5 zip) 
[testrail-report-173.pdf](https://github.com/wp-media/wp-rocket/files/6393913/testrail-report-173.pdf)
Working as expected
