### PR TITLE
Fixes #7042 Argument 2 ($url) passed to exclude_rocket_from_wp_updates() must be of the type string

### LINKED ISSUE #7042: Argument 2 ($url) passed to exclude_rocket_from_wp_updates() must be of the type string
**Describe the bug**
User reported the following error with version 3.17.1 (incomplete stack trace was provided):

`Se ha producido un error del tipo E_ERROR en la línea 135 del archivo /home/customer/www/example.net/public_html/wp-content/plugins/wp-rocket/inc/Engine/Plugin/UpdaterSubscriber.php. Mensaje de error: Uncaught TypeError: Argument 2 passed to WP_Rocket\Engine\Plugin\UpdaterSubscriber::exclude_rocket_from_wp_updates() must be of the type string, null given, called in /home/customer/www/example.net/public_html/wp-includes/class-wp-hook.php on line 324 and defined in /home/customer/www/example.net/public_html/wp-content/plugins/wp-rocket/inc/Engine/Plugin/UpdaterSubscriber.php:135
Stack trace:
#0 /home/customer/www/example.net/public_html/wp-includes/class-wp-hook.php(324): WP_Rocket\Engine\Plugin\UpdaterSubscriber->exclude_rocket_from_wp_updates(Array, NULL)
#1 /home/customer/www/example.net/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /home/customer/www/example.net/public_html/wp-includes/class-wp-http.php(234): apply_filters('http_request_ar...', Array, NULL)
#3 /home/customer/www/example.net/public_html/wp-includes/class-wp-http.php(638): WP_Http->request(NULL, Array)
#4 /home/customer/www/example.net/public_html/wp-includes/http.php(184): WP_Http->get(NULL, Array)
#5 /h`

It relates to this line:
https://github.com/wp-media/wp-rocket/blob/ce7b6014eba3777825b2a4cacf942f6b0e7300be/inc/Engine/Plugin/UpdaterSubscriber.php#L135

I can see a recent update to the related method here:
https://github.com/wp-media/wp-rocket/commit/73488699424f726bef28dbf2c934340efcab8e47
https://imageshack.com/a/img922/4788/YNsWPZ.png

The change removed the check to make sure `$url` is a string, and it opens us up to errors like these.

**To Reproduce**
1. Update to version 3.17.1
2. Not sure exactly what other condition is required. Could be a conflict with another plugin or theme.
3. Anything that could cause the `$url` parameter to not be of type `string`.

**Expected behavior**
We should check to confirm the `$url` parameter is a `string` to prevent this error from happening.

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2737001255/518317
Slack - https://wp-media.slack.com/archives/C43T1AYMQ/p1729176825682779

### PR DESCRIPTION
**Pull request by Khadreal**
# Description

Fixes #7042
Fixed error for some users when updating from one version to another.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario
Check #7042 

## Technical description
Revert the phpstan update on the method.

### Documentation

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.

### CODE REVIEW

File: inc/Engine/Plugin/UpdaterSubscriber.php [hunk 1]
```diff
@@ -132,7 +132,11 @@ public static function get_subscribed_events() {
 	 * @param  string $url     The request URL.
 	 * @return array           Updated array of HTTP request arguments.
 	 */
-	public function exclude_rocket_from_wp_updates( $request, string $url ) {
+	public function exclude_rocket_from_wp_updates( $request, $url ) {
+		if ( ! is_string( $url ) ) {
```
Comment (Miraeld) [inline inc/Engine/Plugin/UpdaterSubscriber.php]: You should add a php-stan ignore on this line. 

``` php
// @phpstan-ignore-line GH #7042 - $url variable may be change by other plugins to something else than string.

**Review by Miraeld — CHANGES_REQUESTED** [review]

**Review by Miraeld — APPROVED** [review]

**Comment by Mai-Saad** [comment]
For test: reproduce the issue and confirm it's fixed is enough. Please check this for reproducing it https://wp-media.slack.com/archives/CUT7FLHF1/p1730103718060409?thread_ts=1730101320.378249&cid=CUT7FLHF1

**Review by remyperona — APPROVED** [review]

**Review by hanna-meda — APPROVED** [review]
Thank you, @Khadreal, for this PR.
Reproduced error outside the PR by using snippet from [thread](https://wp-media.slack.com/archives/CUT7FLHF1/p1730103718060409?thread_ts=1730101320.378249&cid=CUT7FLHF1). On PR this error no longer happens (just some deprecation notices because of snippet but confirmed with devs that those are expected in this situation, and a very edgy one).
Confirming this as fixed on test env.
