### PR TITLE
Fixes: #1949 remove lazyload.js file & code when Lazyload is disabled on a specific page

### LINKED ISSUE #1949: When Lazyload is disabled on a specific page, the Lazyload.js file is still loaded
When Lazyload is deactivated for a particular page in the page settings section, the lazyload.js file is still included in the footer of that page. 

Related ticket:
https://secure.helpscout.net/conversation/954182539/122869?folderId=2683093

Slack discussion:
https://wp-media.slack.com/archives/C08N8J6VC/p1568315297052500

### PR DESCRIPTION
**Pull request by crystinutzaa**
Fixes #1949 - when LazyLoad is disabled on a specific page, remove lazyload.js and inline JS code related to lazy load

### CODE REVIEW

File: inc/classes/subscriber/Optimization/class-lazyload-subscriber.php [hunk 1]
```diff
@@ -452,6 +452,14 @@ private function can_lazyload_images() {
 	 * @return boolean
 	 */
 	private function can_lazyload_iframes() {
+		if ( ! $this->options->get( 'lazyload_youtube' ) ) {
+			return false;
+		}
```
Comment (Tabrisrp) [inline inc/classes/subscriber/Optimization/class-lazyload-subscriber.php]: This is a sub-option of the `lazyload_iframes`, so it should be checked separately only when needed

File: inc/classes/subscriber/Optimization/class-lazyload-subscriber.php [hunk 2]
```diff
@@ -258,7 +254,7 @@ public function insert_nojs_style() {
 	 * @return void
 	 */
 	public function insert_youtube_thumbnail_style() {
-		if ( ! $this->options->get( 'lazyload_youtube' ) || ! $this->can_lazyload_iframes() ) {
+		if ( ! $this->can_lazyload_iframes() ) {
```
Comment (Tabrisrp) [inline inc/classes/subscriber/Optimization/class-lazyload-subscriber.php]:
```suggestion
		if ( ! $this->options->get( 'lazyload_youtube' ) || ! $this->can_lazyload_iframes() ) {
```

File: inc/classes/subscriber/Optimization/class-lazyload-subscriber.php [hunk 3]
```diff
@@ -188,7 +184,7 @@ public function insert_lazyload_script() {
 	 * @return void
 	 */
 	public function insert_youtube_thumbnail_script() {
-		if ( ! $this->options->get( 'lazyload_youtube' ) || ! $this->can_lazyload_iframes() ) {
+		if ( ! $this->can_lazyload_iframes() ) {
```
Comment (Tabrisrp) [inline inc/classes/subscriber/Optimization/class-lazyload-subscriber.php]:
```suggestion
		if ( ! $this->options->get( 'lazyload_youtube' ) || ! $this->can_lazyload_iframes() ) {
```
