### PR TITLE
Closes #7678 Send Rocket Insights data to Mixpanel

### LINKED ISSUE #7678: 3.20 - User events tracking
More details [here](https://group-one.atlassian.net/wiki/x/EwDi6wc).

### LINKED ISSUE #7687: WP Rocket database optimization should support InnoDB tables
**Describe the bug**
WP Rocket does not optimize InnoDB tables. This was originally due to the fact that MyISAM was the default WordPress table engine, and InnoDB’s OPTIMIZE TABLE behavior was inconsistent and resource-intensive. To ensure reliability, the conservative approach was to support only MyISAM.

However, this has changed: since WordPress 5.5, InnoDB has been the default engine. Modern MySQL versions (5.6+) also handle InnoDB optimization much more reliably. As a result, most users can no longer benefit from our database optimizations, which highlights the need to revisit and modernize the Database feature.
**To Reproduce**
1. Go to any website using WP Rocket + InnoDB 
2. Click onDatabase tab and activate the different options (Post Cleanup, Comments Cleanup, Transients Cleanup, Database Cleanup, Automatic Cleanup)
3. Run the clearing and nothing happens.

**Expected behavior**
Users with WordPress 5.5 or higher, who are using InnoDB, can take advantage of the Database feature.

**Additional context**
Slack thread: https://group-onecom.slack.com/archives/C08EFUGUH5G/p1758226177831899
Ticket: https://secure.helpscout.net/conversation/3078416520/587186?viewId=7406897

### PR DESCRIPTION
**Pull request by remyperona**
# Description

Fixes #7678

## Type of change

- [x] Task

### What was tested

N/A

### How to test

- Adding a new page should send an event `Rocket Insights Page Added` to Mixpanel, with the properties associated `plan_type` and `tracked_pages`
- When a test is failed or completed, an event is sent `Rocket Insights Performance Test`, with the properties associated `plan_type`, `status`, `retest` and `duration`
- When visiting the WP Rocket dashboard (once per week), an event `Page Viewed` is sent, with property `path`
- Clicking on the `See report` button should send an event `Button Clicked`

### Documentation

This PR implements Mixpanel tracking for Rocket Insights (Performance Monitoring) functionality by adding three key tracking events: URL additions, test completions/failures, and admin page visits. The changes also refactor the credit management system by consolidating it into the existing Plan manager.

- Adds Mixpanel tracking for Rocket Insights user interactions and performance test events
- Consolidates credit management functionality from separate Credit\Manager into Plan manager
- Updates frontend JavaScript to track "see report" button clicks

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.

## Unticked items justification

New tests not needed

### CODE REVIEW

**Comment by CrochetFeve0251** [comment]
@remyperona tests are not passing

File: inc/Engine/Admin/PerformanceMonitoring/AJAX/Controller.php [hunk 1]
```diff
@@ -139,14 +129,19 @@ public function add_new_page(): void {
...
 		 *
 		 * @since 3.20
 		 *
-		 * @param string $url The URL that was added for monitoring.b.
+		 * @param string $url        The URL that was added for monitoring.
+		 * @param Plan   $plan       Plan instance.
+		 * @param int    $urls_count The current number of URLs being monitored.
 		 */
-		do_action( 'rocket_pm_job_added', $url );
+		do_action( 'rocket_pm_job_added', $url, $this->plan, $urls_count );
```
Comment (wordpressfan) [inline inc/Engine/Admin/PerformanceMonitoring/AJAX/Controller.php:144]: the plan and urls_count are global attributes so I think it'd be easier to pass the plan and query instances to the tracking class, what do u think?

Comment (wordpressfan) [reply inc/Engine/Admin/PerformanceMonitoring/AJAX/Controller.php:144]: Let's leave it for now I believe remy did this for a reason, maybe he didn't want to add any dependency to the tracking classes.

**Review by wordpressfan — APPROVED** [review]

**Comment by wordpressfan** [comment]
Going to merge this to release beta2
