### PR TITLE
Fixes #4506 Exclude ai-uncode.js from defer js

### LINKED ISSUE #4506: Automatically exclude a file from WPR’s JS optimization features when Uncode’s Adaptive images is enabled
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔️
- Used the search feature to ensure that the bug hasn’t been reported before ✔️

**Describe the bug**
When Uncode’s _Adaptive Images_ option is enabled along with WPR’s _Load JS deferred_, background images appear blurred.

**To Reproduce**
1. Enable WPR’s _Load JS deferred_
2. Enable _Uncode > Theme options > Performance > Adaptive Images_
3. Visit a page with a background image (like [this one](http://mega.wp-rocket.me/uncode/inspired-by-clouds/) from Mega/Uncode)

The issue is fixed when excluding the following file from Load JS deferred:
`/themes/uncode/library/js/ai-uncode.js`

Screencast for reference: https://share.getcloudapp.com/DOu6k7eq

**Expected behavior**
Images should not be blurred when both features are enabled.

**Screenshots**
Blurred background image: https://share.getcloudapp.com/p9uNLmDR
Image properly displayed: https://share.getcloudapp.com/geupOXnj

**Additional context**
Related ticket: https://secure.helpscout.net/conversation/1694600613/307367/
Slack discussion: https://wp-media.slack.com/archives/C08N8J6VC/p1637060245029300

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by mostafa-hisham**
## Description

Add `/library/js/ai-uncode.js` , `/library/js/min/ai-uncode.min.js`, `/library/js/ai-uncode.min.js`  to the function rocket_exclude_defer_js_uncode()

Fixes #4506 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?
No

## How Has This Been Tested?

- [x] Unit and integration test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
Fixed on Mega site for Defer JS.

Note: if Delay JS is enabled, header/BG image won't be displayed till user interaction. Do we need to handle anything in this case? @piotrbak 

Before interaction:
Screenshot from 2021-12-14 09-20-01

After interaction:
Screenshot from 2021-12-14 09-20-08

**Comment by piotrbak** [comment]
@Mai-Saad To resolve the issue we need to exclude the following form the **Delay JS**:
```
/wp-content/themes/uncode/library/js/init.js
/wp-content/themes/uncode/library/js/ai-uncode.js
UNCODE\.
```

@mostafa-hisham Can we do that within this PR?

File: inc/3rd-party/themes/uncode.php [hunk 1]
```diff
@@ -59,8 +59,31 @@ function rocket_exclude_defer_js_uncode( $exclude_defer_js ) {
...
 
+	/**
+	 * Excludes Uncode JS files from delay JS
+	 *
+	 * @since 3.10.5
+	 *
+	 * @param array $exclude_delay_js Array of JS to be excluded.
+	 * @return array
+	 */
+	function rocket_exclude_defer_js_uncode( $exclude_delay_js ) {
```
Comment (remyperona) [inline inc/3rd-party/themes/uncode.php]:
```suggestion
	function rocket_exclude_delay_js_uncode( $exclude_delay_js ) {
```

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
Working for Delay JS if we added exclusions mentioned above in UI but For some reason auto exclusion isnot working:
`<script type='text/javascript' src='/uncode/wp-content/themes/uncode/library/js/ai-uncode.js' id='uncodeAI' data-async='true' data-home='/uncode/' data-path='/uncode/' data-breakpoints-images='258,516,720,1032,1440,2064,2880' id='ai-uncode-js'></script>`
is delayed and turned into
`<script type="rocketlazyloadscript" data-rocket-type='text/javascript' src='/uncode/wp-content/themes/uncode/library/js/ai-uncode.js' id='uncodeAI' data-async='true' data-home='/uncode/' data-path='/uncode/' data-breakpoints-images='258,516,720,1032,1440,2064,2880' id='ai-uncode-js'></script>`

File: inc/3rd-party/themes/uncode.php [hunk 2]
```diff
@@ -59,8 +59,31 @@ function rocket_exclude_defer_js_uncode( $exclude_defer_js ) {
...
+		$exclude_delay_js[] = rocket_clean_exclude_file( get_template_directory_uri() . '/library/js/init.js' );
+		$exclude_delay_js[] = rocket_clean_exclude_file( get_template_directory_uri() . '/library/js/min/init.min.js' );
+		$exclude_delay_js[] = rocket_clean_exclude_file( get_template_directory_uri() . '/library/js/init.min.js' );
+		$exclude_delay_js[] = rocket_clean_exclude_file( get_template_directory_uri() . '/library/js/min/ai-uncode.min.js' );
+		$exclude_delay_js[] = rocket_clean_exclude_file( get_template_directory_uri() . '/library/js/ai-uncode.min.js' );
+		$exclude_delay_js[] = rocket_clean_exclude_file( get_template_directory_uri() . '/library/js/ai-uncode.js' );
+		$exclude_delay_js[] = 'UNCODE\.';
+		return $exclude_delay_js;
+	}
+	add_filter( 'exclude_delay_js', 'rocket_exclude_delay_js_uncode' );
```
Comment (Mai-Saad) [inline inc/3rd-party/themes/uncode.php]: I think` exclude_delay_js` shall be `rocket_exclude_delay_js`  to follow the same naming convention as the rest. what do you think @mostafa-hisham?

**Review by Mai-Saad — APPROVED** [review]
Working fine now for both Defer JS and Delay JS
[testrail-report-328.pdf](https://github.com/wp-media/wp-rocket/files/7732321/testrail-report-328.pdf)
