### PR TITLE
Background cpu#6408

### LINKED ISSUE #6408: Lazyload background images regexes are taking too long time to load and may timeout, consuming memory and CPU
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**
After doing some investigation on high CPU usage and profiling the code to reach which parts are consuming that much time, We found that the following regexes are taking too much time (over 1.5 seconds in some servers):

https://github.com/wp-media/wp-rocket/blob/29697ac7363ad6b6c9da5ad1b63ec3bdfc135cb7/inc/Engine/Media/Lazyload/CSS/Front/Extractor.php#L41-L43

You can check an example for the first regex with long CSS styles:
https://regex101.com/r/Y2kVDS/1

**To Reproduce**
1. Add the CSS styles from here: https://regex101.com/r/Y2kVDS/1 into a page
2. Enable our lazyload bg images option.
3. Disable the preload
4. Visit the page in incognito mode.
5. You will find the page is taking too long time to load.

**Expected behavior**
We should load the page quickly.

**Slack discussion:** https://wp-media.slack.com/archives/C056ZJMHG0P/p1705319619398929

Also @Miraeld mentioned that we may need to merge both regexes in one but we need to enhance even one of them to work properly with large CSS styles.

### PR DESCRIPTION
**Pull request by Khadreal**
# Description
Refactore the regex pattern for css background lazyloading and improve it to be more faster.
Fixes #6408 

### User documentation

*Explain how this code impacts users.*

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
N/A

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [x] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

## Observability
- [ ] I handled errors when needed.
- [ ] I wrote user-facing messages that are understandable and provide actionable feedbacks.
- [ ] I prepared ways to observe the implemented system (logs, data, etc.).

## Risks
- [ ] I explicitely mentioned performance risks in the PR.
- [ ] I explicitely mentioned security risks in the PR.

### CODE REVIEW

**Comment by Mai-Saad** [comment]
Test plan:
1- Run LLBG tests on e2e `npm run test:llcssbg` => confirms it' passing, if not recheck failed test manually to see if it passes
2- Performance check => running the scenario mentioned here on gamma n times on branch and trunk (compare results)
3- Run related test run https://wpmediaqa.testrail.io/index.php?/runs/view/821&group_by=cases:section_id&group_order=asc
4- Some exploratory test with different themes + page builder

**Review by wordpressfan — CHANGES_REQUESTED** [review]
Why did u update dependencies on this PR?

**Comment by Khadreal** [comment]
> Why did u update dependencies on this PR?

No dependencies was updated, maybe an oversight

**Comment by Khadreal** [comment]
> Why did u update dependencies on this PR?

Fixed this

File: inc/classes/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php [hunk 1]
```diff
@@ -18,7 +18,7 @@
  * @author  Nick Ilyin <nick.ilyin@gmail.com>
  * @author: Victor Stanciu <vic.stanciu@gmail.com> (original author)
  *
- * @version 2.8.41
+ * @version 2.8.45
```
Comment (Miraeld) [inline inc/classes/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php]: Is this dependency update normal ?

File: tests/Unit/inc/Engine/Media/Lazyload/CSS/Front/Extractor/extract.php [hunk 2]
```diff
@@ -7,6 +7,7 @@
 
 use WP_Rocket\Tests\Unit\TestCase;
 use Brain\Monkey\Functions;
+
```
Comment (Miraeld) [inline tests/Unit/inc/Engine/Media/Lazyload/CSS/Front/Extractor/extract.php]: Is this change intended ? As there is nothing else in this test that has been changed, it seems like committed noise

File: inc/Engine/Media/Lazyload/CSS/Front/Extractor.php [hunk 3]
```diff
@@ -149,6 +187,28 @@ protected function extract_urls( string $content, string $file_url = '' ): array
 		return $output;
 	}
 
+	/**
+	 * Reformat css
```
Comment (Miraeld) [inline inc/Engine/Media/Lazyload/CSS/Front/Extractor.php]: It could be nice to have a more descriptive description of this function, in my opinion. 
When you read `reformat css` in the first place, you kinda wonder `reformat to what and why? `

File: inc/classes/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php (hunk 1 above)
Comment (Khadreal) [reply inc/classes/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php]: Nope, it's not supposed to be here

File: inc/Engine/Media/Lazyload/CSS/Front/Extractor.php (hunk 3 above)
Comment (Khadreal) [reply inc/Engine/Media/Lazyload/CSS/Front/Extractor.php]: Updated, please check again

**Review by Miraeld — APPROVED** [review]

**Comment by MathieuLamiot** [comment]
@wordpressfan It seems this PR is pending for your updated review, following your request for changes. Can you have a quick look? Thanks 🙏

File: composer.json [hunk 4]
```diff
@@ -68,7 +68,7 @@
 		"wpackagist-plugin/amp": "^1.1.4",
 		"wpackagist-plugin/hummingbird-performance": "2.0.1",
 		"wpackagist-plugin/jetpack": "9.3.2",
-		"wpackagist-plugin/pdf-embedder": "^4.6",
```
Comment (wordpressfan) [inline composer.json]: This is not needed in this PR

File: inc/classes/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php [hunk 5]
```diff
@@ -216,1477 +216,1477 @@
  */
 class WP_Rocket_Mobile_Detect
 {
-    /**
```
Comment (wordpressfan) [inline inc/classes/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php]: this is dependency update that we don't need here

**Review by wordpressfan — CHANGES_REQUESTED** [review]
Just noticed those dependency updates, will test it locally now over some difference sets of styles

File: composer.json (hunk 4 above)
Comment (wordpressfan) [reply composer.json]: Ok, I figured out that you updated this version to fix workflow errors, correct?

Comment (Khadreal) [reply composer.json]: Yes, it was updated because of CI error

File: inc/classes/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php (hunk 5 above)
Comment (Khadreal) [reply inc/classes/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php]: This is not much of an update per se, it's my IDE just adding space/tabs to the file

Comment (wordpressfan) [reply inc/classes/dependencies/mobiledetect/mobiledetectlib/Mobile_Detect.php]: Yes, I know, I prefer not touching any file other than needed files, I pushed a small commit to revert this.
Thanks Boss.

File: inc/Engine/Media/Lazyload/CSS/Front/Extractor.php [hunk 6]
```diff
@@ -56,30 +58,66 @@ function ( $matches ) {
...
 		foreach ( $matches as $match ) {
-			if ( ! key_exists( 'property', $match ) || ! key_exists( 'selector', $match ) ) {
+			$original_offset = $match[1];
+			$adjusted_offset = strlen( $content ) - $original_offset - strlen( $match[0] );
+
+			// Reverse the selector regex.
+			$reversed_selector_regex = '/dnuorgkcab[^{}]*{\s?(?<reversed_selector>(?:[ \-,:\w\.\n\r^>[*"\'=~\]#]|(?:\][^\]]+\[))+)/mi';
+
+			// Execute preg_match to find reversed selector.
+			preg_match( $reversed_selector_regex, $content_reversed, $matches, PREG_OFFSET_CAPTURE, $adjusted_offset );
```
Comment (wordpressfan) [inline inc/Engine/Media/Lazyload/CSS/Front/Extractor.php]: I think we need to rename this `$matches` not to be exactly the same as the main $matches in the parent loop, this will be readable and robust, what do u think?

File: inc/Engine/Media/Lazyload/CSS/Front/Extractor.php [hunk 7]
```diff
@@ -56,30 +58,66 @@ function ( $matches ) {
...
 
-			$property = $match['property'];
-			$selector = $match['selector'];
+			// Extract reversed selector and reverse it back.
+			$reversed_selector = $matches['reversed_selector'][0];
+			$selector          = strrev( $reversed_selector );
+			$property          = $match[0];
 
 			$property = trim( $property );
 			$selector = trim( $selector );
```
Comment (wordpressfan) [inline inc/Engine/Media/Lazyload/CSS/Front/Extractor.php]:
```suggestion
			$selector          = trim( strrev( $reversed_selector ) );
			$property          = trim( $match[0] );
```

**Review by wordpressfan — APPROVED** [review]
I'll approve it with very minor changes and also wanted to share this concern:
https://bugs.php.net/bug.php?id=80166

I don't know if this is affecting us or not but this flag `PREG_OFFSET_CAPTURE` returns wrong offset when the file contains special characters and in the comments, php team mentioned:

> The documentation should be clarified, but the current behavior is both intentional and preferable. The use of character offsets should be avoided wherever possible.

I just added this to be noted but I believe it's not a blocker for now.

**Comment by MathieuLamiot** [comment]
About the byte vs. number of characters mentionend by @wordpressfan : Hmm interesting but I think that won't be an issue because all methods we use around the PREG_OFFSET_CAPTURE are working with byte:
preg_match_all returns the offset as bytes. Then we do some operations on the original_offset with strlen which also works with bytes. Then we use that value in the next preg_match which expects bytes too.

File: inc/Engine/Media/Lazyload/CSS/Front/Extractor.php (hunk 6 above)
Comment (remyperona) [reply inc/Engine/Media/Lazyload/CSS/Front/Extractor.php]: I agree

**Review by hanna-meda — APPROVED** [review]
[testrail-report-583.pdf](https://github.com/wp-media/wp-rocket/files/14591906/testrail-report-583.pdf)
