### PR TITLE
Fixes #5577 saving CDN CNAMEs with protocol

### LINKED ISSUE #5577: CDN - CNAME field is emptied and can't be added anymore with https protocol.
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
After updating to 3.12.3, the CDN's CNAME field is emptied and the CNAME can't be added anymore to it if it contains the https:// protocol.

**To Reproduce**
1. Add a CNAME like https://xxxxxxxx.rocketcdn.me/
2. Update to 3.12.3
3. There's no more CNAME
4. try to add https://xxxxxxxx.rocketcdn.me and save
5. See the empty field
6. try to add xxxxxxxx.rocketcdn.me
7. CNAME is saved

**Expected behavior**
CNAME should be saved in any case.

**Additional context**
Per, Vasilis, this commit may involved: https://github.com/wp-media/wp-rocket/pull/5105/commits/2244ddcc7e79955170a26a8d4c85d1582a9e9ee2

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

When saving CDN CNAMEs, we remove the ones with http protocol from the options, we need to keep them.
Thanks @vmanthos , u did the hard part.

Fixes #5577

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Locally

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: inc/Engine/Admin/Settings/Settings.php [hunk 1]
```diff
@@ -693,7 +693,7 @@ private function check_global_exclusion( $field ) {
 	private function sanitize_cdn_cnames( array $cnames ) {
 		$cnames = array_map(
 			function( $cname ) {
-				return filter_var( $cname, FILTER_VALIDATE_DOMAIN, FILTER_FLAG_HOSTNAME );
+				return filter_var( $cname, FILTER_VALIDATE_DOMAIN );
```
Comment (remyperona) [inline inc/Engine/Admin/Settings/Settings.php]: not using the hostname flag doesn't filter anything, it will validate incorrect outputs.

Other solution is to use the filter only on the host part, by slicing the url with parse_url and reconstructing it after

**Review by remyperona — CHANGES_REQUESTED** [review]

File: inc/Engine/Admin/Settings/Settings.php (hunk 1 above)
Comment (engahmeds3ed) [reply inc/Engine/Admin/Settings/Settings.php]: Done

File: inc/Engine/Admin/Settings/Settings.php [hunk 2]
```diff
@@ -693,7 +693,17 @@ private function check_global_exclusion( $field ) {
...
+					return false;
+				}
+
+				$cname_parts = get_rocket_parse_url( rocket_add_url_protocol( $cname ) );
+
+				if( false === filter_var( $cname_parts['host'], FILTER_VALIDATE_DOMAIN, FILTER_FLAG_HOSTNAME ) ) {
+					return false;
+				}
+
+				return $cname_parts['scheme'] . '://' . $cname_parts['host'];
```
Comment (remyperona) [inline inc/Engine/Admin/Settings/Settings.php]: We also need to include the path if it exists, some CDN URL use a path value

**Review by remyperona — CHANGES_REQUESTED** [review]

File: inc/Engine/Admin/Settings/Settings.php (hunk 2 above)
Comment (engahmeds3ed) [reply inc/Engine/Admin/Settings/Settings.php]: Good point, Done

**Review by remyperona — APPROVED** [review]

**Comment by piotrbak** [comment]
@wp-media/qa while testing we need to make sure to check the CNAME with/without schema and also with/without path (`cdn.com/site1/`)

**Comment by Mai-Saad** [comment]
@engahmeds3ed Thanks for the PR. While exploring the PR found that if CNAME contains space before it, it will be removed from UI and not applied to the page. This was working on 3.12.2.1, can you please check that :pray:

**Comment by engahmeds3ed** [comment]
> @engahmeds3ed Thanks for the PR. While exploring the PR found that if CNAME contains space before it, it will be removed from UI and not applied to the page. This was working on 3.12.2.1, can you please check that pray

Fixed now, no need for another code review.

**Review by Mai-Saad — APPROVED** [review]
Working as expected with the following notes.
- If CNAME  is not containing a scheme, it will be automatically added in UI HTTP/HTTPS based on the site settings
- If the inline script contains `var WP_DEBUG = {"debug":"1"};` flag, URLs in the inline script  will be written to CNAME (same on 3.12.2.1)
[testrail-report-426.pdf](https://github.com/wp-media/wp-rocket/files/10040036/testrail-report-426.pdf)
