### PR TITLE
RUCSS refactor check_warmup_status

### LINKED ISSUE #3895: RUCSS refactor check_warmup_status
**Describe the bug**
`check_warmup_status()` is doing too much and mixins concerns and makes it a hard time to identify what happens.

Check warmup status is hooked on `init()` , however is bailing out on init if RUCSS is disabled or if the option is empty and fetch_finish_time is not set.

During the latest round of changed , the status of  the option `wp_rocket_prewarmup_stats` was changed. This means that this option will always be kept in the DB and used for metrics. Inside this option, there will be a bool indicator: `allow_optimization` which indicates if RUCSS is enabled or not.

### 1. Modify the  `WP_Rocket\Engine\Optimization\RUCSS\Warmup\Subscriber::check_warmup_status()` 
- Bailout in 2 cases: when RUCSS option is disabled
- when `allow_optimization` is true && `warmup` finished - for warmup finished implement a new method in `Checker.php` which determines this.

### 4. Connect these new methods where are needed 😄 
- On REST API, when the BTN is clicked and RUCSS is manually enabled by the customer, we need to set the warmup status (finish time & allow_optimization)
- When the list of the warmup items finished (no more items in the list) - need to setup the warmup status (finish time & allow_optimization)
- When 1 hour passed after we started the warmup process  - need to setup the warmup status (finish time & allow_optimization)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by crystinutzaa**
## Description

check_warmup_status() is doing too much and mixins concerns and makes it a hard time to identify what happens.

Check warmup status is hooked on init() , however is bailing out on init if RUCSS is disabled or if the option is empty and fetch_finish_time is not set.

During the latest round of changed , the status of the option wp_rocket_prewarmup_stats was changed. This means that this option will always be kept in the DB and used for metrics. Inside this option, there will be a bool indicator: allow_optimization which indicates if RUCSS is enabled or not.

Fixes https://github.com/wp-media/wp-rocket/issues/3895

### CODE REVIEW

File: inc/Engine/Optimization/RUCSS/Warmup/Status/Checker.php [hunk 1]
```diff
@@ -45,31 +45,108 @@ public function __construct( Options $options_api, Options_Data $options, Resour
...
+			$this->set_warmup_status_completed();
+		}
+	}
+
+	/**
+	 * Checks if warmup is completed.
+	 *
+	 * @return void
+	 */
+	public function check_warmup_completed() {
```
Comment (iCaspar) [inline inc/Engine/Optimization/RUCSS/Warmup/Status/Checker.php]:
```suggestion
	public function activate_optimization_on_warmup_completion() {
```

File: inc/Engine/Optimization/RUCSS/Warmup/Status/Checker.php [hunk 2]
```diff
@@ -45,31 +45,108 @@ public function __construct( Options $options_api, Options_Data $options, Resour
...
 		}
 
 		if ( time() > strtotime( '+1 hour', (int) $prewarmup_stats['scan_start_time'] ) ) {
-			$this->set_warmup_status_finish_time();
+			$this->set_warmup_status_completed();
+		}
+	}
+
+	/**
+	 * Checks if warmup is completed.
```
Comment (iCaspar) [inline inc/Engine/Optimization/RUCSS/Warmup/Status/Checker.php]: This description is misleading. It is activating the optimization and setting the finish time on completion.

File: inc/Engine/Optimization/RUCSS/Warmup/Status/Checker.php [hunk 3]
```diff
@@ -45,31 +45,108 @@ public function __construct( Options $options_api, Options_Data $options, Resour
...
 
+		return ! empty( $prewarmup_stats['scan_start_time'] );
+	}
+
+	/**
+	 * Checks warmup status for resources in the prewarmup process.
+	 *
+	 * @return void
+	 */
+	public function check_warmup_status() {
```
Comment (iCaspar) [inline inc/Engine/Optimization/RUCSS/Warmup/Status/Checker.php]:
```suggestion
	public function update_warmup_status_while_has_items() {
```

Again, this is doing something contingently. `check...` implies a bool return on a condition.

File: inc/Engine/Optimization/RUCSS/Warmup/Subscriber.php [hunk 4]
```diff
@@ -130,6 +134,36 @@ public function check_warmup_status() {
...
 	}
 
+	/**
+	 * Checks the is prewarmup process is completed.
+	 *
+	 * @since 3.9
+	 *
+	 * @return void
+	 */
+	public function check_warmup_completed() {
```
Comment (iCaspar) [inline inc/Engine/Optimization/RUCSS/Warmup/Subscriber.php]: Rename to conform to name change in checker.

**Review by iCaspar — CHANGES_REQUESTED** [review]
Mostly requests/suggestions for better method names here.

**Review by iCaspar — APPROVED** [review]
