### PR TITLE
Fixes #3232 Update sanitize for CSS/JS exclusion fields

### LINKED ISSUE #3232: Sanitization on exclude from combination fields prevents from excluding certain scripts
**Describe the bug**
When the theme contains space in the directory name, the sanitization of the Exclude JS/CSS Files prevents us from excluding the files:
- `/wp-content/themes/twenty%20sixteen/genericons/genericons.css` becomes `/wp-content/themes/twentysixteen/genericons/genericons.css`
- `/wp-content/themes/twenty sixteen/genericons/genericons.css` doesn't fetch the files
- The only solution is to use the wildcard `/wp-content/themes/twenty(.*)sixteen/genericons/genericons.css`

**To Reproduce**
1. Work on a theme that has a space in the directory name
2. Enable JS and CSS combination
3. Try to exclude the CSS and JS file using either `/twenty%20sixteen/` or `/twenty sixteen/`
4. Confirm that the first one doesn't save correctly and the second one doesn't work in the frontend

**Expected behavior**
Possibility to exclude the files in a correct way

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by alfonso100**
Fixes #3232

Sanitization on exclude from combination fields prevents from excluding certain scripts.

Applied changes: 
- returning `true` if the file is internal at [rocket_is_internal_file](https://github.com/wp-media/wp-rocket/blob/a1f95920f4e1504af6826a75d1e16294e9b133eb/inc/functions/formatting.php#L135). Props to @vmanthos on this one.

- replacing `sanitize_text_field()` by `esc_url_raw()` at  [rocket_validate_css()](https://github.com/wp-media/wp-rocket/blob/a1f95920f4e1504af6826a75d1e16294e9b133eb/inc/functions/formatting.php#L113-L118) and [rocket_validate_js()](https://github.com/wp-media/wp-rocket/blob/a1f95920f4e1504af6826a75d1e16294e9b133eb/inc/functions/formatting.php#L102)

### Acceptance criteria
- Exclusion of URLs containing encoded spaces `%20` is working correctly

### CODE REVIEW

File: inc/functions/formatting.php [hunk 1]
```diff
@@ -112,10 +112,10 @@ function rocket_validate_js( $file ) {
  */
 function rocket_validate_css( $file ) {
 	if ( rocket_is_internal_file( $file ) ) {
-		return rocket_sanitize_css( rocket_clean_exclude_file( trim( $file ) ) );
+		return esc_url_raw( rocket_clean_exclude_file( trim( $file ) ) );
```
Comment (Tabrisrp) [inline inc/functions/formatting.php:115]: You should keep `rocket_sanitize_css` here

**Review by Tabrisrp — CHANGES_REQUESTED** [review]
One change to fix

**Comment by alfonso100** [comment]
Ooops! reverted this change. thank you Remy!

**Review by Tabrisrp — APPROVED** [review]

**Comment by Tabrisrp** [comment]
@wp-media/qa Ready for QA

**Review by piotrbak — APPROVED** [review]
Worked as expected.
[testrail-report-67.pdf](https://github.com/wp-media/wp-rocket/files/5531990/testrail-report-67.pdf)

**Comment by piotrbak** [comment]
@Tabrisrp @arunbasillal @alfonso100 I checked all possible combinations, it looks like adding the external alone, without .css or .js extension is not possible with that update:

3.7.5:
- example.com/(.*).js 👍
- example.com 👍

3.7.6:
- example.com/(.*).js 👍
- example.com 👎
