### PR TITLE
Fix #3877 Delete RUCSS tables on multisite sub-sites when uninstalling WP Rocket

### LINKED ISSUE #3877: Delete RUCSS tables on multisite sub-sites when uninstalling WP Rocket
**Describe the bug**
RUCSS tables should be deleted on all sub-sites of a multisite when uninstalling WP Rocket. Currently, it's only uninstalling for the main site.

**Additional context**
We need to check for `is_multisite()`, and then use `get_sites()` to get the list of all sub-sites, + a loop over each of them with `switch_to_blog()` to perform the deletion.

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

In multisite, Remove all subsites' DB tables created by us

Fixes #3877

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Manually on our multisite staging site

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: inc/Engine/WPRocketUninstall.php [hunk 1]
```diff
@@ -136,6 +143,24 @@ private function drop_rucss_database_tables() {
...
+
+		foreach ( get_sites( [ 'fields' => 'ids' ] ) as $site_id ) {
+			switch_to_blog( $site_id );
+
+			if ( $this->rucss_resources_table->exists() ) {
+				$this->rucss_resources_table->uninstall();
+			}
+			if ( $this->rucss_usedcss_table->exists() ) {
+				$this->rucss_usedcss_table->uninstall();
+			}
```
Comment (iCaspar) [inline inc/Engine/WPRocketUninstall.php]: The duplication here seems wrong.
Can we maybe extract these lines into it's own private function, please.
Maybe the main function is `remove_all_rucss_database_tables()` and the extracted one is `drop_usedcss_and_resources_tables()`

**Review by iCaspar — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Review by Mai-Saad — APPROVED** [review]
Works as expected but here are 2 comments already on the trunk. ( not related to this PR)
1- Settings of WPR is different in each site when activating WPR on each site separately after fresh installation
2- We over-write advanced-cache.php with each site activation with the same content, Why do we need to overwrite with the same value?
