### PR TITLE
Fixes #4701 Prevent console error when using Elementor with combine JS and user cache

### LINKED ISSUE #4701: Console Errors for logged-in user when Combine js is enabled while Elementor plugin is active
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.7
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Console error displayed for the logged-in user when combine js and user cache are enabled while Elementor is active

**To Reproduce**
- Elementor is enabled 
- User cache and Combine JS are enabled at WPR
1. open home page while logged-in
2. Console errors are there

**Expected behavior**
No console error

**Screenshots**
Screenshot from 2022-02-01 17-52-37

**Additional context**
- Deactivate Elementor or disable Combine JS or disable User Cache will fix the problem
- Tested on 3.10.7 and 3.8 => same results

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
## Description

Add a new method to exclude the `hooks.min.js` file from combine JS when using:
- Elementor
- Combine JS
- User cache and the user is logged in

Fixes #4701 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

- [x] Added unit/integration tests for the new method

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: inc/ThirdParty/Plugins/PageBuilder/Elementor.php [hunk 1]
```diff
@@ -161,4 +142,31 @@ public function add_fix_animation_script( $html ) {
...
+
+		if ( ! $this->options->get( 'cache_logged_user', false ) ) {
+			return $excluded_files;
+		}
+
+		if ( ! is_user_logged_in() ) {
+			return $excluded_files;
+		}
+
+		$excluded_files[] = '/wp-includes/js/dist/hooks.min.js';
```
Comment (engahmeds3ed) [inline inc/ThirdParty/Plugins/PageBuilder/Elementor.php]: Do we need to handle both `min` and source files? as if `SCRIPT_DEBUG` is true, the page will load the source file not the minified one.
Like what we do here: https://github.com/wp-media/wp-rocket/blob/f7667cd723f29484c222d49c274fda6a11abffd5/inc/Engine/Optimization/DeferJS/DeferJS.php#L231

**Review by engahmeds3ed — CHANGES_REQUESTED** [review]

File: inc/ThirdParty/Plugins/PageBuilder/Elementor.php (hunk 1 above)
Comment (remyperona) [reply inc/ThirdParty/Plugins/PageBuilder/Elementor.php]: Indeed it's better to cover both, code is updated

**Review by engahmeds3ed — APPROVED** [review]

**Review by Mai-Saad — APPROVED** [review]
Working as expected
