### PR TITLE
Fixes #3521 Add position configuration for Beacon display

### LINKED ISSUE #3521: Beacon is covering WordPress's menu when RTL languages are used
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

When an RTL language, e.g. Hebrew is used in WordPress, the beacon is covering part of the menu when the user is on WP Rocket's options page.

**To Reproduce**

1. Set Hebrew as the WordPress language.
2. Visit WP Rocket's dashboard.
3. See the issue:

**Expected behavior**

The Beacon should be on the left on RTL languages.

**Additional context**

**Ticket:** https://secure.helpscout.net/conversation/1404323697/233602?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
## Description

This PR adds support for RTL languages when displaying the HS Beacon on our settings page.

Instead of always being displayed on the right hand side, it's now displayed on the left hand side for RTL languages.

Fixes #3521

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] Tested on LTR language with english set as the website language in WP settings
- [x] Tested on RTL language with arabic  set as the website language in WP settings
- [x] Unit/Integration tests updated to validate the Beacon configuration

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: tests/Integration/inc/Engine/Admin/Beacon/Beacon/insertScript.php [hunk 1]
```diff
@@ -26,12 +26,15 @@ public function setUp() {
 	}
 
 	public function tearDown() {
-		parent::tearDown();
-
+		global $wp_locale;
 		set_current_screen( 'front' );
 
+		$wp_locale->text_direction = 'ltr';
```
Comment (engahmeds3ed) [inline tests/Integration/inc/Engine/Admin/Beacon/Beacon/insertScript.php]: **[MINOR]** why not setting real current value on setup method and then use it here not to use static value.

**Review by engahmeds3ed — APPROVED** [review]

File: tests/Integration/inc/Engine/Admin/Beacon/Beacon/insertScript.php (hunk 1 above)
Comment (remyperona) [reply tests/Integration/inc/Engine/Admin/Beacon/Beacon/insertScript.php]: good point, I updated the test to reflect that

**Comment by remyperona** [comment]
@wp-media/qa ready for QA

**Review by Mai-Saad — CHANGES_REQUESTED** [review]
Not fixed with IE edge on windows 10
IE11Windows10

**Review by Mai-Saad — COMMENTED** [review]
With a small screen size i.e 1024 x 768, the Help Beacon will hide the WP version number independent on local/used browser (I think we need to open a separate issue for this)
SmallerScreen

**Review by Mai-Saad — CHANGES_REQUESTED** [review]
<strike>
Not working when WP in a subdirectory (testing URL:  https://nest.rocketlabsqa.ovh/wp/) using chrome on ubuntu.
</strike>

Update: working fine after pull changes

**Comment by remyperona** [comment]
> Not fixed with IE edge on windows 10

> With a small screen size i.e 1024 x 768, the Help Beacon will hide the WP version number independent on local/used browser (I think we need to open a separate issue for this)

All the styling is done by the source from Beacon/Helpscout, so it's not something we can change.

**Review by Mai-Saad — COMMENTED** [review]
Since IE11 not in our hands then working fine on different env and other browsers.

Note: we need rerun tests to check the failed one, I am having a problem to have working WP local on PHP 7.4 for now

**Comment by remyperona** [comment]
All checks have passed now

**Review by Mai-Saad — APPROVED** [review]
- Work as expected on supported browsers
