### PR TITLE
Exclude expired users from adding home page automatically inside rocket insights feature

### LINKED ISSUE #8029: Don't automatically add home page in Rocket Insights tests when user endpoint is down
**Describe the bug**
Now when the user API endpoint returns not valid response for any reason (maybe site is down or something wrong went there), we are adding homepage automatically into Rocket Insights feature to be processed by SaaS, which adds more headache on our servers in case user endpoint is down.

**To Reproduce**
1. Mock the user endpoint to return not valid json response, u can find it [here](https://group-onecom.slack.com/archives/C08EFCYRQ2X/p1770378172405649?thread_ts=1770378017.693009&cid=C08EFCYRQ2X)
2. Use 3.20.2 zip file or GH tag
3. Update to 3.20.3 (we have the code to automatically insert home page into RI)
4. Make sure that rocket_insights_add_homepage_expiry_interval from dynamic lists is more than 0, for production it's 7 now.

**Expected behavior**
For this case we shouldn't add the homepage

**Additional context**
s

### PR DESCRIPTION
**Pull request by wordpressfan**
# Description

Fixes #8029

Here we will exclude expired users from adding homepage automatically after update.

## Type of change

- [ ] New feature (non-breaking change which adds functionality).
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).
- [ ] Sub-task of #(issue number)
- [ ] Chore
- [ ] Release

### What was tested

Steps are there in the issue itself.

### How to test

Steps are there in the issue itself.

### Affected Features & Quality Assurance Scope

- Rocket Insights

### Documentation

Now we are excluding expired users from automatically adding homepage into rocket insights feature with update.

### New dependencies

N/A

### Risks

N/A

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification

*If some mandatory items are not relevant, explain why in this section.*

# Additional Checks
- [ ] In the case of complex code, I wrote comments to explain it.
- [ ] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [ ] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

File: tests/Fixtures/inc/Engine/License/Renewal/isExpiringIn.php [hunk 1]
```diff
@@ -38,7 +38,7 @@
 				'license_expiration' => $now - ( 5 * DAY_IN_SECONDS ), // Expired 5 days ago.
 				'duration_in_days'   => 30,
 			],
-			'expected' => true,
+			'expected' => false,
```
Comment (Mai-Saad) [inline tests/Fixtures/inc/Engine/License/Renewal/isExpiringIn.php:41]: Why expected not matching test title?

**Review by jeawhanlee — APPROVED** [review]
