### PR TITLE
Fixes #1430 Allow json upload after WP latest security update

### LINKED ISSUE #1430: Import settings failed with error: Settings import failed: incorrect filetype
Tools tab > export settings, then import the same settings. Got this error.

import error

Recreated both on `3.2.3` and `3.1.4`. [Vasilis got the same](https://wp-media.slack.com/archives/C08N8J6VC/p1544699369019200?thread_ts=1544698554.018800&cid=C08N8J6VC) and [customer reported it as well](https://secure.helpscout.net/conversation/730832086/90166/).

### PR DESCRIPTION
**Pull request by Tabrisrp**
Make settings import work again

### CODE REVIEW

File: inc/admin/admin.php [hunk 1]
```diff
@@ -507,7 +507,43 @@ function rocket_handle_settings_import() {
 		rocket_settings_import_redirect( __( 'Settings import failed: incorrect filename.', 'rocket' ), 'error' );
 	}
 
-	add_filter( 'upload_mimes', 'rocket_allow_json_mime_type' );
+	add_filter( 'mime_types', 'rocket_allow_json_mime_type' );
+
+	add_filter(
+		'wp_check_filetype_and_ext',
+		function( $wp_check_filetype_and_ext, $file, $filename, $mimes ) {
```
Comment (Screenfeed) [inline inc/admin/admin.php]: Shame!
