### PR TITLE
3118 Fix external css minify exclusions

### LINKED ISSUE #3118: 3.7: External CSS Minify exclusions are not working as intended
The specs for excluding an external CSS file from minify are: 

>3rd Party: Use either the full URL path or only the domain name, to exclude external CSS. 

However there are some cases where this is not working as expected. 

Samples: 
- https://use.fontawesome.com/releases/v5.14.0/css/all.css
Had to be excluded like this: /releases/v5.14.0/css/all.css

- https://cloud.typography.com/7231672/6270372/css/fonts.css
Had to be excluded like this: /7231672/6270372/css/fonts.css

Seems only to be an issue with Minify, not Combine

Tickets: 
- https://secure.helpscout.net/conversation/1281498132/194658?folderId=3572910
- https://secure.helpscout.net/conversation/1278389385/193723?folderId=2675957

**To Reproduce**
1. Include one of the above URLS in the HTML of a site
2. Enable Minify CSS
3. Try to exclude the file with either the domain or full URL

**Expected behavior**
The files should be excluded using either the domain or full URL

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by iCaspar**
Per #3118 -
[X] - Add testcases for external css with URL in domains
[X] - Modify regex to make tests pass

### CODE REVIEW

File: inc/Engine/Optimization/Minify/CSS/Minify.php [hunk 1]
```diff
@@ -32,6 +33,19 @@ public function optimize( $html ) {
 		}
 
 		foreach ( $styles as $style ) {
+			foreach ( $this->get_excluded_externals() as $excluded ) {
```
Comment (Tabrisrp) [inline inc/Engine/Optimization/Minify/CSS/Minify.php:36]: 2 suggestions: 
- Initialize the excluded outside of the loops, that way the method is only called once
- Instead of a second loop, how about imploding the array into a string pattern, and using `preg_match()` to do the matching in the URL?

File: inc/Engine/Optimization/Minify/CSS/Minify.php [hunk 2]
```diff
@@ -323,9 +347,30 @@ protected function minify( $file_path, $minified_file, $file_content ) {
...
+		/**
+		 * Filters CSS external URLs to exclude from the minify process
+		 *
+		 * @since 3.7.6
+		 *
+		 * @param array $pattern Patterns to match.
+		 */
+		$excluded_externals = (array) apply_filters( 'rocket_minify_css_excluded_external', [] );
+
+		return array_merge( $excluded_externals, $this->options->get( 'exclude_css', [] ) );
```
Comment (engahmeds3ed) [inline inc/Engine/Optimization/Minify/CSS/Minify.php:374]: I don't like using array_merge as it's slow, can u check the following and test it.
```suggestion
		return [ ...$excluded_externals, ...$this->options->get( 'exclude_css', [] ) ];
```
This code is using [Spread Operator](https://wiki.php.net/rfc/spread_operator_for_array) which I think it's included from PHP 5.6 (If I remember well)

and also do we need to make this array unique?
if Yes, I think using `array_flip` twice will do the trick faster.

@iCaspar What do u think?

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by engahmeds3ed — CHANGES_REQUESTED** [review]

File: inc/Engine/Optimization/Minify/CSS/Minify.php (hunk 2 above)
Comment (iCaspar) [reply inc/Engine/Optimization/Minify/CSS/Minify.php]: Found a way to eliminate this method altogether :)

File: inc/Engine/Optimization/Minify/CSS/Minify.php (hunk 1 above)
Comment (iCaspar) [reply inc/Engine/Optimization/Minify/CSS/Minify.php]: Moved this check into `AbstractCSSOptimization::is_minify_excluded_file()`.

**Review by remyperona — APPROVED** [review]

**Comment by Tabrisrp** [comment]
@wp-media/qa ready for QA

**Review by piotrbak — APPROVED** [review]
Worked as expected:
[Uploading testrail-report-71.pdf…]()
