### PR TITLE
Closes #3477 - Subsites on multisite loading incorrect config file

### LINKED ISSUE #3477: Multisite - Cache Query String(s) & other features not working on subsites
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

**Cache Query String(s)**, as well as any other option we save in the configuration file in `/wp-content/wp-rocket-config/` will not work on multisite.

Changes made on a subsite will be written in the subsite-specific configuration file, e.g. `example.com.subsite.php`.

However, the configuration file that we are using is that of the main site:
https://github.com/wp-media/wp-rocket/blob/df26acdfbe015d056fc442cfbf28734f9635aa9f/inc/classes/Buffer/class-tests.php#L192

which doesn't have the changes applied to the subsite.

**To Reproduce**
1. Go to MEGA/Multisite.
2. On a subsite add a query string in the **Cache Query String(s)** text area in the **Advanced Rules** tab.
3. Visit a URL after appending the query string from step 2.
4. Check the source code of the page. It won't be cached/optimized.

**Expected behavior**

The features should work when they are set up on subsites.

**Additional context**

A workaround is to use the main site's advanced rules tab to add the query strings that need to be cached.
However, this can be problematic if the specific behavior is only needed on subsites.

**Related ticket:** https://secure.helpscout.net/conversation/1393512095/230531?folderId=2135277

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

This will fix the issue of subsites loading incorrect config file(the main site config file) on multisite.

Fixes #3477 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual Tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: inc/classes/Buffer/class-config.php [hunk 1]
```diff
@@ -197,34 +197,33 @@ public function get_config_file_path() {
...
-				return self::memoize(
+				$config_file_paths[] = self::$config_dir_path . $host . '.' . $dir . $p . '.php';
+			}
+
+			$dir .= $p . '.';
+		}
+
+		$config_file_paths = array_reverse( $config_file_paths );
+
+		foreach ( $config_file_paths as $config_path ) {
```
Comment (remyperona) [inline inc/classes/Buffer/class-config.php]: If I understand correctly, here we are reversing the array order and then using the first item of the array for the config path, is that right?

Comment (jeawhanlee) [reply inc/classes/Buffer/class-config.php]: That's right. We can just return the first item alone right?

Comment (remyperona) [reply inc/classes/Buffer/class-config.php]: In that case, you can use `array_shift()` to extract the first item of the array directly instead of starting a loop

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
Working as expected
[testrail-report-434.pdf](https://github.com/wp-media/wp-rocket/files/10259923/testrail-report-434.pdf)
