### PR TITLE
Fix #2374  - Cloudflare remove ajax calls when saving development mode and optimal settings

### LINKED ISSUE #2374: Cloudflare error while saving Optimal Settings
**Describe the bug**
When filling in Cloudflare credentials and enabling Optimal Settings in one step, we are receiving an error and settings are not saved.

**To Reproduce**
1. On WP Rocket install with Cloudflare
2. Fill the correct Cloudflare credentials
3. Enable Optimal Settings
4. Save settings
5. The error should be outputted, CF settings not changed.

**Expected behavior**
Optimal settings should be enabled correctly
OR
Optimal settings button should be disabled until credentials are filled in

**Screenshots**
Error screenshot:
https://i.vgy.me/1Xinkg.jpg

**Additional context**
The problem was investigated by @vmanthos and @crystinutzaa here:
https://wp-media.slack.com/archives/CBJ2KQ0MU/p1583302791209100

This bug is a continuation of the following one:
https://github.com/wp-media/wp-rocket/issues/2295#issue-559886603

**Backlog Grooming**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by crystinutzaa**
Fixes #2374 

**Reproduce the issue** ✅ 
Reproduced on my local test site

**Identify the root cause** ✅ 
The root cause is related to the order of the operations. 
Optimal Settings are saved with AJAX call, while Cloudflare credentials are saved when submitting WP Rocket settings page.

**Scope a solution** ✅ 
Remove ajax calls when saving development mode and optimal settings  and save on form submit. 
Check that error messages to be well displayed and not duplicated.

### CODE REVIEW

File: inc/Addon/Cloudflare/Subscriber.php [hunk 1]
```diff
@@ -370,15 +372,29 @@ public function save_cloudflare_options( $old_value, $value ) {
...
+
+		if ( ( isset( $old_value['cloudflare_devmode'], $value['cloudflare_devmode'] ) && (int) $old_value['cloudflare_devmode'] !== (int) $value['cloudflare_devmode'] ) ||
+			( isset( $old_value['cloudflare_auto_settings'], $value['cloudflare_auto_settings'] ) && (int) $old_value['cloudflare_auto_settings'] !== (int) $value['cloudflare_auto_settings'] ) ) {
+			$submit_cloudflare_view = true;
+		}
+
+		// Revalidate Cloudflare credentials if transient is false.
+		if ( false === $is_api_keys_valid_cloudflare ) {
+			$is_api_keys_valid_cloudflare = $this->cloudflare->is_api_keys_valid( $value['cloudflare_email'], $value['cloudflare_api_key'], $value['cloudflare_zone_id'] );
+			set_transient( 'rocket_cloudflare_is_api_keys_valid', $is_api_keys_valid_cloudflare, 2 * WEEK_IN_SECONDS );
```
Comment (Screenfeed) [inline inc/Addon/Cloudflare/Subscriber.php]:
```suggestion
			if ( isset( $value['cloudflare_email'], $value['cloudflare_api_key'], $value['cloudflare_zone_id'] ) ) {
				$is_api_keys_valid_cloudflare = $this->cloudflare->is_api_keys_valid( $value['cloudflare_email'], $value['cloudflare_api_key'], $value['cloudflare_zone_id'] );
			} else {
				$is_api_keys_valid_cloudflare = false;
			}
			set_transient( 'rocket_cloudflare_is_api_keys_valid', $is_api_keys_valid_cloudflare, 2 * WEEK_IN_SECONDS );
```

File: inc/Addon/Cloudflare/Subscriber.php [hunk 2]
```diff
@@ -370,15 +372,29 @@ public function save_cloudflare_options( $old_value, $value ) {
...
+		}
+
+		// If is submit CF view & CF Credentials are invalid, display error and bail out.
+		if ( is_wp_error( $is_api_keys_valid_cloudflare ) && $submit_cloudflare_view ) {
+			$cloudflare_error_message = $is_api_keys_valid_cloudflare->get_error_message();
+			add_settings_error( 'general', 'cloudflare_api_key_invalid', __( 'WP Rocket: ', 'rocket' ) . '</strong>' . $cloudflare_error_message . '<strong>', 'error' );
```
Comment (Screenfeed) [inline inc/Addon/Cloudflare/Subscriber.php]: About `add_settings_error()`:
- This will be triggered even when `update_option()` is used directly, not only when the settings are saved through the settings page. I guess it will leads to the message appearing at random times.
- `__( 'WP Rocket: ', 'rocket' ) . '</strong>' . $cloudflare_error_message . '<strong>'`: do we know what this message may contain? If it's clearly mentioning Cloudflare it's fine, but if it's something like "Connection error" we will have a confusing message.

**Comment by Screenfeed** [comment]
No automated tests?

File: inc/Addon/Cloudflare/Subscriber.php (hunk 2 above)
Comment (crystinutzaa) [reply inc/Addon/Cloudflare/Subscriber.php]: The error message will be clear directly from Cloudflare. 
The one which might be confusing is related to disabled curl.

**Comment by crystinutzaa** [comment]
All CF tests are in here: 
https://github.com/wp-media/cloudflare/pull/20

**Comment by Tabrisrp** [comment]
@piotrbak This is ready for QA

**Comment by crystinutzaa** [comment]
@piotrbak I identified the issue and fixed it. Can you please retry?

**Comment by piotrbak** [comment]
Starting QA
