### PR TITLE
Fixes #4757 Exclude AMP redirection script from delay JS

### LINKED ISSUE #4757: Exclude the script for AMP redirection from Delay JS
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.10.8
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The script which redirects mobile pages to the amp is delayed

**To Reproduce**
- Cache for mobile devices is enabled
- Delay JS is enabled
- Amp redirect is enabled

1. Open the home page in mobile view 
2. redirect to ?amp does not occur till user interaction

**Expected behavior**
Amp redirect occurs without user interaction

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

Fix the problem which prevent the page from redirecting automatically to the ?amp=1 page without any user interaction.
This has been implemented by excluding wprRemoveCPCSS from Delay JS.
Fixes #4757 
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No the grooming was right

## How Has This Been Tested?

- [x] Run tests locally
- [x] Check the behavior on my own testing website

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by CrochetFeve0251** [comment]
@engahmeds3ed Should I change fixtures for this functionnality with the following script as it is external plugin: ```<script type="16b9331a55e54810d7a4cd33-text/javascript">
!function(){var e={};e.g=function(){if("object"==typeof globalThis)return globalThis;try{return this||new Function("return this")()}catch(e){if("object"==typeof window)return window}}(),function(n){let{ampUrl:t,isCustomizePreview:r,isAmpDevMode:o,noampQueryVarName:s,noampQueryVarValue:i,disabledStorageKey:a,mobileUserAgents:c,regexRegex:u}=n;if("undefined"==typeof sessionStorage)return;const d=new RegExp(u);if(!c.some((e=>{const n=e.match(d);return!(!n||!new RegExp(n[1],n[2]).test(navigator.userAgent))||navigator.userAgent.includes(e)})))return;e.g.addEventListener("DOMContentLoaded",(()=>{const e=document.getElementById("amp-mobile-version-switcher");if(!e)return;e.hidden=!1;const n=e.querySelector("a[href]");n&&n.addEventListener("click",(()=>{sessionStorage.removeItem(a)}))}));const g=o&&["paired-browsing-non-amp","paired-browsing-amp"].includes(window.name);if(sessionStorage.getItem(a)||r||g)return;const m=new URL(location.href),h=new URL(t);h.hash=m.hash,m.searchParams.has(s)&&i===m.searchParams.get(s)?sessionStorage.setItem(a,"1"):h.href!==m.href&&(window.stop(),location.replace(h.href))}({"ampUrl":"https:\/\/rocket.mitango.app\/?amp=1","noampQueryVarName":"noamp","noampQueryVarValue":"mobile","disabledStorageKey":"amp_mobile_redirect_disabled","mobileUserAgents":["Mobile","Android","Silk\/","Kindle","BlackBerry","Opera Mini","Opera Mobi"],"regexRegex":"^\\/((?:.|\n)+)\\/([i]*)$","isCustomizePreview":false,"isAmpDevMode":false})}();
</script>```

**Comment by CrochetFeve0251** [comment]
@engahmeds3ed I added the script to the fixtures

**Comment by engahmeds3ed** [comment]
@CrochetFeve0251 it looks good to me.

@Tabrisrp we already have third party compatibility for for AMP, do u think it'd be better if we used the filter there to add this exclusion?

**Comment by remyperona** [comment]
It could be cleaner that way indeed

**Comment by CrochetFeve0251** [comment]
@engahmeds3ed I added the integration test

File: inc/ThirdParty/Plugins/Optimization/AMP.php [hunk 1]
```diff
@@ -177,4 +178,17 @@ public function reject_files( $files ) {
 			]
 		);
 	}
+
+	/**
+	 * Adds the switching script from AMP to excluded files
+	 *
+	 * @since 3.10.1
```
Comment (remyperona) [inline inc/ThirdParty/Plugins/Optimization/AMP.php]:
```suggestion
	 * @since 3.11.1
```

File: tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+/**
+ * @covers \WP_Rocket\ThirdParty\Plugins\Optimization\AMP::exclude_script_from_delay_js
+ * @group  ThirdParty
+ * @group  WithAmp
+ */
+class Test_ExcludeScriptFromDelayJs extends TestCase
+{
+	/**
+	 * @dataProvider providerTestData
+	 */
```
Comment (remyperona) [inline tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php]:
```suggestion
	/**
	 * @dataProvider configTestData
	 */
```

You can use the configTestData method as the data provider, it will automatically match with the corresponding file in the fixtures directory

File: tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+	public function testShouldExcludeScriptWhenAmpPresent($config, $expected) {
+		$this->assertEquals($expected['excluded'], apply_filters( 'rocket_delay_js_exclusions', $config['excluded']));
+	}
+
+	public function providerTestData() {
+		return $this->getTestData( __DIR__, 'excludeScriptFromDelayJs' );
+	}
```
Comment (remyperona) [inline tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php]:
```suggestion
```

File: tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+		parent::setUp();
+
+		$this->options        = Mockery::mock( Options_Data::class );
+		$this->cdn_subscriber = Mockery::mock( Subscriber::class );
+		$this->amp            = new AMP( $this->options, $this->cdn_subscriber );
+	}
+
+	/**
+	 * @dataProvider providerTestData
+	 */
```
Comment (remyperona) [inline tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php]:
```suggestion
	/**
	 * @dataProvider configTestData
	 */
```

File: tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+	public function testShouldDoExpected($config, $expected) {
+		$this->assertEquals($expected['excluded'], $this->amp->exclude_script_from_delay_js($config['excluded']));
+	}
+
+	public function providerTestData() {
+		return $this->getTestData( __DIR__, 'excludeScriptFromDelayJs' );
+	}
```
Comment (remyperona) [inline tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php]:
```suggestion
```

**Review by remyperona — CHANGES_REQUESTED** [review]

File: tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php [hunk 6]
```diff
@@ -0,0 +1,38 @@
+<?php
+
+namespace WP_Rocket\Tests\Unit\inc\ThirdParty\Plugins\Optimization\AMP;
+
+use Mockery;
+use WP_Rocket\Admin\Options_Data;
+use WP_Rocket\Engine\CDN\Subscriber;
+use WP_Rocket\ThirdParty\Plugins\Optimization\AMP;
+use WPMedia\PHPUnit\Unit\TestCase;
```
Comment (remyperona) [inline tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php]:
```suggestion
use WP_Rocket\Tests\Unit\TestCase;
```

File: tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php [hunk 7]
```diff
@@ -0,0 +1,25 @@
+<?php
+
+namespace WP_Rocket\Tests\Unit\inc\ThirdParty\Plugins\Optimization\AMP;
+
+use Mockery;
+use WP_Rocket\Admin\Options_Data;
+use WP_Rocket\Engine\CDN\Subscriber;
+use WP_Rocket\ThirdParty\Plugins\Optimization\AMP;
+use WPMedia\PHPUnit\Unit\TestCase;
```
Comment (remyperona) [inline tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php]:
```suggestion
use WP_Rocket\Tests\Integration\TestCase;
```

Comment (remyperona) [inline tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/excludeScriptFromDelayJs.php]:
```suggestion
```

File: inc/ThirdParty/Plugins/Optimization/AMP.php [hunk 8]
```diff
@@ -177,4 +178,17 @@ public function reject_files( $files ) {
 			]
 		);
 	}
+
+	/**
+	 * Adds the switching script from AMP to excluded files
```
Comment (remyperona) [inline inc/ThirdParty/Plugins/Optimization/AMP.php]:
```suggestion
	 * Adds the switching script from AMP to delay JS excluded files
```

**Review by remyperona — CHANGES_REQUESTED** [review]

**Comment by CrochetFeve0251** [comment]
@Tabrisrp I made changes

**Review by remyperona — APPROVED** [review]

**Review by Mai-Saad — APPROVED** [review]
working as expected
[testrail-report-364.pdf](https://github.com/wp-media/wp-rocket/files/8370069/testrail-report-364.pdf)

**Comment by remyperona** [comment]
@CrochetFeve0251 You can merge the PR using "squash and merge" method. 👍🏼

**Comment by CrochetFeve0251** [comment]
@Tabrisrp just saw I forgot to merge that branch. Can I do the same with the others @Mai-Saad approuved?
