### PR TITLE
Fix problem with action scheduler

### LINKED ISSUE #4960: Improve the control over rocket_rucss_pending_jobs_cron action
**Describe the bug**
Currently, we improved the behaviour described in the https://github.com/wp-media/wp-rocket/issues/4940 based on the https://github.com/woocommerce/action-scheduler/issues/698 suggestions. However, we can improve it even further by adding a health check cron.

**Expected behavior**
We'll schedule a permanent action/cron that will check the number of `pending` or `in-progress` `rocket_rucss_pending_jobs_cron` actions:
1. 0 actions - we need to schedule it
2. 1 action - we're just fine, no further action needed
3. 1+ actions - we need to reduce it to 1

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

We had a problem with multiple actions running at the same time.
We fixed this by cancelling all running and pending action for the hook if multiple actions are launched.

Fixes #4960

## Type of change

- [ ] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [x] Tested on my testing environment

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: inc/Engine/Common/Queue/AbstractASQueue.php [hunk 1]
```diff
@@ -46,8 +48,13 @@ public function schedule_single( $timestamp, $hook, $args = [] ) {
 	 */
 	public function schedule_recurring( $timestamp, $interval_in_seconds, $hook, $args = [] ) {
 		if ( $this->is_scheduled( $hook, $args ) ) {
+			$all = $this->search( [ 'status' => [ ActionScheduler_Store::STATUS_RUNNING, ActionScheduler_Store::STATUS_PENDING ] ] );
+			if ( count( $all ) > 1 ) {
+				$this->cancel_all( $hook, $args );
+			}
```
Comment (engahmeds3ed) [inline inc/Engine/Common/Queue/AbstractASQueue.php]: Here I have some comments as follows:-
1. `search` method's second parameter is `$return_format` and its default value is `OBJECT` and we don't need those objects so I believe we can use `ids` instead so we just get the actions IDs and that's good from performance perspective.
2. You need to use Yoda condition like that
    ```if ( 1 < count( $all ) ) {```
3. Use descriptive variable names like `$scheduled_actions`
4. You need to apply the concept of `return early` instead of using nested if conditions to be like that:
```suggestion
			$scheduled_actions = $this->search( [ 'status' => [ ActionScheduler_Store::STATUS_RUNNING, ActionScheduler_Store::STATUS_PENDING ] ] );
			if ( 1 === count( $scheduled_actions ) ) {
				return '';
			}
			
			// Here means that it's greater than 1 as this is enclosed into the condition of is_scheduled.
			$this->cancel_all( $hook, $args );
			return '';
```
5. Add a new condition to the `search` method call for the group to search only for our group (Small optional enhancement)

What do u think about those points?

**Review by engahmeds3ed — CHANGES_REQUESTED** [review]

**Review by engahmeds3ed — APPROVED** [review]

**Review by engahmeds3ed — APPROVED** [review]
