### PR TITLE
#3450 Rewrite AMP Compat fixes using generic filters

### LINKED ISSUE #3450: Official AMP plugin compatibility: issues upon activation with certain options
**Describe the bug**

We've received a few reports ([like this one](https://wordpress.org/support/topic/cache-amp-plugin-which-one-is-the-best-to-work-together/)) of some potential issues when using [the AMP plugin](https://wordpress.org/plugins/amp/) with WP Rocket. In testing, the AMP plugin detects 5 instances of invalid markup being placed on AMP content upon activation and persistently with a few options enabled:

Screen Shot 2020-12-18 at 6 30 52 PM

Screen Shot 2020-12-23 at 2 50 21 PM

Since the AMP plugin automatically detects and removes the invalid markup, the AMP content remains valid. However, to [maintain compatibility](https://docs.wp-rocket.me/article/1326-amp-compatibility) and a good user experience, it would be best to prevent this from occurring. 

**To Reproduce**
1. Install and activate WP Rocket on a site using the AMP plugin
2. Go to _AMP > Validated URLs_ to see invalid markup detected and removed
3. [Recheck URLs](https://jmp.sh/DJmIfV5) to see the invalid markup for **Optimize CSS Delivery** and **Delay JS execution** resolve. 
4. Notice that invalid markup for **Preload links** remains.

**Expected behavior**

No invalid markup on AMP content and validation errors flagged by the AMP plugin.

**Screenshots**

**Options that cause invalid markup with links to screenshots**

[Preload links](https://jmp.sh/3aON5tl) (occurs upon activation and persists)

[Optimize CSS delivery](https://jmp.sh/nREtsG8) (occurs upon activation, but resolves after rechecking the URLS)

[Delay JavaScript execution](https://jmp.sh/aK3MWZr) (occurs upon activation, but resolves after rechecking the URLs)

**Additional context**

Some of these may appear in certain site setups and not others. Details of my test below: 

<details>
<summary>Site Health Info</summary>

```

### wp-core ###

version: 5.6
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/fastcms1/example.com
wordpress_size: 61.09 MB (64055503 bytes)
uploads_path: /home/fastcms1/example.com/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /home/fastcms1/example.com/wp-content/themes
themes_size: 8.27 MB (8673288 bytes)
plugins_path: /home/fastcms1/example.com/wp-content/plugins
plugins_size: 22.70 MB (23799327 bytes)
database_size: 3.53 MB (3706713 bytes)
total_size: 95.59 MB (100234831 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Twenty Twenty-One (twentytwentyone)
version: 1.1
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, title-tag, post-formats, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, custom-background, editor-color-palette, editor-gradient-presets, responsive-embeds, custom-line-height, experimental-link-color, custom-spacing, custom-units, amp, widgets
theme_path: /home/fastcms1/example.com/wp-content/themes/twentytwentyone
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.9, author: the WordPress team, Auto-updates disabled
Twenty Seventeen: version: 2.5, author: the WordPress team, Auto-updates disabled
Twenty Twenty: version: 1.6, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (2) ###

AMP: version: 2.0.9, author: AMP Project Contributors, Auto-updates disabled
WP Rocket: version: 3.8.1, author: WP Media, Auto-updates disabled

### wp-plugins-inactive (4) ###

Akismet Anti-Spam: version: 4.1.7, author: Automattic, Auto-updates disabled
All-in-One WP Migration: version: 7.32, author: ServMask, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled
Site Kit by Google: version: 1.23.0, author: Google, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
gd_version: 2.2.5
ghostscript_version: 8.70

### wp-server ###

server_architecture: Linux 2.6.32-954.3.5.lve1.4.71.el6.x86_64 x86_64
httpd_software: Apache/2.4.46 (cPanel) OpenSSL/1.1.1h mod_bwlimited/1.4 Phusion_Passenger/5.3.7
php_version: 7.4.13 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: -1
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.71.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.32-log
client_version: mysqlnd 7.4.13

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/fastcms1/example.com/wp-content
WP_PLUGIN_DIR: /home/fastcms1/example.com/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### amp_wp ###

amp_mode_enabled: transitional
amp_reader_theme: legacy
amp_templates_enabled: post, page, is_singular, is_home, is_archive, is_author, is_date, is_search, is_404, is_category, is_tag
amp_serve_all_templates: true
amp_css_transient_caching_disabled: false
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: 34
amp_css_transient_caching_time_series: 
	20201219: 0
	20201223: 14
	20201224: 34
amp_libxml_version: 2.9.4

```

</details>

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by iCaspar**
After #3508 merged, a new more direct approach came to light -- using `pre_get_rocket_option_xxx` directly in the AMP compat file rather than creating new specific filters.

Also, previous solution did not adequately cover the Optimize CSS delivery option, appearing only on activation. Therefore we add `pre_get_rocket_option_async_css` filter here as well.

### CODE REVIEW

File: inc/ThirdParty/Plugins/Optimization/AMP.php [hunk 1]
```diff
@@ -4,6 +4,7 @@
 use WP_Rocket\Admin\Options_Data;
 use WP_Rocket\Engine\CDN\Subscriber;
 use WP_Rocket\Event_Management\Subscriber_Interface;
+use function Sodium\add;
```
Comment (remyperona) [inline inc/ThirdParty/Plugins/Optimization/AMP.php]: What is this for?

Comment (iCaspar) [reply inc/ThirdParty/Plugins/Optimization/AMP.php]: lol. not sure where that came from. :/

**Review by remyperona — APPROVED** [review]

**Comment by iCaspar** [comment]
@wp-media/qa Ready for a re-check. This includes fix for the CSS Optimization at activation found during the 3.8.4 comprehensive as well. 🤞

**Review by piotrbak — APPROVED** [review]
Everything is good, no errors detected:
[testrail-report-118.pdf](https://github.com/wp-media/wp-rocket/files/5919687/testrail-report-118.pdf)
