### PR TITLE
Applies the new clean strategy to `rocket_clean_domain()`.

### LINKED ISSUE #2618: "max execution time" errors in 3.5.4 version of rocket_clean_files()
**Describe the bug**
Customers are reporting `max execution time` errors in the 3.5.4 version of `rocket_clean_files()`. 

**To Reproduce**
So far, we've not been able to reproduce the problem.

**Additional context**
In version 3.5.4, we upgraded `rocket_clean_files()` to use PHP SPL iterators instead of `glob()`. 

We are working with L2 to identify when this error occurs, it's contributors, and what may be causing it. More information will be coming as we learn more.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by hellofromtonya**
Applies the new clean strategy from PR #2623 to `rocket_clean_domain()`. 

Part of issue #2618 

The new strategy does the following:

- Only runs the wildcard/regex crawl once for each given URL domain host. 
- It stores these directories, which will be in root of `cache/wp-content/`, in memory.
     - Note: Later we will optimize this further to store in db or via mapping module.
- It then runs each URL with each of these root level cache directories without crawling the filesystem. 
     - If the URL's file/directory does not exist in the cache, it skips and goes to the next one.
     - If it's a directory, it runs `rocket_rrmdir()`.
     - Else, it's a file. It deletes it without running `rocket_rrmdir()`.

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

File: inc/functions/files.php [hunk 1]
```diff
@@ -1132,7 +1146,7 @@ function rocket_rrmdir( $dir, array $dirs_to_preserve = [], $filesystem = null )
 		if ( ! $filesystem->is_dir( $entry ) ) {
 			$filesystem->delete( $entry );
 		} else {
-			rocket_rrmdir( $entry, $dirs_to_preserve );
+			rocket_rrmdir( $entry, $dirs_to_preserve, $filesystem );
```
Comment (hellofromtonya) [inline inc/functions/files.php:1149]: Micro-optimization: on recursive calls to `rocket_rrmdir()`, `rocket_direct_filesystem()` will not have to be called over and over again.

File: inc/functions/files.php [hunk 2]
```diff
@@ -838,17 +841,18 @@ function rocket_clean_domain( $lang = '' ) {
 	 */
 	$urls = (array) apply_filters( 'rocket_clean_domain_urls', $urls, $lang );
 	$urls = array_filter( $urls );
```
Comment (engahmeds3ed) [inline inc/functions/files.php:843]: I think this is a small and maybe not effective change but wanted to highlight it.
I think looping on items to assure their values are better/faster than array_filter, I tried sample code to check and found that.
You can take this as reference: http://www.levijackson.net/are-array_-functions-faster-than-loops/

**Review by crystinutzaa — APPROVED** [review]

**Review by engahmeds3ed — APPROVED** [review]

**Comment by hellofromtonya** [comment]
@wp-media/dev-qa This PR is ready for QA. 

@piotrbak It applies the same strategy we did for `rocket_clean_files()`. 

Note: It does not fix the IIS/Windows directory separator problem; rather, that will be a separate PR.

Let me know if you have any questions.

File: inc/functions/files.php (hunk 2 above)
Comment (hellofromtonya) [reply inc/functions/files.php:843]: @engahmeds3ed I remember this article. I had issues with how the benchmarking was done, though I didn't validate his findings through proper benchmarking.

What do I mean? Why did I take issues with it?

Benchmarking requires a large statistical sample of running the code over and over again and then taking the averages. Typically, we run these samples in 10k, 100k, and/or 1m cycles. 

Why? Each time we run it, the results vary. When dealing with fractions of a second, we need a large sample set to analyze and average.

But you raise a valuable point. We need to analyze and benchmark to optimize. Let's do that as part of our Filesystem module work. Sound good?

Comment (engahmeds3ed) [reply inc/functions/files.php:843]: Sounds great.

**Review by piotrbak — APPROVED** [review]
Worked like expected, also on IIS.
