### PR TITLE
Unblur blurred urls for paid plan

### LINKED ISSUE #7718: 3.20 blurred score is still blurred after buying license
**Describe the bug**
When upgrading to paid while having a blurred score, the score is not automatically unblurred

**To Reproduce**
1. Free user, having a blurred score
2. Upgrade to paid 
3. Do the payment => redirection occur to Rocket Insights (you may need a manual refresh to see the green banner "under investigations")
4. Check blurred score in list => is still blurred 

**Expected behavior**
When redirect from success payment to Rocket Insights, blurred score should be un blurred

**Additional context**
- Related slack https://group-onecom.slack.com/archives/C08F4LZB2QG/p1758786630045019?thread_ts=1758785816.864029&cid=C08F4LZB2QG

### PR DESCRIPTION
**Pull request by wordpressfan**
# Description

Fixes #7718

Unblur blurred urls for paid plan.

## Type of change

- [x] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).
- [ ] Sub-task of #(issue number)
- [ ] Chore
- [ ] Release

### What was tested

- Install WPR freshly with free rocket insights license
- Make sure that you are out of credit
- Add a url and wait till it's completed and blurred
- Upgrade to advanced plan
- You should find this url unblurred and global score is also unblurred.

### How to test

Mentioned above.

### Documentation

N/A

### New dependencies

N/A

### Risks

N/A

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification

*If some mandatory items are not relevant, explain why in this section.*

# Additional Checks
- [ ] In the case of complex code, I wrote comments to explain it.
- [ ] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [ ] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

**Review by Miraeld — APPROVED** [review]

File: inc/Engine/Admin/PerformanceMonitoring/Database/Queries/PerformanceMonitoring.php [hunk 1]
```diff
@@ -177,4 +177,28 @@ public function prune_old_items( int $to_keep ) {
 			$this->delete_item( $id );
 		}
 	}
+
+	/**
+	 * Change blurred rows into unblurred.
+	 *
+	 * @return bool|int
+	 */
+	public function unblur_blurred_rows() {
```
Comment (remyperona) [inline inc/Engine/Admin/PerformanceMonitoring/Database/Queries/PerformanceMonitoring.php]:
```suggestion
	public function unblur_rows() {
```
I think that's enough to have a clear naming of the method. You wouldn't unblur something that isn't blurred anyway

**Review by remyperona — CHANGES_REQUESTED** [review]

**Comment by hanna-meda** [comment]
@wordpressfan, thank you for this PR.

The issue described in the ticket has been fixed. 
[Update] Finished exploring other scenarios and everything seems to be al right.
Note: If users had 0 credit when upgrading, coming back to the free plan, they might need to delete transients to see the "Re-test' buttons dimmed. (Confirmed as fine by PO)
[testrail-report-769.pdf](https://github.com/user-attachments/files/22661703/testrail-report-769.pdf)

**Review by hanna-meda — APPROVED** [review]
