### PR TITLE
Fixes #947 improve Kinsta compatibility

### LINKED ISSUE #947: Kinsta Compatibility -  The "Purge" individual URL in the admin-bar doesn't work
Brian Jackson from Kinsta noticed that the individual purge for a post doesn't also purge the Kinsta cache.

Here what he said:

_I'm wondering if perhaps this is because you didn't know the command to do this?

Clear entire site cache: /kinsta-clear-cache-all/ (this one works good already for the clear cache button on entire site)

Clear individual page cache: /kinsta-clear-cache/ (perhaps this can run for the "Purge URL" option when running on Kinsta?)

Example: https://wpdev.ink/blog-post-1/kinsta-clear-cache/
Example: https://wpdev.ink/blog-post-2/kinsta-clear-cache/_

### PR DESCRIPTION
**Pull request by Tabrisrp**
In this PR:
- Fix fatal error if Kinsta mu-plugin is not there (after a migration for example)
- Display a warning on WP Rocket settings page if the mu-plugin is not there, to ask the customer to get in touch with Kinsta about this
- Fix cache clear not working when using the "Purge this URL" link on the front-end

### CODE REVIEW

File: inc/3rd-party/hosting/kinsta.php [hunk 1]
```diff
@@ -6,78 +6,143 @@
...
+		 * @author Remy Perona
+		 *
+		 * @param object $post Post object.
+		 * @return void
+		 */
+		function rocket_clean_kinsta_post_cache( $post ) {
+			global $kinsta_cache;
+			$kinsta_cache->kinsta_cache_purge->initiate_purge( $post->ID, 'post' );
+		}
+		add_action( 'after_rocket_clean_post', 'rocket_clean_kinsta_post_cache', 10, 1 );
```
Comment (Screenfeed) [inline inc/3rd-party/hosting/kinsta.php]: `, 10, 1` is useless.

File: inc/3rd-party/hosting/kinsta.php [hunk 2]
```diff
@@ -6,78 +6,143 @@
...
+		 * @param string $root WP Rocket root cache path.
+		 * @param string $lang Current language.
+		 * @return void
+		 */
+		function rocket_clean_kinsta_cache_home( $root = '', $lang = '' ) {
+			$url = get_rocket_i18n_home_url( $lang );
+			$url = trailingslashit( $url ) . 'kinsta-clear-cache/';
+
+			wp_remote_get( $url, array(
+				'blocking' => false,
```
Comment (Screenfeed) [inline inc/3rd-party/hosting/kinsta.php]: `'timeout'  => 0.01,`

File: inc/3rd-party/hosting/kinsta.php [hunk 3]
```diff
@@ -6,78 +6,143 @@
...
+		 * @author Remy Perona
+		 *
+		 * @param string $url URL to purge.
+		 * @return void
+		 */
+		function rocket_clean_kinsta_cache_url( $url ) {
+			$url = trailingslashit( $url ) . 'kinsta-clear-cache/';
+
+			wp_remote_get( $url, array(
+				'blocking' => false,
```
Comment (Screenfeed) [inline inc/3rd-party/hosting/kinsta.php]: `'timeout'  => 0.01,`
