### PR TITLE
Fix/5645 add guard

### LINKED ISSUE #5645: Missing column on wp_wpr_rocket_cache during updates
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.3.3`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**

During plugins updates, and if navigating away from the plugins page, the website might go down and show the following error: 

```
WordPress database error Unknown column 'is_locked' in 'field list' for query INSERT INTO `wp_wpr_rocket_cache` (`url`, `status`, `modified`, `last_accessed`, `is_locked`) VALUES ('some-url', 'completed', '2022-12-20T22:23:24Z', '2022-12-20 22:23:24', '0') made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, wp_ob_end_flush_all, ob_end_flush, WP_Rocket\\Engine\\Optimization\\Buffer\\Optimization->maybe_process_buffer, do_action('rocket_after_process_buffer'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Rocket\\Engine\\Preload\\Subscriber->update_cache_row, WP_Rocket\\Engine\\Preload\\Database\\Queries\\Cache->create_or_update, WP_Rocket\\Dependencies\\Database\\Query->add_item
```

We should safeguard this:

https://github.com/wp-media/wp-rocket/blob/537d497e7d2e12ae5a5b2b0f69a6d47edd073a39/inc/Engine/Preload/Database/Queries/Cache.php#L124-L179

from doing any database update while a plugin update is ongoing. 

**To Reproduce**
Couldn't be reproduced at will. But it happened on 3 different websites.

**Expected behavior**
No issues should happen related to the Preload module while updates are ongoing, even if the user navigates away from the plugins page. 

**Screenshots**

**Additional context**
Related: 

https://secure.helpscout.net/conversation/2070564947/382216/
https://secure.helpscout.net/conversation/2070582927/382224/
https://secure.helpscout.net/conversation/2103762680/390369/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description

This pull request fixes a bug where the website goes down during plugin updates because of a missing column `is_locked` in the `wp_wpr_rocket_cache` table. 
This bug happens during plugins updates and when navigating away from the plugins page, the solution is to safeguard the function `create_or_update` in `wp-rocket/inc/Engine/Preload/Database/Queries/Cache.php`

Fixes #5645

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No, this is the solution proposed during the grooming.

## How Has This Been Tested?

- [ ] Test with automated tests.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: inc/admin/upgrader.php [hunk 1]
```diff
@@ -313,3 +313,56 @@ function rocket_new_upgrade( $wp_rocket_version, $actual_version ) {
...
+	}
+
+	$plugin = isset( $plugin['plugin'] ) ? $plugin['plugin'] : '';
+
+	if ( empty( $plugin ) || 'wp-rocket/wp-rocket.php' !== $plugin ) {
+		$msg = __( 'Missing plugin.', 'rocket' );
+		return new WP_Error( 'bad_request', $msg );
+	}
+
+	update_option( 'wp_rocket_updating', true );
```
Comment (mostafa-hisham) [inline inc/admin/upgrader.php]: @CrochetFeve0251 should we use Transient here instead of  options ?

Comment (CrochetFeve0251) [reply inc/admin/upgrader.php]: @mostafa-hisham could be a good thing

**Review by remyperona — CHANGES_REQUESTED** [review]
We could add those new funtions to the UpdaterSubscriber instead

**Review by remyperona — APPROVED** [review]

File: inc/Engine/Plugin/UpdaterSubscriber.php [hunk 2]
```diff
@@ -508,4 +511,53 @@ public function rollback_add_return_link( $update_actions ) {
...
+		if ( is_wp_error( $return ) ) { // Bypass.
+			return $return;
+		}
+
+		$plugin = isset( $plugin['plugin'] ) ? $plugin['plugin'] : '';
+
+		if ( empty( $plugin ) || 'wp-rocket/wp-rocket.php' !== $plugin ) {
+			$msg = __( 'Missing plugin.', 'rocket' );
+			return new WP_Error( 'bad_request', $msg );
+		}
```
Comment (engahmeds3ed) [inline inc/Engine/Plugin/UpdaterSubscriber.php]: [As discussed in Slack]
This will stop updating other plugins if they wish to update, plz check this code in core:
https://github.com/WordPress/wordpress-develop/blob/b60ccbdb266567a20d54357095ee0374b68169f9/src/wp-admin/includes/class-wp-upgrader.php#L483-L498
We just need to return the `$return` variable here.

**Review by engahmeds3ed — CHANGES_REQUESTED** [review]

File: inc/Engine/Plugin/UpdaterSubscriber.php (hunk 2 above)
Comment (piotrbak) [reply inc/Engine/Plugin/UpdaterSubscriber.php]: @CrochetFeve0251 @engahmeds3ed How we could move forward here?

**Review by engahmeds3ed — APPROVED** [review]

**Review by Mai-Saad — APPROVED** [review]
Couldn't reproduce it , however, Update is working fine from 3.12.2.1 and 3.12.5.3 on single site ( Apache/Nginx) / multisite
