### PR TITLE
Fix 4472 - Display notice when DelayJS is activated with Autoptimize Aggregate JS already in effect

### LINKED ISSUE #3707: Autoptimize - rocket-delay-js-js-after script and delayed scripts are being combined by Autoptimize
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✔
- Used the search feature to ensure that the bug hasn’t been reported before ✔

**Describe the bug**
When Delay JavaScript Execution and JavaScript combination feature from Autoptimize are active, the Delay JavaScript Execution Script (rocket-delay-js-js-after) and all the delayed scripts (data-rocketlazyloadscript ones) are combined and disappear from the HTML, this prevents the delayed scripts for being executed.

**To Reproduce**
1. Activate Delay JavaScript Execution on WP Rocket
2. Add a script to be delayed to the "Scripts to delay" box if needed (Example GA, GTM)
3. Activate JavaScript combination on Autoptimize (Aggregate JS-files option) and "Also aggregate inline JS" if needed.

**Expected behavior**
These scripts shouldn't be combined by Autoptimize or WP Rocket should disable Delay JavaScript execution when Aggregate JS-files option is active on Autoptimize.

**Screenshots**
image

**Additional context**
Because the delayed scripts are "Empty" (there is nothing between the <script> tags and src is not present), they are just removed from the HTML and in the combined file they do not exist, since they are in the data-rocketlazyloadscript attribute.

Excluding **_data-rocketlazyloadscript_** and **_rocket-browser-checker-js-after_** from Autoptimize solves the problem, but by the moment this should be done manually from Autoptimize UI: 
image

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### LINKED ISSUE #4472: Autoptimize aggregated JS file can't be delayed
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When Autoptimize is using their `JS, CSS & HTML` > `JavaScript Options` > `Aggregate JS-files`, WP Rocket `Delay JS` is not applied to the resulting combined file.

The combined file will be added as:

```
<script defer src="https://domain.ext/wp-content/cache/autoptimize/js/autoptimize_609b9fb609c9a893772168880e9ef32e.js">
```

Checking the buffer received before applying the Delay JS: 

[/inc/Engine/Optimization/DelayJS/Subscriber.php#L84-L86](https://github.com/wp-media/wp-rocket/blob/v3.10.2/inc/Engine/Optimization/DelayJS/Subscriber.php#L84-L86)

The combined files are not there on the HTML to process. 

https://gist.github.com/DahmaniAdame/51aa691bad4070275eb565d8dc1e3445

**To Reproduce**
1. Go to enable `Autoptimize` > `JS, CSS & HTML` > `JavaScript Options` > `Aggregate JS-files`
2. Enable WP Rocket `Delay JS` with no exclusions
3. See error

**Expected behavior**
We should either delay the resulting combined file or hint to the customer that this particular file won't be delayed.

**Screenshots**
N/A

**Additional context**

Temporary fix: disabling `Autoptimize` > `JS, CSS & HTML` > `JavaScript Options` > `Aggregate JS-files` will allow delaying all scripts.

Ticket - https://secure.helpscout.net/conversation/1681325316/304823/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by iCaspar**
## Description

Please include a summary of the change and which issue is fixed/closed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #4472
Fixes #3707 

## Type of change
- [X] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

Yes
In the grooming I had thought we would be adding a helper notice into the DelayJS selection field. In fact, we are adding a notice to the notices area at the top of the page.
Also, to do this, we had been adding the notice via the '`settings_errors` transient,  but that was failing to display messages properly. Instead, this adds a method in the DelayJS Admin/Subscriber to check if Autoptimize Aggregate JS is active, and if so, uses `add_settings_errors()` for display.

## How Has This Been Tested?

- [X] New Integration tests to confirm that the notice is added under expected conditions.
- [x] Check that notice is displayed properly on local environment.

Screen Shot 2021-11-17 at 9 32 55 AM

# Checklist:

Please delete the options that are not relevant.

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by iCaspar** [comment]
This approach should work, as the integration tests prove that notice data is added to the `settings_errors` transient array. But the notice is not appearing, due to the same bug that is causing https://github.com/wp-media/wp-rocket/issues/4314, namely there is something preventing any notice being displayed from the `settings_errors` transient when settings are updated.

Marking this as blocked by #4314.

**Review by mostafa-hisham — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@iCaspar Please find notes below based on test analysis and exploratory test:

1- If Delay JS was enabled, then we enable auto-optimize with the aggregate JS features => no warning will be displayed (we will need to re-enable delay js to see the warning), can we display the warning without needing to re-enable Delay JS (maybe with cache clear, refresh settings)?

2- When Autooptimize aggregate js files and inline js is enabled along with WPR LL video and preview image, result in removing LL videos script from HTML => Do we need a separate GH issue for that? or is it something we can handle on this PR? (same already on trunk)

3- @piotrbak  Q: Why not handle the current conflict, the same way as we do with minify/combine CSS/JS (disable the option and display red msg)?
Screenshot from 2021-11-18 12-27-13

4- Just for UI confirmation => Current msg which is displayed only when enable delay js while aggregate options are enabled in auto-optimize is as attached, is this what we need?
Screenshot from 2021-11-18 12-28-03

**Comment by piotrbak** [comment]
@Mai-Saad **When it comes to the 3:**
Minify and Combine CSS/JS are exactly the same features. It's not the case with DelayJS, as it's not causing errors, rather not working as good as it should, we decided to go with a educative warning approach.

@iCaspar Can we make the warning border yellow instead of blue?

**Comment by piotrbak** [comment]
@Mai-Saad 

**For 2:**
Does it cause any issues with the video or lazyload?

**For 4:**
We're going to display the message when:
1. Delay JS is enabled
2. Autoptimize JS Aggregation is enabled

CSS files are disabled because the CSS optimisations are enabled in the Autoptimize, below we have an explanation

**Comment by iCaspar** [comment]
@piotrbak @Mai-Saad 
On 1, please confirm that the User Story above is accurate. Per the current version of the story:
We will show the message when Autoptimize>JS Aggregation is already active and then DelayJS is activated (the behavior Mai observed). If we also want it to appear when the events happen in the reverse order (DelayJS is already active and then JSAggregation is activated) we should specify that behavior in the story. Otherwise, I think it is working as intended here.

On 2, interaction with Lazyload -- this PR is ONLY about messaging -- see the User Story. It will not include any fixes for conflicts with LazyLoad (or anything else).

On 3, see 2.

On 4, the message is (again) specified in the User Story.

**Comment by piotrbak** [comment]
@iCaspar Will it be possible to cover both scenarios? We want to display the warning in all possible use cases. The same should be applied to other Autoptimize compatibilities. Sorry for the misunderstanding.

**Comment by iCaspar** [comment]
@piotrbak No problem. Let's update the User Story and I can make that change this morning.

File: inc/ThirdParty/Plugins/Optimization/Autoptimize.php [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+
+	/**
+	 * Add an admin warning notice when Delay JS and JS Aggregation are both activated.
+	 *
+	 * @since 3.10.4
+	 */
+	public function warn_when_js_aggregation_and_delay_js_active() {
+		if ( ! rocket_get_constant( 'AUTOPTIMIZE_PLUGIN_VERSION', false ) ) {
+			return;
+		}
```
Comment (engahmeds3ed) [inline inc/ThirdParty/Plugins/Optimization/Autoptimize.php:54]: I think it would be better adding this check into `get_subscribed_events` method not to register the file events if the plugin is not installed, this will help if we added other events in the future.

**Review by remyperona — APPROVED** [review]

File: inc/ThirdParty/Plugins/Optimization/Autoptimize.php [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+		];
+	}
+
+	/**
+	 * Add an admin warning notice when Delay JS and JS Aggregation are both activated.
+	 *
+	 * @since 3.10.4
+	 */
+	public function warn_when_js_aggregation_and_delay_js_active() {
+		if ( ! rocket_get_constant( 'AUTOPTIMIZE_PLUGIN_VERSION', false ) ) {
```
Comment (engahmeds3ed) [inline inc/ThirdParty/Plugins/Optimization/Autoptimize.php:52]: `AUTOPTIMIZE_PLUGIN_VERSION` is introduced at autoptimize version 2.4.0 (3 years ago) and I think it wasn't there before, is this a problem or we are fine? @wp-media/productrocket

**Review by engahmeds3ed — CHANGES_REQUESTED** [review]
Small minor comments

File: inc/ThirdParty/Plugins/Optimization/Autoptimize.php (hunk 1 above)
Comment (iCaspar) [reply inc/ThirdParty/Plugins/Optimization/Autoptimize.php:54]: Initially, I did have it where you are suggesting. However, when `get_subscribed_events()` returns and empty array, that was what seemed to cause the failure in the `removeAllCallbacksExcept()` from detatching the other things from `admin_notices`. I think we will have to leave it here for now, until we can fix the callbacks test method.

File: inc/ThirdParty/Plugins/Optimization/Autoptimize.php (hunk 2 above)
Comment (piotrbak) [reply inc/ThirdParty/Plugins/Optimization/Autoptimize.php:52]: I think we're fine, I don't believe anyone will be using 3 years old Autoptimize + newest WP Rocket

Comment (iCaspar) [reply inc/ThirdParty/Plugins/Optimization/Autoptimize.php:52]: This is OK, per @piotrbak in slack.

**Review by engahmeds3ed — APPROVED** [review]

**Review by Mai-Saad — COMMENTED** [review]
Working as expected.

As per discussion, we agreed on the following notes:
- Notice won't be displayed after dismissing with plugin(s) reactivation (with same settings), import same settings
- Notice will be normally displayed when delay js is enabled independent of exclusions (i.e with default exclusions, notice is displayed)
- When enabling autoptimize while LL video is enabled, LL video will be automatically unchecked (this is already on the trunk and added ticket for this)
[testrail-report-311.pdf](https://github.com/wp-media/wp-rocket/files/7589642/testrail-report-311.pdf)
