### PR TITLE
Closes #107

### LINKED ISSUE #107: Improve database optimization process
Currently the process will fail if there is too much to clean. We can improve by doing it using a background process like we use for sitemap preloading

### PR DESCRIPTION
**Pull request by Tabrisrp**
Use a background process to perform the database optimization

### CODE REVIEW

File: inc/classes/class-rocket-database-optimization.php [hunk 1]
```diff
@@ -0,0 +1,264 @@
...
+	 * @see process_handler()
+	 */
+	public function optimize() {
+		if ( ! isset( $_GET['_wpnonce'] ) || ! wp_verify_nonce( $_GET['_wpnonce'], 'rocket_optimize_database' ) ) {
+			wp_nonce_ays( '' );
+		}
+
+		$this->process_handler();
+
+		wp_redirect( wp_get_referer() );
```
Comment (Screenfeed) [inline inc/classes/class-rocket-database-optimization.php]: Mode Greg-monomaniac:

    wp_safe_redirect( esc_url_raw( wp_get_referer() ) );

**Comment by Screenfeed** [comment]
Oh and you have a conflict.

File: inc/classes/class-rocket-background-database-optimization.php [hunk 2]
```diff
@@ -59,97 +59,97 @@ protected function task( $item ) {
 
 		switch ( $item ) {
 			case 'revisions':
-				$query = $wpdb->get_col( $wpdb->prepare( "SELECT ID FROM $wpdb->posts WHERE post_type = %s", 'revision' ) );
+				$query = $wpdb->get_col( "SELECT ID FROM $wpdb->posts WHERE post_type = revision" );
```
Comment (Screenfeed) [inline inc/classes/class-rocket-background-database-optimization.php]: The `'` are missing in `WHERE post_type = 'revision'`.
Same for all next queries.

File: inc/classes/class-rocket-database-optimization.php [hunk 3]
```diff
@@ -95,7 +95,7 @@ public function optimize() {
 
 		$this->process_handler();
 
-		wp_redirect( wp_get_referer() );
+		wp_redirect( esc_url_raw( wp_get_referer() ) );
```
Comment (Screenfeed) [inline inc/classes/class-rocket-database-optimization.php]: No `wp_safe_redirect()`?

File: inc/classes/class-rocket-background-database-optimization.php [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+					foreach ( $query as $id ) {
+						$number += (int) wp_delete_comment( intval( $id ), true );
+					}
+
+					$this->count[ $item ] = $number;
+				}
+				break;
+			case 'expired_transients':
+				$time = isset( $_SERVER['REQUEST_TIME'] ) ? (int) $_SERVER['REQUEST_TIME'] : time();
+				$query = $wpdb->get_col( "SELECT option_name FROM $wpdb->options WHERE option_name LIKE '_transient_timeout%' AND option_value < '$time'" );
```
Comment (Screenfeed) [inline inc/classes/class-rocket-background-database-optimization.php]: `$time` is an integer so there is no need for quotes.

File: inc/classes/class-rocket-background-database-optimization.php [hunk 5]
```diff
@@ -0,0 +1,171 @@
...
+
+					$this->count[ $item ] = $number;
+				}
+				break;
+			case 'optimize_tables':
+				$query = $wpdb->get_results( "SELECT table_name, data_free FROM information_schema.tables WHERE table_schema = '" . DB_NAME . "' and Engine <> 'InnoDB' and data_free > 0" );
+				if ( $query ) {
+					$number = 0;
+					foreach ( $query as $table ) {
+						$number += (int) $wpdb->query( "OPTIMIZE TABLE '$table->table_name'" );
```
Comment (Screenfeed) [inline inc/classes/class-rocket-background-database-optimization.php]: No quotes around the database name here (`DB_NAME`), this will trigger a SQL error.

File: inc/classes/class-rocket-database-optimization.php [hunk 6]
```diff
@@ -0,0 +1,264 @@
...
+				break;
+			case 'spam_comments':
+				$count = $wpdb->get_var( "SELECT COUNT(comment_ID) FROM $wpdb->comments WHERE comment_approved = 'spam'" );
+				break;
+			case 'trashed_comments':
+				$count = $wpdb->get_var( "SELECT COUNT(comment_ID) FROM $wpdb->comments WHERE (comment_approved = 'trash' OR comment_approved = 'post-trashed')" );
+				break;
+			case 'expired_transients':
+				$time = isset( $_SERVER['REQUEST_TIME'] ) ? (int) $_SERVER['REQUEST_TIME'] : time();
+				$count = $wpdb->get_var( "SELECT COUNT(option_name) FROM $wpdb->options WHERE option_name LIKE '_transient_timeout%' AND option_value < '$time'" );
```
Comment (Screenfeed) [inline inc/classes/class-rocket-database-optimization.php]: Same as before, `$time` is an integer so there is no need for quotes.

File: inc/classes/class-rocket-database-optimization.php [hunk 7]
```diff
@@ -0,0 +1,264 @@
...
+				break;
+			case 'all_transients':
+				$count = $wpdb->get_var( "SELECT COUNT(option_id) FROM $wpdb->options WHERE option_name LIKE '_transient_%' OR option_name LIKE '_site_transient_%'" );
+				break;
+			case 'optimize_tables':
+				$count = $wpdb->get_var( "SELECT COUNT(table_name) FROM information_schema.tables WHERE table_schema = '" . DB_NAME . "' and Engine <> 'InnoDB' and data_free > 0" );
```
Comment (Screenfeed) [inline inc/classes/class-rocket-database-optimization.php]: Same here, no quotes around the DB name.
