### PR TITLE
Fixes #3323 High CPU usage when combining CSS

### LINKED ISSUE #3323: 3.7 - High CPU usage when CSS combination is used
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

In `3.7` when CSS combination is used and there is a lot of CSS content, the CPU usage can substantially increase.
This is because contrary to what we did in `3.6.4`, where optimization was applied separately to every CSS file, in `3.7` it's applied to the combined content.

On a customer's site, where the combined CSS content was ~2.2MB, the following part takes 20-25s to complete on WP StageCoach, where no traffic exists:
https://github.com/wp-media/wp-rocket/blob/92b9036c6a7492d8790e8558ef60c8ce8b721470/inc/Dependencies/Minify/CSS.php#L311

This can cause timeouts and bring down a busy site.

**To Reproduce**

1. Use the latest WP Rocket.
2. Enable CSS combination.
3. Enqueue a few large CSS files
4. Measure the time it takes for this part to complete:
https://github.com/wp-media/wp-rocket/blob/92b9036c6a7492d8790e8558ef60c8ce8b721470/inc/Dependencies/Minify/CSS.php#L311

**Expected behavior**

The CPU usage should be affected as little as possible by our file optimization features.

**Additional context**

**Related ticket:** https://secure.helpscout.net/conversation/1327441678/208364?folderId=2135277
**Slack conversation:** https://wp-media.slack.com/archives/C43T1AYMQ/p1605710940034300

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by remyperona**
Fixes #3323 

Changes the way the content is passed to the minify library: instead of passing the whole content at once, add it in smaller data chunk, and let the library handle combining.

This should prevent the high CPU usage reported in the issue, as the library's regex will process smaller data chunks instead of one big.

### CODE REVIEW

File: tests/Fixtures/inc/Engine/License/API/UserClient/getUserData.php [hunk 1]
```diff
@@ -37,15 +37,5 @@
 		],
 		'expected' => $data,
 	],
-	'testShouldReturnDataWhenSuccess'  => [
```
Comment (crystinutzaa) [inline tests/Fixtures/inc/Engine/License/API/UserClient/getUserData.php:40]: May I ask you why this fixture is deleted? It does not seem related to the code changes you applied.

**Review by crystinutzaa — APPROVED** [review]

File: tests/Fixtures/inc/Engine/License/API/UserClient/getUserData.php (hunk 1 above)
Comment (Tabrisrp) [reply tests/Fixtures/inc/Engine/License/API/UserClient/getUserData.php:40]: the test is too fragile, because the data on the API end changes to often. I want to do it another way, but for now I'm removing it to stop it from failing our test suites every 2 days.

**Comment by Tabrisrp** [comment]
@wp-media/qa ready for QA

I guess the easiest way would be to test on client site reporting the issue, ir copying their css to do so

**Comment by piotrbak** [comment]
@Tabrisrp I checked this on the staging site of the customer, unfortunately, I don't have access to the CPU utilization statistics.

The difference in the time spent on the `execute` function is significant though:
https://github.com/wp-media/wp-rocket/blob/92b9036c6a7492d8790e8558ef60c8ce8b721470/inc/Dependencies/Minify/CSS.php#L296

Before fix:
19~ seconds

After fix:
1.5~ seconds

Should I try to create an environment where we could measure the CPU usage or that's enough and I'll just check if there's no regression in the functionality?

File: tests/Fixtures/inc/Engine/License/API/UserClient/getUserData.php (hunk 1 above)
Comment (crystinutzaa) [reply tests/Fixtures/inc/Engine/License/API/UserClient/getUserData.php:40]: Ok. Good to know. On my last PR there are a lot of failures due to "fragile" test data related to API too. 
Like expiration data on licence. Probably this one is  related too.

**Comment by Tabrisrp** [comment]
As discussed during the daily standup, we can consider the time difference enough to validate the change.

You can go ahead to check for regression 👍🏼

**Review by piotrbak — APPROVED** [review]
Worked as expected:
[testrail-report-74.pdf](https://github.com/wp-media/wp-rocket/files/5575469/testrail-report-74.pdf)
