### PR TITLE
Fixes #3332 Add missing filter parameter in get_rocket_cdn_cnames()

### LINKED ISSUE #3332: CRITICAL error when using `TM Extra Product Options` plugin
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Special Thanks to @vmanthos 

One of our customers are using the plugin `TM Extra Product Options by themeComplete` along with EWWW plugin and gets the following error

> 2020-11-16T14:54:47+00:00 CRITICAL Uncaught ArgumentCountError: Too few arguments to function WP_Rocket\Subscriber\Third_Party\Plugins\Images\Webp\EWWW_Subscriber::maybe_remove_images_cnames(), 1 passed in /home/XXX/public_html/wp-includes/class-wp-hook.php on line 287 and exactly 2 expected in /home/XXX/public_html/wp-content/plugins/wp-rocket/inc/classes/subscriber/third-party/plugins/Images/Webp/class-ewww-subscriber.php:126
> Stack trace:
> `#0` /home/XXX/public_html/wp-includes/class-wp-hook.php(287): WP_Rocket\Subscriber\Third_Party\Plugins\Images\Webp\EWWW_Subscriber->maybe_remove_images_cnames(Array)
> `#1` /home/XXX/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
> `#2` /home/XXX/public_html/wp-content/plugins/wp-rocket/inc/functions/api.php(69): apply_filters('rocket_cdn_cnam...', Array)
> `#3` /home/XXX/public_html/wp-content/plugins/woocommerce-tm-extra-product-options/include/class-tm-extra-product-options.php(1451): get_rocket_cdn_cnames(Array)
> `#4` /home/XXX/public_html/wp-includes/cl in /home/XXX/public_html/wp-content/plugins/wp-rocket/inc/classes/subscriber/third-party/plugins/Images/Webp/class-ewww-subscriber.php in Zeile 126

**To Reproduce**
1. Install TM Extra Product Options plugin
2. Install WP Rocket
3. Install EWWW plugin
4. Check error log,you will see the error

**Expected behavior**
No error.

**Screenshots**
The code from `TM Extra Product Options` plugin that triggers the issue
image

**Additional context**
When the function [get_rocket_cdn_cnames](https://github.com/wp-media/wp-rocket/blob/f83e9ea6944883824645259eaae19b23afb476ed/inc/functions/api.php#L40) is called, it will apply the filter [rocket_cdn_cnames](https://github.com/wp-media/wp-rocket/blob/f83e9ea6944883824645259eaae19b23afb476ed/inc/functions/api.php#L69) with only one argument `$hosts` but we need it to be like the following one with two argument

https://github.com/wp-media/wp-rocket/blob/28e7b00cb74df0a18b79c65631d0ba438e019db8/inc/Engine/CDN/CDN.php#L197

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by vmanthos**
## Description

This PR adds a missing filter parameter in the function `get_rocket_cdn_cnames()`.

This missing parameter created a fatal error when the above function is used in conjunction with the EWWW plugin enabled, because of our EWWW compatibility file, which requires the 2 parameters.

Fixes #3332

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: inc/functions/api.php [hunk 1]
```diff
@@ -66,7 +66,7 @@ function get_rocket_cdn_cnames( $zone = 'all' ) { // phpcs:ignore WordPress.Nami
 	 *
 	 * @param array $hosts List of CNAMES.
```
Comment (remyperona) [inline inc/functions/api.php:67]:
```suggestion
	 * @param array $hosts List of CNAMES.
	 * @param array $zone  Array of CDN zones.
```

**Review by remyperona — CHANGES_REQUESTED** [review]
One small change for the PHP Docblock to reflect the update in the code

**Review by remyperona — APPROVED** [review]

**Comment by remyperona** [comment]
@wp-media/qa Ready for QA

**Review by piotrbak — APPROVED** [review]
Worked as expected:
[testrail-report-125.pdf](https://github.com/wp-media/wp-rocket/files/5953943/testrail-report-125.pdf)
