### PR TITLE
Fixes #5747 Added referrer by default to actions

### LINKED ISSUE #5747: [Clear Cache Dashboard button] - White screen after clicking clear cache button
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
white screen appears after clicking the "clear cache button"- in the dashboard. The error appears when the header is "Referrer-Policy: no-referrer"

**To Reproduce**
For the error to appear, the header "Referrer-Policy: no-referrer" must be present
1. Go to 'wp-admin/options-general.php?page=wprocket#dashboard'
2. Click on 'Clear and preload cache'
3. See the error

**Expected behavior**
1. Go to 'wp-admin/options-general.php?page=wprocket#dashboard'
2. Click on 'Clear and preload cache'
3. The cache is cleared and the dashboard is visible 

**Screenshots**
1.  The Header is "Referrer-Policy: no-referrer" https://jmp.sh/1skSOtrG
2. Click on 'Clear and preload cache' button: https://jmp.sh/FRoWYyFw
3. White Screen appears: https://jmp.sh/mr6EL5Sl

Video provided by lucy (awesome  debugging job): https://jumpshare.com/j/5QPVMsRAH2ChG0kT12dQ

**Additional context**
This bug was tested in WPR version 3.12.4 and 3.12.5.1
The issue is resolved when you change the header to:  Referrer-Policy: strict-origin-when-cross-origin

Alfonso noticed: 

- The White page only appears when the cache is cleared from the dashboard option.

From the toolbar works ok.

- clear cache from dashboard:
https://www.domain.com/wp-admin/admin-post.php?action=purge_cache&type=all&_wpnonce=d4eee5fa26

Works ok: Clear cache from top menu
https://www.domain.com/wp-admin/admin-post.php?action=purge_cache&type=all&_wp_http_referer=%2Fwp-admin%2Foptions-general.php%3Fpage%3Dwprocket&_wpnonce=d4eee5fa26

The only difference found it's the top menu link containing the _wp_http_referer and dashboard button no. 

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
## Description
Fixed an error where the clear cache button create an error while being used with no-referrer policy.
To fix this I forced the header on button actions.

Fixes #5747 

## Type of change

Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No.

## How Has This Been Tested?

- [ ] Tested on local env

# Checklist:

Please delete the options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: inc/classes/class-abstract-render.php [hunk 1]
```diff
@@ -125,8 +125,17 @@ public function render_action_button( $type, $action, $args = [] ) {
 			case 'rocket_generate_critical_css':
 			case 'rocket_purge_rocketcdn':
 			case 'rocket_clear_usedcss':
+				if ( ! empty( $_SERVER['REQUEST_URI'] ) ) {
+					$referer = filter_var( wp_unslash( $_SERVER['REQUEST_URI'] ), FILTER_SANITIZE_URL );
+					$referer = '&_wp_http_referer=' . rawurlencode( remove_query_arg( 'fl_builder', $referer ) );
+				} else {
+					$referer = '';
+				}
```
Comment (remyperona) [inline inc/classes/class-abstract-render.php]:
```suggestion
                               $referer = '';

				if ( ! empty( $_SERVER['REQUEST_URI'] ) ) {
					$referer = filter_var( wp_unslash( $_SERVER['REQUEST_URI'] ), FILTER_SANITIZE_URL );
					$referer = '&_wp_http_referer=' . rawurlencode( remove_query_arg( 'fl_builder', $referer ) );
				}
```

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Review by Mai-Saad — APPROVED** [review]
Working as expected for Cache clear and Used CSS clear on Apache (even with no referrer header) and Nginx
