### PR TITLE
Exclude Google Site Kit files from JavaScript minification to fix JavaScript errors

### LINKED ISSUE #4656: Google Site Kit - Console errors with Minify JS files and User Cache
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**

On a customer's website with [Google Site Kit](https://wordpress.org/plugins/google-site-kit/) installed there were JavaScript errors in the admin area:
```JavaScript
TypeError: Cannot read properties of null (reading 'isGatheringData')
at Object.current (https://www.example.com/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-adminbar-2e3c962b6fd11dea95f0.js?ver=1641695747:1:111751)
at e (https://www.example.com/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-3768ea49b07e3fd1421f.js?ver=1641695747:1:190209)
at https://www.example.com/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-3768ea49b07e3fd1421f.js?ver=1641695747:1:190318
at Ui (https://www.example.com/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-3768ea49b07e3fd1421f.js?ver=1641695747:1:823227)
at va (https://www.example.com/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-3768ea49b07e3fd1421f.js?ver=1641695747:1:846154)
at t.unstable_runWithPriority (https://www.example.com/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-3768ea49b07e3fd1421f.js?ver=1641695747:1:865779)
at Mr (https://www.example.com/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-3768ea49b07e3fd1421f.js?ver=1641695747:1:790879)
at Yj (https://www.example.com/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-3768ea49b07e3fd1421f.js?ver=1641695747:1:842581)
at Lj (https://www.example.com/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-3768ea49b07e3fd1421f.js?ver=1641695747:1:832939)
at https://www.example.com/wp-content/cache/min/1/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-vendor-3768ea49b07e3fd1421f.js?ver=1641695747:1:791170
```

<details>
  <summary> Screenshot - Click to expand!</summary>
  

</details>

**User Cache** was active. The issue was caused by the **Minify JavaScript files** feature, and was resolved by excluding the following from JavaScript minification:
```
/wp-content/plugins/google-site-kit/dist/assets/js/googlesitekit-modules-(.*).js
```

There is a report of this here as well and apparently, it's happening with other optimization plugins, e.g. Autoptimize:
https://github.com/google/site-kit-wp/issues/4449

**To Reproduce**

1. Install/set up [Google Site Kit](https://wordpress.org/plugins/google-site-kit/)
2. Enable **User Cache**.
3. Enable **Minify JavaScript files**.
4. Visit a page while logged-in, and check the console for errors.

On my test site, the error was different:

**Expected behavior**

No JavaScript errors should appear in the console.

**Additional context**

I'm documenting this here to help the QA team with the PR I'm going to create with the fix.
In my tests, the errors weren't there with Defer JavaScript files and Delay JavaScript Execution active.

**Related ticket:** https://secure.helpscout.net/conversation/1751684424/318205/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by vmanthos**
## Description

I've added the following:
```
$excluded_files[] = '/google-site-kit/dist/assets/js/googlesitekit-modules-(.*).js';
```
in the `get_excluded_files()` method.

Fixes #4656 

## Type of change

Please delete options that are not relevant.

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

This wasn't groomed.

## How Has This Been Tested?

I've tested this locally by installing Google Site Kit, and checking that the JavaScript errors were resolved.

# Checklist:

Please delete the options that are not relevant.

- [x My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@vmanthos Can see it working fine with Minify JS, Defer and Delay JS. But can see this error when Combine JS
Screenshot from 2022-01-18 18-36-24
Can you please check that?

File: inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php [hunk 1]
```diff
@@ -53,6 +53,7 @@ protected function get_excluded_files() {
 		$excluded_files[] = '/interactive-3d-flipbook-powered-physics-engine/assets/js/pdf.min.js';
 		$excluded_files[] = '/interactive-3d-flipbook-powered-physics-engine/assets/js/three.min.js';
 		$excluded_files[] = '/interactive-3d-flipbook-powered-physics-engine/assets/js/3d-flip-book.min.js';
+		$excluded_files[] = '/google-site-kit/dist/assets/js/googlesitekit-modules-(.*).js';
```
Comment (aaemnnosttv) [inline inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php]: @Tabrisrp Can we please extend this to all of Site Kit's JS files? We don't load any on the front end for non-logged-in users. The pattern here is too specific as well as it would not match our runtime. See the list of all the current assets here: https://plugins.svn.wordpress.org/google-site-kit/tags/1.49.0/dist/assets/js/

I haven't tested this, but this should work assuming regular expressions are supported 🙂 

```suggestion
		$excluded_files[] = '/google-site-kit/dist/.*\.js';
```

**Comment by vmanthos** [comment]
@Mai-Saad I'm not sure the specific error you saw is related to the exclusions this PR adds. 

However, there are JavaScript errors coming from it when  **Combine JavaScript files** is active.
On my test site, the errors are specific to Google Site Kit:





The following exclusions resolved the specific errors:
```
/google-site-kit/dist/assets/js/googlesitekit-data-(.*).js
/google-site-kit/dist/assets/js/googlesitekit-widgets-(.*).js
```
I'll add these as well to the PR so you can test them.

**Comment by aaemnnosttv** [comment]
@vmanthos please see my comment on your PR for a suggestion that should match all our JS files 🙂  https://github.com/wp-media/wp-rocket/pull/4657/files#r790655067

**Comment by vmanthos** [comment]
@aaemnnosttv We usually exclude the files that are involved in generating errors/issues.

Let's see what our product team has to say about your request.

@piotrbak What do you think about excluding the whole list of Google Site Kit's files from JavaScript minification/combination?

**Comment by piotrbak** [comment]
@vmanthos Yes, I think we can exclude those, since they're only for logged-in users. By doing so, we'll be protected from potential errors in the future. Let's see if we won't have any errors during the QA.

File: inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php (hunk 1 above)
Comment (vmanthos) [reply inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php]: I've moved on with excluding all JavaScript files.

**Review by Mai-Saad — APPROVED** [review]
Working fine with Site Kit by Google 1.49.0 and 1.49.1
[testrail-report-346.pdf](https://github.com/wp-media/wp-rocket/files/7980521/testrail-report-346.pdf)
