### PR TITLE
Fix #2800 fallback cpcss css files are not loaded async

### LINKED ISSUE #2800: Fallback CPCSS - CSS files are not loaded asynchronously
Tested with WP Rocket 3.6.0.3

When using Fallback CPCSS, the CSS files are not loaded asynchronously anymore. 

**Steps to reproduce**

1. Enter CSS into Fallback CPCSS field (also take appropriate steps to apply it, delete existing cpcss, stop automatic regeneration. 
2. Observe the the CPCSS is correctly inserted into the page, but the CSS files are loaded normally and render-blocking

Related ticket: https://secure.helpscout.net/conversation/1197138109/173482?folderId=377611

### PR DESCRIPTION
**Pull request by crystinutzaa**
This was introduced while refactoring the Critical Path code. 
I identified while doing the PR https://github.com/wp-media/wp-rocket/pull/2786 .
This should be included in the next minor release v3.6.1

When using Fallback CPCSS, the CSS files are not loaded asynchronously anymore.

**Steps to reproduce**
- Enter CSS into Fallback CPCSS field (also take appropriate steps to apply it, delete existing cpcss, stop automatic regeneration.
- Observe the the CPCSS is correctly inserted into the page, but the CSS files are loaded normally and render-blocking

### CODE REVIEW

File: inc/Engine/CriticalPath/CriticalCSSSubscriber.php [hunk 1]
```diff
@@ -675,7 +675,7 @@ public function async_css( $buffer ) {
 			return $buffer;
 		}
 
-		if ( ! $this->critical_css->get_current_page_critical_css() ) {
+		if ( ! $this->critical_css->get_current_page_critical_css() && ! $this->options->get( 'critical_css', '' ) ) {
```
Comment (Tabrisrp) [inline inc/Engine/CriticalPath/CriticalCSSSubscriber.php:678]:
```suggestion
		if ( empty( $this->critical_css->get_current_page_critical_css() ) && empty( $this->options->get( 'critical_css', '' ) ) ) {
```

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Review by hellofromtonya — APPROVED** [review]

**Comment by hellofromtonya** [comment]
@arunbasillal @Davidacu This PR is ready for QA. 
🔥 We'd like to include it with the 3.6.1 release please. 🔥

**Review by arunbasillal — APPROVED** [review]
- Recreated the issue with current master branch on main mega site. Deleted CPCSS for front page and added fallback CPCSS. CSS files were loaded with `rel='stylesheet'`.
- Updated to the fix branch and repeated the test. Fallback CPCSS was used and CSS files were loaded with `rel='preload'` as expected 👍 
- CPCSS was applied correctly on other pages for which WP Rocket generated CPCSS. 👍 
- Nothing was logged in `debug.log`

Looking good 🚀
