### PR TITLE
Closes #5207 on redirect loop 

### LINKED ISSUE #5003: Respect site's trailing slash
**Describe the bug**
Closing https://github.com/wp-media/wp-rocket/issues/1392 in favour of this one, since we have  abetter view of what's needed and what risks are.

When serving the cache page using PHP, we're not respecting the `/` settings in permalinks. We should respect that and the solution will solve this problem except the scenarios when:
1. Rewrite rules are present and working
2. Server-side cache is being used

**Expected behavior**
Respect the trailing slash rules when serving cache using PHP.

**Additional context**
When serving the cache using PHP WordPress is still not loaded. It's possible that we'll need to use WP Rocket configuration file to store the data related to permalinks settings.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### LINKED ISSUE #5207: Potential redirect loop when using 3.11.4, trailing slash redirection
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version - 3.11.4
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When permalinks are set to be without `/` and website is in the subdirectory we might experience redirect loop. 

**To Reproduce**
1. Use website placed in subdirectory (could be multisite)
2. Change the permalinks to be without `/`
3. Visit frontend in incognito

**Expected behavior**
No redirect loop

**Additional context**
Still not sure if there are any other factors needed to reproduce.

**Temporary solution**
Change the permalinks settings to be with `/`

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

This PR will fix the redirect loop by redirecting with wordpress when permalink settings and url do not match.

Fixes #5207

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality)

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@jeawhanlee Thanks for the update.
Please check tabs **NGINX round 2** and **Apache** [here](https://docs.google.com/spreadsheets/d/1TPCAXKSg1fDKWN8hE0LpS37DYWkboOi3N8anFyQ5iHY/edit?usp=sharing), we will need to handle red cells. Orange cell(s) needs to be discussed with @piotrbak to see if anything is needed there. 

Notes: 
- Checking on Apache multisite with subdomain is out of scope till test env is set up.
- For enforcing/remove trailing slash plugins, we already have [bug](https://github.com/wp-media/wp-rocket/issues/5310) on the trunk which shall be fixed before checking it with the current PR

**Comment by jeawhanlee** [comment]
@Mai-Saad @piotrbak From my findings on Apache, I believe single site test cases fails after first visit of the page because the page cache is no longer served via php but `.htaccess` is at play already so the cache files are served using the rewrite rules.
- However Clearing cache from the admin or manually deleting the gzip file in the cache folder or the entire related cache folder makes the page served again via php and the redirect is triggered once again.
according to @piotrbak and @vmanthos we don't need to handle this case if `.htacess` is at work.
@Mai-Saad Can you please confirm the redirections are ok when the cache is cleared from admin. 🙏

Also for failed test cases on Muti-site with sub-folder setup for both Apache & Nginx, when this PR went through QA, Multi-site with sub-folder setup were by-passed so we don't redirect. but having removed the by-pass in the recent commits, Main site works fine but sub-sites fail, I think we might need to handle this from the area of our config file. As it is, we are not loading the corresponding config file for sub-sites of Multi-sites set up in a sub-folder as discussed with @vmanthos 

@piotrbak Can you please check the orange cells [here](https://docs.google.com/spreadsheets/d/1TPCAXKSg1fDKWN8hE0LpS37DYWkboOi3N8anFyQ5iHY/edit?usp=sharing) in the Apache tabs if we need to handle them 🙏

**Comment by piotrbak** [comment]
@jeawhanlee You can enable Separate Cache for Mobile Devices to remove rewrite rules from htaccess

**Comment by piotrbak** [comment]
@jeawhanlee Are those red cells still failing? There are lots of them 🤔

File: inc/classes/Buffer/class-cache.php [hunk 1]
```diff
@@ -669,4 +673,39 @@ private function maybe_dynamic_cookies_filename( $filename, $cookies ) {
...
+			// Check for root installation.
+			$request_uri_last_char = '/' === $request_uri ? '' : $request_uri_last_char;
+
+			// Check for subdir installation.
+			if ( '/' !== $request_uri && $php_self === $request_uri ) {
+				$request_uri_last_char = '';
+			}
+		}
+
+		return $permalink_last_char === $request_uri_last_char;
```
Comment (Kilbourne) [inline inc/classes/Buffer/class-cache.php]: Probably you should return the inverse boolean ( and remove the negation on line81) to be consistent with the function name: currently when _maybe_allow_wp_redirect_ returns true the redirect doesn't happen, while when  it returns false, it redirects

Comment (piotrbak) [reply inc/classes/Buffer/class-cache.php]: @wp-media/php What do you think about this suggestion?

Comment (jeawhanlee) [reply inc/classes/Buffer/class-cache.php]: Good Point @Kilbourne. Thanks🙏

**Review by CrochetFeve0251 — APPROVED** [review]

File: inc/classes/Buffer/class-cache.php [hunk 2]
```diff
@@ -706,6 +706,6 @@ private function maybe_allow_wp_redirect(): bool {
 			}
 		}
 
-		return $permalink_last_char === $request_uri_last_char;
+		return ! $permalink_last_char === $request_uri_last_char;
```
Comment (Kilbourne) [inline inc/classes/Buffer/class-cache.php]: Hi, here there's a bug: you are coercing $permalink_last_char to a boolean and then inverting it, instead of checking if the variables are different(`$permalink_last_char !== $request_uri_last_char;`). In current state it returns false also when the variables are different.
@jeawhanlee  @piotrbak

File: inc/classes/Buffer/class-cache.php [hunk 3]
```diff
@@ -674,8 +678,7 @@ protected function reset_lowercase( $matches ) {
 		return strtolower( $matches[0] );
 	}
 
-	/**
-	 * Sanitizes a string key.
+	/** Sanitizes a string key.
```
Comment (remyperona) [inline inc/classes/Buffer/class-cache.php]: why was this changed?

**Review by remyperona — CHANGES_REQUESTED** [review]

File: inc/classes/Buffer/class-cache.php (hunk 3 above)
Comment (jeawhanlee) [reply inc/classes/Buffer/class-cache.php]: I think that was a mistake

**Review by remyperona — APPROVED** [review]

File: inc/classes/Buffer/class-cache.php (hunk 2 above)
Comment (jeawhanlee) [reply inc/classes/Buffer/class-cache.php]: Thanks once again @Kilbourne

**Comment by vmanthos** [comment]
@jeawhanlee While doing QA we found that on multisites where:
1. the subsite is in a subdirectory `&&`
2. the permalinks there don't have a trailing `/`

caching/optimizations are not applied. This is because `maybe_allow_wp_redirect()` returns here:
https://github.com/wp-media/wp-rocket/blob/aa66a000de1602f0e1d2b1a0587c5e0d879e1276/inc/classes/Buffer/class-cache.php#L79

Logging the variables there, I got these:
```php
permalink_structure: /blog/%postname%
permalink_last_char: 
request_uri: /multisite/green/
request_uri_last_char: /
request_uri_last_char (line 719): /
```

In this scenario, `$permalink_last_char !== $request_uri_last_char` evaluates to `true`:
https://onlinephp.io?s=bcxBCoAgEEDRfdAdJggsCDxASavOIWIDVqY2aeDtq2XQ9j_4wxhMKAvOYXIRCbJPBNrPCAYJO0C3-lyVRR2QdmUXt0mrzii1UQQCGOsfIzwSPjHR8lX-8qVIzmkPze-jEgL-B21_Aw%2C%2C&v=8.1.12

Can you please look into this? 🙏 

PS: You can check this on [MEGA](https://mega.wp-rocket.me/multisite/green/).

**Comment by piotrbak** [comment]
Issue is blocked by https://github.com/wp-media/wp-rocket/issues/3477.

If we won't come up with any solution to the above, we should bypass this enhancement for multisites at all.

**Comment by jeawhanlee** [comment]
Open now as https://github.com/wp-media/wp-rocket/issues/3477 is fixed

**Review by CrochetFeve0251 — APPROVED** [review]

**Review by vmanthos — COMMENTED** [review]
This is working as expected except for one case.

On a subfolder multisite network, when the permalinks don't contain a trailing `/`, visiting the homepage of a subsite, e.g. https://mega.wp-rocket.me/multisite/green won't add a trailing `/` as it's happening when WP Rocket is not enabled.

**Comment by piotrbak** [comment]
@vmanthos We can move this issue to `QA done` then, right?

**Comment by vmanthos** [comment]
> We can move this issue to QA done then, right?

If you decide that the issue I've mentioned previously (orange cells [here](https://docs.google.com/spreadsheets/d/1TPCAXKSg1fDKWN8hE0LpS37DYWkboOi3N8anFyQ5iHY/edit?pli=1#gid=615400320)) isn't something we should fix, then yes.
