### PR TITLE
Closes #4215 Add preload fonts before cpcss and rucss

### LINKED ISSUE #4215: Add preloaded fonts before CPCSS and RUCSS to avoid FOUTs
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In some cases, the font declaration comes a bit late in the style. As a result, CSS generated by CPCSS or RUCSS will start painting the page causing a FOUT. 

The FOUT can't be avoided by using our preload fonts feature as the inline CPCSS and RUCSS will come before the preload fonts are processed by the browser. 

**To Reproduce**
1. Declare fonts at the middle of CSS file
2. Use CPCSS or RUCSS
3. See the FOUC

Make sure to use a network throttling to 3G to see the FOUT. 

**Expected behavior**
There shouldn't be any FOUT when using RUCSS or CPCSS.

A potential fix is to move font-face declarations on RUCSS and CPCSS to the beginning of the inline style. 

Another alternative is to add the `<link rel=preload>` fonts before RUCSS and CPCSS styles.

**Screenshots**
N/A

**Additional context**
Slack discussion - https://app.slack.com/client/T02RYMVKQ/C08N8J6VC/thread/C02RYMVLU-1627725766.110500
We are already doing something similar for Google Fonts when RUCSS is generated - https://github.com/wp-media/wp-rocket/issues/2772

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description
Move fonts after title.

Fixes #4215

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

Automated tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by mostafa-hisham — APPROVED** [review]

File: inc/Engine/Preload/Fonts.php [hunk 1]
```diff
@@ -96,18 +99,22 @@ public function preload_fonts() {
...
+
 		foreach ( array_unique( $fonts ) as $font ) {
-			printf(
+			$preloads .= sprintf(
 				"\n<link rel=\"preload\" as=\"font\" href=\"%s\" crossorigin>",
 				esc_url( $this->cdn->rewrite_url( $base_url . $font ) )
 			);
 		}
+
+		return str_replace( '</title>', $preloads, $html );
```
Comment (remyperona) [inline inc/Engine/Preload/Fonts.php]: it's better to use `preg_replace()` with a replacement limit of 1 in this case, to prevent inserting in unexpected cases (seen it happen before)

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@jeawhanlee The preload fonts are added after the `<style id="rocket-critical-css"></style>`. This is because the respective method is run with a priority of `10` while the `CriticalCSSSubscriber::insert_critical_css_buffer` has a priority of `19`.

Can you look into this, please?

@piotrbak Are we going to cover the case where there isn't a `</title>`? We aren't doing this currently.

**Review by remyperona — APPROVED** [review]

**Review by vmanthos — APPROVED** [review]
Working as expected! :+1:
