### PR TITLE
FIX #8205: 3.21 RI Recommendations: Recommendations will be in loading state when updating while no URL added.

### LINKED ISSUE #8205: 3.21 RI Recommendations: Recommendations will be in loading state when updating while no URL added
**Describe the bug**
Recommendations section from sidebar will be in loading state when all URLs are removed or when updating from a previous version while no URL added. 

**To Reproduce**
1. Install and activate WPR <3.21, e.g. 3.20.6.1.
2. Wait until homepage is completed then remove it from RI tab.
3. Update to WPR 3.21-alpha2.
4. Notice Recommendations section is in loading state.

**Expected behavior**
To be still decided. Maybe a "No Recommendations yet" state. More about expected under: Slack [thread](https://group-onecom.slack.com/archives/C08EFCYRQ2X/p1773904491293319).

**Screenshots**

Image

### LINKED ISSUE #8207: 3.21 RI Recommendations: Show Failed state for Recommendations when no URLs added / all URLs are removed
Show Failed state for Recommendations when no URLs added / all URLs are removed

Related: #8205 & #8206.

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #8205 #8207 
Add handling for empty recommendations state on metrics absence
Also handle 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

### What was tested

Described in respective issues

### How to test

Described in issues

### Affected Features & Quality Assurance Scope

Recommendations RI

### Documentation

This pull request improves the handling of recommendations in the Rocket Insights widget, particularly when there are no metrics available (such as after deleting all tested pages). The changes ensure that the widget displays an appropriate empty state instead of an infinite loading spinner, and that recommendations are refreshed when relevant jobs are deleted.

Handling empty recommendations and widget state:

* Added a new private method `save_empty_recommendations()` in `DataManager.php` to save a failed recommendations state when no metrics are available, preventing the widget from showing a loading spinner.
* Updated `maybe_fetch_recommendations()` in `DataManager.php` to call `save_empty_recommendations()` when required metrics are not present.

Recommendations refresh on job deletion:

* Registered a new event `rocket_rocket_insights_job_deleted` in `Subscriber.php` to trigger recommendations refresh when a job is deleted.
* Added `maybe_clear_recommendations_on_delete()` in `Subscriber.php` to update recommendations and save empty state if no metrics remain after deletion.

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

### CODE REVIEW

File: inc/Engine/Admin/RocketInsights/Recommendations/DataManager.php [hunk 1]
```diff
@@ -596,8 +596,25 @@ public function maybe_fetch_recommendations(): void {
 			return;
 		}
 
-		// Bail if metrics not ready.
+		// Get global score data to check for URLs.
+		$global_score_data = $this->global_score->get_global_score_data();
+		$status            = $global_score_data['status'] ?? 'complete';
```
Comment (jeawhanlee) [inline inc/Engine/Admin/RocketInsights/Recommendations/DataManager.php]:
```suggestion
		$status            = $global_score_data['status'];
```

File: inc/Engine/Admin/RocketInsights/Recommendations/DataManager.php [hunk 2]
```diff
@@ -596,8 +596,25 @@ public function maybe_fetch_recommendations(): void {
...
+		// There's nothing to analyze yet, so show failed state.
+		if ( 'no-url' === $status ) {
+			$this->save_empty_recommendations();
+			return;
+		}
+
+		// If tests are in progress, bail early to show loading state.
+		if ( 'in-progress' === $status ) {
+			return;
+		}
```
Comment (jeawhanlee) [inline inc/Engine/Admin/RocketInsights/Recommendations/DataManager.php]:
```suggestion
```

File: inc/Engine/Admin/RocketInsights/Recommendations/DataManager.php [hunk 3]
```diff
@@ -596,8 +596,25 @@ public function maybe_fetch_recommendations(): void {
...
+
+		// Save empty state if metrics not ready (e.g., all tests failed).
 		if ( ! $this->has_required_metrics() ) {
+			$this->save_empty_recommendations();
```
Comment (jeawhanlee) [inline inc/Engine/Admin/RocketInsights/Recommendations/DataManager.php]:
```suggestion
```

**Review by jeawhanlee — CHANGES_REQUESTED** [review]
