### PR TITLE
Closes #5351 - force preload table recreation if not exist

### LINKED ISSUE #5351: Database guard when cache table is not created
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We have one ticket related to the `cache` table not being created:
https://snippi.com/s/uqa7zrn

**To Reproduce**
We're not sure how it's possible that this error happened. We can force it to happen manually:
1. Install WP Rocket 3.12.0.x
2. Go to db manager and remove the `wpr_rocket_cache` table
3. Run the preload
4. See error in logs

**Expected behavior**
We should:
1. Make sure that preload is not running and nto adding entries in the logs
2. Try to recreate the table
3. Display the error message:
**WP Rocket:** We detected missing database table related to Preload feature. We're trying to fix this problem automatically, if you're still seeing this message after refreshing the page, please contact our support team.

**Additional context**
Similar:
https://github.com/wp-media/wp-rocket/pull/4897/files

Related ticket:
https://secure.helpscout.net/conversation/1990501756/364243

We need to check:
1. The update process with/without the cache table in previous version
2. Manual removal of the table

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description

This PR triggers recreating preload cache table if not exist.

Fixes #5351 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manual test.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

File: inc/Engine/Preload/Database/Tables/Cache.php [hunk 1]
```diff
@@ -14,6 +14,7 @@ class Cache extends Table {
 	public function __construct() {
 		parent::__construct();
 		add_action( 'rocket_preload_activation', [ $this, 'maybe_upgrade' ] );
+		add_action( 'admin_init',  [ $this, 'maybe_trigger_recreate_table' ], 9 );
```
Comment (CrochetFeve0251) [inline inc/Engine/Preload/Database/Tables/Cache.php:17]: You need to use `init` action or guard methods that use the table.

**Review by CrochetFeve0251 — CHANGES_REQUESTED** [review]

File: inc/Engine/Preload/Database/Tables/Cache.php (hunk 1 above)
Comment (jeawhanlee) [reply inc/Engine/Preload/Database/Tables/Cache.php:17]: @CrochetFeve0251 As per discussions with @engahmeds3ed, going with the `admin_init` hook over the `init` hook was due to performance and this will run before https://github.com/wp-media/wp-rocket/blob/c5028cecd905176ddae3e2d313fb9e01aa8b9352/inc/Dependencies/Database/Table.php#L876 with this accessing the frontend also recreates the table, don't know about CRON.

Do we combine this with a guard for table related methods @piotrbak  @engahmeds3ed

**Review by CrochetFeve0251 — APPROVED** [review]

**Review by piotrbak — APPROVED** [review]
Working as expected.
