### PR TITLE
Fix Cloudflare namespace compatibility with v4.14.0+

### LINKED ISSUE #7963: Cloudflare WordPress plugin update v4.14.0 triggers PHP fatal error
**Describe the bug**
Immediately after the [Cloudflare WordPress plugin](https://wordpress.org/plugins/cloudflare/#developers) update to v4.14.0, users started encountering fatal errors inside the WordPress admin whenever WP Rocket attempts to interact with Cloudflare.

```
Uncaught Error: Class "CF\WordPress\Hooks" not found
in
wp-content/plugins/wp-rocket/inc/ThirdParty/Plugins/CDN/CloudflareFacade.php:22
```

**To Reproduce**
1. Install Cloudflare WordPress plugin or update existing to v4.14.0
2. Try to do an action within WP Rocket (Clear Cache, Priority elements, Used CSS...)
3. There should be a fatal error

**Expected behavior**
It should work out of the box without triggering any errors

**Additional context**

Checking the latest update of Cloudflare WordPress plugin, there is a change of class name `CF\WordPress`

/deprecated/WordPress/Hooks/
```
<?php
namespace CF\WordPress;

/**
 * @deprecated 4.13.0 Use \Cloudflare\APO\WordPress\Hooks instead.
 */
class Hooks extends \Cloudflare\APO\WordPress\Hooks {
    public function __construct() {
        _deprecated_file( __FILE__, '4.13.0', "Cloudflare\APO\WordPress\Hooks", 'CF\WordPress namespace is deprecated, use Cloudflare\APO\WordPress instead.' );
        parent::__construct();
    }
}
```

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #7963
Fix Cloudflare namespace compatibility with v4.14.0+
- Remove hardcoded use statement for deprecated CF\WordPress\Hooks
- Add runtime class detection in set_hooks() method
- Prioritize new Cloudflare\APO\WordPress\Hooks namespace (v4.13.0+)
- Fall back to deprecated CF\WordPress\Hooks for backward compatibility
- Add null checks in purge_everything() and purge_urls() methods
- Change hooks property type from Hooks to object for flexibility

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

### What was tested

Refer to issue

### How to test

Refer to issue

### Affected Features & Quality Assurance Scope

CloudFare Thirdparty

### Documentation

This pull request updates the `CloudflareFacade` integration to ensure compatibility with both the latest and older versions of the Cloudflare WordPress plugin. The main changes focus on supporting a new class namespace introduced in Cloudflare plugin v4.13.0+, while maintaining backward compatibility and improving error handling if neither class is found.

**Cloudflare plugin compatibility improvements:**

* Updated the `set_hooks()` method in `CloudflareFacade` to prioritize the new `\Cloudflare\APO\WordPress\Hooks` namespace (Cloudflare plugin v4.13.0+) and fall back to the old `\CF\WordPress\Hooks` namespace for earlier versions. If neither class exists, `$hooks` remains `null`.
* Changed the type annotation for `$hooks` from `null|Hooks` to `null|object` to accommodate both possible hook classes.

**Error handling improvements:**

* Added checks in both `purge_everything()` and `purge_urls()` to ensure that if `$hooks` is `null` (i.e., neither supported Cloudflare class exists), the methods return early and do not attempt to call methods on a non-existent object. [[1]](diffhunk://#diff-1962d986a7afa28e9b61edb4b2bf82489e949c8ce1752ca5add7f205b55d53bdR45-R48) [[2]](diffhunk://#diff-1962d986a7afa28e9b61edb4b2bf82489e949c8ce1752ca5add7f205b55d53bdR64-R67)

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

### CODE REVIEW

File: inc/ThirdParty/Plugins/CDN/CloudflareFacade.php [hunk 1]
```diff
@@ -19,7 +17,19 @@ class CloudflareFacade {
...
+		// Prioritize new namespace (Cloudflare plugin v4.13.0+).
+		if ( class_exists( '\\Cloudflare\\APO\\WordPress\\Hooks' ) ) {
+			$this->hooks = new \Cloudflare\APO\WordPress\Hooks();
+			return;
+		}
+
+		// Fall back to old namespace (Cloudflare plugin < v4.14.0).
+		if ( class_exists( '\\CF\\WordPress\\Hooks' ) ) {
+			$this->hooks = new \CF\WordPress\Hooks();
+			return;
```
Comment (wordpressfan) [inline inc/ThirdParty/Plugins/CDN/CloudflareFacade.php]: No need for this return, because there is no code below this line.

**Review by wordpressfan — CHANGES_REQUESTED** [review]

**Comment by hanna-meda** [comment]
Thank you @Miraeld for this PR.

QA done, everything looks good.

Testing:
- Verified fix against Cloudflare 4.14.0, 4.13.0, 4.14.1, 4.14.2.
- Confirmed no fatal errors with Cloudflare missing or deactivated.
- Validated clear cache, purge this URL, and clear priority elements across old/new namespaces (4.13.x vs 4.14.x).
- Ran E2E smoke, all passed.

**Review by hanna-meda — APPROVED** [review]
