### PR TITLE
Fixes #4804 Use absint values for width/height values when setting image dimensions of SVG files

### LINKED ISSUE #1804: Proposal: Minify our Lazyload Inline JS script
We have requests from customer who wants us to minify our LazyLoad Inline JS script.

We had 4 tickets about just for this week, here an example
- https://secure.helpscout.net/conversation/883475838/112994?folderId=343175

### LINKED ISSUE #4804: Decimals displayed as width and height values with "Add Missing Image Dimensions" option
**Describe the bug**

From v3.10.8 I have errors from [W3C validator](https://validator.w3.org/nu/) because of bad value (decimals) in width and height attributes of SVG elements loaded in ``tag when WP-Rocket "Add Missing Image Dimensions" option is enabled.

**To Reproduce**

1. Add into a page a SVG with decimals in viewBox
2. Enable Rocket "Add Missing Image Dimensions" option
3. Check your DOM or test it with W3C validator : https://validator.w3.org/
4. See `Bad value for attribute width on element img` errors

**Expected behavior**
Integer values for width and height image sizes. 

**Screenshots**
w3c

The values seems to come from SVG source file: `viewBox="0 0 160.27708 108.89794"`.

**Additional context**
Related with #3727

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by Klemart3D**
## Description

Display integers as width and height values for SVG (instead of decimals) to prevent errors.

Fixes #4804

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

Please describe in this section if there is any change to the solution, and why.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Load a SVG with decimals in viewBox and check DOM if width and height values are converted to integers (needs "Add Missing Image Dimensions" option enabled)

# Checklist:

Please delete the options that are not relevant.

### CODE REVIEW

File: inc/Engine/Media/ImageDimensions/ImageDimensions.php [hunk 1]
```diff
@@ -506,7 +506,7 @@ private function svg_getimagesize( string $filename ) {
 			$size[0] = $width;
 			$size[1] = $height;
 			$size[2] = 0;
-			$size[3] = 'width="' . $width . '" height="' . $height . '"';
+			$size[3] = 'width="' . absint($width) . '" height="' . absint($height) . '"';
```
Comment (remyperona) [inline inc/Engine/Media/ImageDimensions/ImageDimensions.php]:
```suggestion
			$size[3] = 'width="' . absint( $width ) . '" height="' . absint( $height ) . '"';
```

File: inc/Engine/Media/ImageDimensions/ImageDimensions.php [hunk 2]
```diff
@@ -522,7 +522,7 @@ private function svg_getimagesize( string $filename ) {
 				$size[0] = $view_box[2];
 				$size[1] = $view_box[3];
 				$size[2] = 0;
-				$size[3] = 'width="' . $size[0] . '" height="' . $size[1] . '"';
+				$size[3] = 'width="' . absint($size[0]) . '" height="' . absint($size[1]) . '"';
```
Comment (remyperona) [inline inc/Engine/Media/ImageDimensions/ImageDimensions.php]:
```suggestion
				$size[3] = 'width="' . absint( $size[0] ) . '" height="' . absint( $size[1] ) . '"';
```

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Comment by remyperona** [comment]
Thank you for the PR @Klemart3D,

After going through our QA process, it will be added in one of our next releases.

**Review by Mai-Saad — APPROVED** [review]
Working as expected with decimal/integer SVG dimensions/viewport internal/external and inside pic Elem.

**Review by Mai-Saad — APPROVED** [review]
