### PR TITLE
disable preload for pagination URLs

### LINKED ISSUE #5544: Preload - disable preload for pagination pages by default
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Pagination pages will be added to the `wpr_rocket_cache` table, and since WordPress allows accessing "fake" pagination pages like these: http://mega.wp-rocket.me/cf-7/page/124 it might be problematic on some sites.
 
**To Reproduce**
1. Go to http://mega.wp-rocket.me/cf-7/page/124
2. change the page number several times  `/page/127`, `/page/245, etc`
4. See all these unexistent pages being added to the `wpr_rocket_cache` table

**Expected behavior**
We should exclude these pagination pages from preload by default

**Screenshots**
vjw36yT-1
Full image here:  https://i.imgur.com/vjw36yT.png

On some sites, this might become quite problematic: 
https://i.imgur.com/veLGv6U.png

**Additional context**
ticket: 
https://secure.helpscout.net/conversation/2029385423/373136?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by mostafa-hisham**
## Description

disable add pagination URLs in `wpr_rocket_cache` table
Fixes #5544 

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

No
## How Has This Been Tested?
- [x] local envoinment
- [x] unit and integration tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by CrochetFeve0251 — APPROVED** [review]

File: inc/Engine/Preload/Controller/CheckExcludedTrait.php [hunk 1]
```diff
@@ -28,7 +28,9 @@ protected function is_excluded_by_filter( string $url ): bool {
 		 *
 		 * @param string[] regexes to check
 		 */
-		$regexes = (array) apply_filters( 'rocket_preload_exclude_urls', [] );
+		global $wp_rewrite;
+		$pagination_regex = "/$wp_rewrite->pagination_base/\d+";
+		$regexes          = (array) apply_filters( 'rocket_preload_exclude_urls', [ $pagination_regex ] );
```
Comment (remyperona) [inline inc/Engine/Preload/Controller/CheckExcludedTrait.php]: The docblock for the filter should be placed correctly next to the filter function usage

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Review by vmanthos — COMMENTED** [review]
This is working as expected. :+1: 

In the following cases:
1. There is a post or page whose slug is matching the pagination base, e.g. `https://example.com/page/`.
2. The user has changed the default category/tag base and that matches the pagination base.

we are going to prevent the preloading of all the URLs that include `/page/`.

@piotrbak These are edge cases.  Should we address them in this PR or monitor them, and if any come up act on this?

**Comment by piotrbak** [comment]
@vmanthos Let's monitor them and make decision based on that. It'll be possible to redo this change with filter for edge cases and specifc use cases

**Review by vmanthos — APPROVED** [review]
