### PR TITLE
Fixes #545

### LINKED ISSUE #545: Google fonts regex matches more than it should
In some cases the regex for google fonts concatenation is matching with incorrect content, causing the HTML to break

### PR DESCRIPTION
**Pull request by Tabrisrp**

### CODE REVIEW

File: inc/front/minify.php [hunk 1]
```diff
@@ -139,7 +139,7 @@ function rocket_insert_minify_js_in_footer() {
 function rocket_concatenate_google_fonts( $buffer ) {
 	// Get all Google Fonts CSS files.
 	$buffer_without_comments = preg_replace( '/<!--(.*)-->/Uis', '', $buffer );
-	preg_match_all( '/<link(?:\s.+)?\shref\s*=\s*(\'|")((?!\1).+fonts\.googleapis\.com(?!\1).+)\1(?:\s.*)?>/iU', $buffer_without_comments, $matches );
+	preg_match_all( '/<link(?:\s+(?:(?!href\s*=\s*)[^>])+)?(?:\s+href\s*=\s*([\'"])((?:https?:)?\/\/fonts\.googleapis\.com\/css(?:(?!\1).)+)\1)(?:\s+[^>]*)?>/iU', $buffer_without_comments, $matches );
```
Comment (Screenfeed) [inline inc/front/minify.php]: Is it the pattern I gave you few days ago? It looks like anyway.

Comment (Tabrisrp) [reply inc/front/minify.php]: yes it is
