### PR TITLE
Closes #5674 Cancel AS preload pending jobs after truncating cache table

### LINKED ISSUE #5674: Cancel AS preload pending jobs after truncating cache table
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 3.12.4
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We are not canceling AS pending jobs with actions that truncate the Cache table i.e change permalinks

**To Reproduce**
Precondition:
- Set preload batch size to 300 for example to notice the problem
```
add_filter( 'rocket_preload_cache_pending_jobs_cron_rows_count', function( $urls ){
return 300;
} );
```

1. Enable preload on large site => many preload pending jobs are there in the actions table
2. Clear and preload the cache
3. Use a custom sitemap
```
function add_my_sitemap() {
return ['https://new.rocketlabsqa.ovh/wp-content/rocket-test-data/files/custom-sitemap.xml'];
}
```
add_filter( 'rocket_sitemap_preload_list', 'add_my_sitemap', PHP_INT_MAX );
6. change permalinks
7. check the cache table and AS actions table => URLs of pending AS are added once completed with completed status

**Expected behavior**
Cancel AS preload pending jobs when truncating the cache table

**Screenshots**

https://user-images.githubusercontent.com/76941962/211803860-18216d0e-22f7-4751-afa7-636949635c2d.mp4

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by jeawhanlee**
## Description
Cancel pending AS preload pending jobs after truncating cache table.

Fixes #5674 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Is the solution different from the one proposed during the grooming?

No

## How Has This Been Tested?

Automated Tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: tests/Unit/inc/Engine/Preload/Subscriber/onPermalinkChanged.php [hunk 1]
```diff
@@ -33,13 +33,14 @@ protected function setUp(): void
 		$this->activation = Mockery::mock(Activation::class);
 		$this->mobile_detect = Mockery::mock(WP_Rocket_Mobile_Detect::class);
 		$this->clear_cache = Mockery::mock(ClearCache::class);
-		$this->queue = Mockery::mock(Queue::class);
```
Comment (CrochetFeve0251) [inline tests/Unit/inc/Engine/Preload/Subscriber/onPermalinkChanged.php]: @jeawhanlee why did you used `$this->createMock` instead of Mockery?
I started using `$this->createMock` as last option to fix an issue with Query classes. Otherwise by convention we use Mockery as mocking library.

Comment (jeawhanlee) [reply tests/Unit/inc/Engine/Preload/Subscriber/onPermalinkChanged.php]: I was having issues mocking methods in the `queue` class, so using `$this->createMock` solved the issue.

**Review by CrochetFeve0251 — APPROVED** [review]

**Review by vmanthos — APPROVED** [review]
This is working as expected! :+1:
