### PR TITLE
Closes #288

### LINKED ISSUE #288: Add filters to remove query string and static file creation
It's needed to be able to exclude files from those as it causes issues with some particular themes/plugins using wp_enqueue_style() or wp_enqueue_script() in unexpected ways.

### PR DESCRIPTION
**Pull request by Tabrisrp**
Add filters to cache busting and static dynamic resources to excludefiles from the process

### CODE REVIEW

File: inc/front/enqueue.php [hunk 1]
```diff
@@ -33,6 +33,13 @@ function rocket_browser_cache_busting( $src, $current_filter = '' ) {
     if ( false === strpos( $src, '.css' ) && false === strpos( $src, '.js' ) ) {
         return $src;
     }
+
+	$excluded_files = apply_filters(  'rocket_exclude_cache_busting', array() );
```
Comment (GeekPress) [inline inc/front/enqueue.php]: Add filter comment here

File: inc/front/enqueue.php [hunk 2]
```diff
@@ -142,6 +149,13 @@ function rocket_cache_dynamic_resource( $src ) {
         return $src;
     }
 
+	$excluded_files = apply_filters(  'rocket_exclude_static_dynamic_resources', array( '/wp-admin/admin-ajax.php' ) );
```
Comment (GeekPress) [inline inc/front/enqueue.php]: Add filter comment here too :)
