### PR TITLE
Fix wrong metrics

### LINKED ISSUE #8188: Wrong recommendations and labeling for recommended features
**Describe the bug**
Example: 

Score communicated to API: 
```
LCP: 3.3s
TBT: 5ms
CLS: 0.000
TTFB: 839ms
Global: 66
```

[API is response was](https://saas.wp-rocket.me/recommendations/?email=test%40example.com&lcp=3.3&ttfb=0.839&cls=0&tbt=0.005&global_score=66&enabled_options=lazyload_images&language=en&limit=5&version=3.20.4)

```
{
            "option_slug": "remove_unused_css",
            "priority": 100,
            "title": "Remove unused CSS",
            "description": "Improve how quickly the page appears by removing unused CSS and reducing stylesheet size.",
            "learn_more_url": null,
            "icon_slug": null,
            "lcp_impact": 50,
            "ttfb_impact": 0,
            "cls_impact": 20,
            "tbt_impact": 0
        },
        {
            "option_slug": "defer_all_js",
            "priority": 100,
            "title": "Load JavaScript deferred",
            "description": "Improve page loading by downloading JavaScript in parallel and executing it only after the HTML is fully loaded.",
            "learn_more_url": null,
            "icon_slug": null,
            "lcp_impact": 30,
            "ttfb_impact": 0,
            "cls_impact": 0,
            "tbt_impact": 30
        },
        {
            "option_slug": "lazyload_css_bg_img",
            "priority": 100,
            "title": "Lazy load CSS background images",
            "description": "Reduce the amount of data loaded initially by delaying CSS background images until they appear on the screen.",
            "learn_more_url": null,
            "icon_slug": null,
            "lcp_impact": 30,
            "ttfb_impact": 0,
            "cls_impact": 0,
            "tbt_impact": 0
        },
        {
            "option_slug": "lazyload",
            "priority": 100,
            "title": "Lazyload images",
            "description": "Reduce initial page size by delaying images that are not yet visible so the content visible on screen loads first.",
            "learn_more_url": null,
            "icon_slug": null,
            "lcp_impact": 30,
            "ttfb_impact": 0,
            "cls_impact": 0,
            "tbt_impact": 0
        },
        {
            "option_slug": "manual_preload",
            "priority": 100,
            "title": "Preload Cache",
            "description": "Make pages available instantly on the first visit by generating cached versions before users visit them.",
            "learn_more_url": null,
            "icon_slug": null,
            "lcp_impact": 30,
            "ttfb_impact": 40,
            "cls_impact": 0,
            "tbt_impact": 0
        }
```

And plugin showed: 

Image

- Plugin didn't match the order or the recommendations provided by API
- Plugin didn't label correctly web vitals impact for each feature

**To Reproduce**

**Expected behavior**
- We should match API's recommendation items and order
- Each feature needs to have vitals impact correct

**Additional context**
[Slack](https://group-onecom.slack.com/archives/C0AF91DUS9Z/p1773827715602659?thread_ts=1773816265.278549&cid=C0AF91DUS9Z)

Website affected is included on the Slack convo.

### PR DESCRIPTION
**Pull request by wordpressfan**
# Description

Fixes #8188

Here we fix two issues:
1. Show correct tags in each recommendations, we were showing all tags (Impact on:), but now we show the correct effect.
2. Send the average advanced indicators in a correct way to get the correct results.

## Type of change

- [ ] New feature (non-breaking change which adds functionality).
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).
- [ ] Sub-task of #(issue number)
- [ ] Chore
- [ ] Release

### What was tested

Check the issue, u will find some numbers, I validated the numbers on Adame's website which has the issue.

### How to test

Everything is in the issue.

### Affected Features & Quality Assurance Scope

Recommendations

### Documentation

N/A

### New dependencies

N/A

### Risks

N/A

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style

- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

## Unticked items justification

*If some mandatory items are not relevant, explain why in this section.*

# Additional Checks
- [ ] In the case of complex code, I wrote comments to explain it.
- [ ] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [ ] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

**Review by jeawhanlee — CHANGES_REQUESTED** [review]
2 small changes, other than that LGTM 🙌

File: inc/Engine/Admin/RocketInsights/Recommendations/DataManager.php [hunk 1]
```diff
@@ -272,6 +271,36 @@ public function fetch_recommendations( array $options = [] ): bool {
...
+	 * Prepare average metrics for API parameters.
+	 *
+	 * @return array
+	 */
+	private function prepare_metrics_to_api(): array {
+		$params = [];
+
+		// Get average metrics from global score data.
+		$average_metrics = $this->get_average_metrics( false );
+		if ( empty( $average_metrics ) || ! is_array( $average_metrics ) ) {
```
Comment (jeawhanlee) [inline inc/Engine/Admin/RocketInsights/Recommendations/DataManager.php]:
```suggestion
		if (  ! is_array( $average_metrics ) || empty( $average_metrics ) ) {
```

File: inc/Engine/Admin/RocketInsights/Recommendations/DataManager.php [hunk 2]
```diff
@@ -428,20 +457,26 @@ private function calculate_metrics_hash(): string {
 	/**
 	 * Get average metrics from global score data (from Task 1.1).
```
Comment (jeawhanlee) [inline inc/Engine/Admin/RocketInsights/Recommendations/DataManager.php]:
```suggestion
	 * Get average metrics from global score data.
```

**Review by jeawhanlee — CHANGES_REQUESTED** [review]
