### PR TITLE
Fixes #2383: Conflict between WP Rocket mobile preload and wp_is_mobile()

### LINKED ISSUE #2383: Conflict between WP Rocket mobile preload and wp_is_mobile()
**Describe the bug**
WP Rocket uses `iPhone` in its user agent for mobile preload requests, but `wp_is_mobile()` doesn't use this string in its detection, so `wp_is_mobile()` will serve desktop content to preloaded mobile pages.

**To Reproduce**
- Activate separate cache for mobile device
- Activate preloading
- Have a theme/plugin that uses `wp_is_mobile()`
- The preloaded mobile page will contain for desktop output instead of for mobile output

**Expected behavior**
Mobile preload should be compatible with `wp_is_mobile()` and preloaded mobile pages should have the appropriate content

### PR DESCRIPTION
**Pull request by Screenfeed**
Make the user agent used to preload mobile pages detected as mobile by `wp_is_mobile()`.
We use now a more complex user agent, closer to a real one, that uses `iPhone` (for WPR mobile detect) and `Mobile` (for `wp_is_mobile()`).
Also, this new string is prepended to the custom user agent instead of being happened.

Fixes #2383.

### CODE REVIEW

File: tests/Integration/inc/classes/preload/Full_Process/getItemUserAgent.php [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+
+	public function testShouldNotBeDetectedAsMobileByWordPressWhenNotMobileItem() {
+		$previous_ua                = ! empty( $_SERVER['HTTP_USER_AGENT'] ) ? $_SERVER['HTTP_USER_AGENT'] : null;
+		$_SERVER['HTTP_USER_AGENT'] = $this->process->get_item_user_agent( [ 'mobile' => 0 ] );
+
+		$this->assertFalse( wp_is_mobile() );
+
+		$_SERVER['HTTP_USER_AGENT'] = $previous_ua;
+	}
+}
```
Comment (hellofromtonya) [inline tests/Integration/inc/classes/preload/Full_Process/getItemUserAgent.php]: Great job testing these scenarios @Screenfeed 👍

**Comment by arunbasillal** [comment]
I tested this with Uncode theme between current `master` and `develop` branches. 

- I was able to replicate the issue with 3.5.0.1 (master branch)
- Switching to the current develop branch fixes the issue
- You can see it documented here: https://youtu.be/wZpZCagjISg

All good 👍
