### PR TITLE
Closes #2561 Combine Google Fonts and JetMenu incompatibility

### LINKED ISSUE #2561: Combine Google Fonts breaks JetMenu data-menu-options
**Before submitting an issue please check that you’ve completed the following steps:**
- Tested with WP Rocket 3.5.2 and JetMenu Version 2.0.3

**Describe the bug**
When a Google font is used in **Jetmenu** settings, and **Combine Google Fonts** is enabled at WP Rocket, JetMenu will add its own google font tag. If the theme already has another google font tag, the combined file will get injected twice at the HTML, the usual injection and another one inside JetMenu _data-menu-options_ object, breaking the menu functionality.

**To Reproduce**
1. Go to JetMenu settings
2. Choose a Google Font
3. Enable Combine Google Fonts
4. The menu won't work anymore.

**To Reproduce (if you don't have a copy of JetMenu)**
1. Add these font tags to the head: http://snippi.com/s/g2eavfz
2. Add this menu markup to the body: http://snippi.com/s/xk7sha8
3. Enable Combine Google Fonts
4. The menu markup will be rewritten, including the Combined Google Font link.

**Expected behavior**
Enabling Combine Google Fonts shouldn't break the menu functionality

**Screenshots**
Screenshot at abr  21 09-00-39

**Additional Information**
Related HS Ticket: https://secure.helpscout.net/conversation/1141442668/159225?folderId=2683093

**Backlog Grooming (for WP Media dev team use only)**
- [x] Reproduce the problem
- [x] Identify the root cause
- [x] Scope a solution
- [x] Estimate the effort

### PR DESCRIPTION
**Pull request by crystinutzaa**
When a Google font is used in Jetmenu settings, and Combine Google Fonts is enabled at WP Rocket, JetMenu will add its own google font tag. If the theme already has another google font tag, the combined file will get injected twice at the HTML, the usual injection and another one inside JetMenu data-menu-options object, breaking the menu functionality.

**Reproduce the issue** ✅ 
Identified this issue on localhost.

**Identify the root cause** ✅ 
The root cause is that JetMenu contains SVG which contains `<title></title>` and Google Fonts is appended after `</title>` in here:
https://github.com/wp-media/wp-rocket/blob/57003cff362df710d36acb49085115ea4d09e0eb/inc/Engine/Optimization/GoogleFonts/Combine.php#L79

**Scope a solution** ✅ 
I would go on targeting with regex </title> withing <head></head>.

**Effort** ✅ 
Effort `[S]`

### CODE REVIEW

File: inc/Engine/Optimization/GoogleFonts/Combine.php [hunk 1]
```diff
@@ -76,7 +76,11 @@ public function optimize( $html ) {
 			return $html;
 		}
 
-		$html = str_replace( '</title>', '</title>' . $this->get_combine_tag(), $html );
+		$head_html = preg_match( '/<head[^>]*>(.*?)<\/head>/umsi', $html, $matches );
+		if ( $head_html ) {
+			$new_head = preg_replace( '/<\/title>/', '</title>' . $this->get_combine_tag(), $matches[0], 1 );
+			$html     = str_replace( $matches[0], $new_head, $html );
+		}
```
Comment (Tabrisrp) [inline inc/Engine/Optimization/GoogleFonts/Combine.php:83]:
```suggestion
		$html = preg_replace( '/(<head[^>]*>(?:.*)<title>(?:.*))(<\/title>)((?:.*)<\/head>)/', '$1$2' . $this->get_combine_tag() . '$3', $html, 1 );
```

@Screenfeed Always looking for your double-check on regEx 🙏

Comment (Screenfeed) [inline inc/Engine/Optimization/GoogleFonts/Combine.php:83]: @Tabrisrp Challenge accepted.

```suggestion
		$html = preg_replace( '@(<head[^>]*>.*<title[^>]*>.*</title>)(.*</head>)@isU', '$1' . $this->get_combine_tag() . '$2', $html, 1 );
```

[Test](https://regex101.com/r/MfusIp/1).

**Comment by hellofromtonya** [comment]
@wp-media/dev-qa This PR is ready for QA.
