### PR TITLE
Divi compatibility: show admin notice to clear the used CSS when a template is updated

### LINKED ISSUE #5837: Clear Used CSS when Divi saves template item
**Before submitting an issue please check that you’ve completed the following steps:**
- [x] Made sure you’re on the latest version `3.12.6.1`
- [x] Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Divi has a template builder feature where the header, body, and footer can be set globally or under specific conditions. 

If one of them is changed, we are not triggering the Used CSS clearing. This results in whatever was changed to have their style missing.

Divi stores them on specific post types: 

```
et_footer_layout
et_body_layout
et_header_layout
```

All posts linked to a specific header, body, or footer will be documented on a customer field called, respectively, `_et_header_layout_id`, `_et_body_layout_id`, `_et_footer_layout_id`.

We can track `et_save_post`, check if one of the specific post types is being saved, and then fire the following for any post with the corresponding custom field to have its Used CSS cleared, which should also clear the cache. 

`et_save_post` takes the `$post_id` as a parameter. 

The custom field to target can be built using: 

```
'_' . get_post_type( $post_id ) . '_id'
```

With an SQL command that uses that specific custom field to get the matching posts to be processed. 

**To Reproduce**
1. Set a global/custom header, body, or footer
2. Generate Used CSS
3. Change the global/custom header, body, or footer by adding a new element with a specific style
4. Clear the cache
5. See that the style of the changed item is missing

**Expected behavior**
We should clear the Used CSS when items from Divi's Theme Builder change. 

**Screenshots**
N/A

**Additional context**
Ticket - https://secure.helpscout.net/conversation/2184716932/408393/

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

### PR DESCRIPTION
**Pull request by engahmeds3ed**
## Description

Show admin notice to clear the used CSS when a template is updated only when this template is used in any (page, post, tag, ...etc.)

Also added a new filter `` to enable/disable this functionality.

Fixes #5837

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality)

## Is the solution different from the one proposed during the grooming?

Yes it's changed a bit, you can check the discussion in the issue itself for more details.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested on mega site

# Checklist:

Please delete the options that are not relevant.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: inc/ThirdParty/Themes/Divi.php [hunk 1]
```diff
@@ -214,4 +218,109 @@ public function disable_dynamic_css_on_rucss() {
...
+	 * @return void
+	 */
+	public function handle_save_template( $template_post_id ) {
+		/**
+		 * Filters Bypassing saving template functionality.
+		 *
+		 * @param bool $bypass Bypass save template functionality.
+		 * @param int  $template_post_id Currently saved template post id.
+		 */
+		if ( apply_filters( 'rocket_divi_bypass_save_template', empty( $layout_post_ids ), $template_post_id ) ) {
```
Comment (remyperona) [inline inc/ThirdParty/Themes/Divi.php]: `empty( $layout_post_ids )`, I don't understand that part, the variable doesn't exist yet?

File: inc/ThirdParty/Themes/Divi.php [hunk 2]
```diff
@@ -214,4 +218,109 @@ public function disable_dynamic_css_on_rucss() {
...
+			return;
+		}
+	}
+
+	/**
+	 * Admin notices handler.
+	 *
+	 * @return void
+	 */
+	public function handle_divi_admin_notice() {
```
Comment (remyperona) [inline inc/ThirdParty/Themes/Divi.php:322]: Aren't we missing a check for RUCSS enabled?

Also, the notice will be displayed again if reloading the page, since the transient is not deleted until `rocket_after_clean_used_css`

**Review by remyperona — CHANGES_REQUESTED** [review]
No unit/integration tests?

File: inc/ThirdParty/Themes/Divi.php (hunk 1 above)
Comment (engahmeds3ed) [reply inc/ThirdParty/Themes/Divi.php]: Sorry I added the default value for the filter then realized that we need the filter to run before the query as in big sites we may have issue with such query so it'll be easy to have a helper plugin to stop the whole feature so moved it above, fixed it now to have the default value to false.

File: inc/ThirdParty/Themes/Divi.php (hunk 2 above)
Comment (engahmeds3ed) [reply inc/ThirdParty/Themes/Divi.php:322]: > Aren't we missing a check for RUCSS enabled?

Oh, sorry, did that now.

> Also, the notice will be displayed again if reloading the page, since the transient is not deleted until rocket_after_clean_used_css

This is not the case here, I named the box with my transient name so when clicking on the dismiss button it will delete the transient here:

https://github.com/wp-media/wp-rocket/blob/205e2b28b3351163b0ca546906ac9c9d9b628cb0/inc/functions/admin.php#L91

**Comment by engahmeds3ed** [comment]
I forgot the tests, we have two public methods, going to add the tests for them now.

File: tests/Unit/inc/ThirdParty/Themes/Divi/handleSaveTemplate.php [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+	}
+
+	protected function tearDown(): void {
+		unset( $GLOBALS['wpdb'] );
+
+		parent::tearDown();
+	}
+
+	/**
+	 * @dataProvider providerTestData
```
Comment (remyperona) [inline tests/Unit/inc/ThirdParty/Themes/Divi/handleSaveTemplate.php]:
```suggestion
	 * @dataProvider configTestData
```

File: tests/Unit/inc/ThirdParty/Themes/Divi/handleSaveTemplate.php [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+		}
+
+		$divi = new Divi( $options_api, $options, $delayjs_html );
+
+		$divi->handle_save_template( 1 );
+	}
+
+	public function providerTestData() {
+		return $this->getTestData( __DIR__, 'handleSaveTemplate' )['test_data'];
+	}
```
Comment (remyperona) [inline tests/Unit/inc/ThirdParty/Themes/Divi/handleSaveTemplate.php]:
```suggestion
```

File: tests/Unit/inc/ThirdParty/Themes/Divi/handleDiviAdminNotice.php [hunk 5]
```diff
@@ -0,0 +1,67 @@
+<?php
+namespace WP_Rocket\tests\Unit\inc\ThirdParty\Themes\Divi;
+
+use Mockery;
+use WP_Rocket\Tests\Unit\TestCase;
+use WP_Rocket\ThirdParty\Themes\Divi;
+use Brain\Monkey\Functions;
+use wpdb;
+use function Brain\Monkey\Functions;
```
Comment (remyperona) [inline tests/Unit/inc/ThirdParty/Themes/Divi/handleDiviAdminNotice.php]:
```suggestion
```

File: tests/Unit/inc/ThirdParty/Themes/Divi/handleDiviAdminNotice.php [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+class Test_HandleDiviAdminNotice extends TestCase {
+
+	protected function setUp(): void {
+		parent::setUp();
+
+		$this->stubTranslationFunctions();
+	}
+
+	/**
+	 * @dataProvider providerTestData
```
Comment (remyperona) [inline tests/Unit/inc/ThirdParty/Themes/Divi/handleDiviAdminNotice.php]:
```suggestion
	 * @dataProvider configTestData
```

File: tests/Unit/inc/ThirdParty/Themes/Divi/handleDiviAdminNotice.php [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+		}
+
+		$divi = new Divi( $options_api, $options, $delayjs_html );
+
+		$divi->handle_divi_admin_notice();
+	}
+
+	public function providerTestData() {
+		return $this->getTestData( __DIR__, 'handleDiviAdminNotice' )['test_data'];
+	}
```
Comment (remyperona) [inline tests/Unit/inc/ThirdParty/Themes/Divi/handleDiviAdminNotice.php]:
```suggestion
```

**Review by remyperona — CHANGES_REQUESTED** [review]

**Review by remyperona — APPROVED** [review]

**Comment by Mai-Saad** [comment]
@engahmeds3ed Thanks for the PR.
Please notice the exploratory test notes below.
1- The transient `rocket_divi_notice` shall be deleted when deleting WPR
2- When we save on the layout level still not displaying a notice. (only displayed when we edit inside the header itself)

**Comment by engahmeds3ed** [comment]
@Mai-Saad 

All done now

**Review by remyperona — APPROVED** [review]

**Comment by vmanthos** [comment]
@engahmeds3ed Thank you for the PR.

There are a couple of scenarios that are failing. 

With Remove Unused CSS enabled and used CSS existing in the database:
1. Disable Remove Unused CSS.
2. Edit the global header in Divi's Theme Builder for any existing template.
3. Enable Remove Unused CSS -> the notice is displayed. :heavy_check_mark: 
4. Disable Remove Unused CSS -> the notice isn't displayed. :heavy_check_mark: 
5. Enable Remove Unused CSS -> the notice is _NOT_ displayed. :x: 

For the second scenario, with Remove Unused CSS enabled and used CSS existing in the database:
1. Disable Remove Unused CSS.
2. Delete a template using the Divi Theme Builder  -> the notice is not displayed. :heavy_check_mark: 
3. Enable Remove Unused CSS -> the notice is _NOT_ displayed. :x: 

Can you please look into these?

**Comment by MathieuLamiot** [comment]
As discussed [here](https://wp-media.slack.com/archives/C015FT0RBKQ/p1691564901977129), I created a dedicated follow-up issue #6095. I move back this PR to Ready for QA @vmanthos

**Review by vmanthos — APPROVED** [review]
Working as expected. :+1: 

**TestRail report:** [testrail-report-514.pdf](https://github.com/wp-media/wp-rocket/files/12303035/testrail-report-514.pdf)
